### ISSUE TITLE
Use intent specification of image croping

### ISSUE THREAD

**Issue by friedger** [Yalantis/uCrop#1]
There is an intent com.android.camera.action.CROP (http://www.openintents.org/action/com-android-camera-action-crop/)
You could use the same extra keys and use the data uri instead of input key. Use MediaStore.EXTRA_OUTPUT for the output uri.

**Comment by shliama** [comment]
Yes I agree. Should be fixed in next update.

**Comment by hss01248** [comment]
this intent will not work on some cellphone such as meizu and some of huawei,their rom has been changed to much.Setting the input and output uri is a nice way to avoid the problem.
just see here: http://www.cnblogs.com/over140/archive/2012/12/17/2821874.html

**Comment by shliama** [comment]
We decided to keep uCrop builder API in the near future.
