### ISSUE TITLE
can you add functionality to make cropping rectangle resizeble by touching the edges? like google photos image cropping tool

### ISSUE THREAD

**Issue by developer--** [Yalantis/uCrop#10]

**Comment by shliama** [comment]
Yes I can. But it's not in our plans for future updates at the moment.

There are libraries that allow you to resize cropping rectangle but not an image, others (like uCrop) allow you to resize image - but not cropping rectangle. And we think this approach is much better.
Furthermore our UCropActivity provides a set of most common crop ratios to choose from.

If you want totally dynamic cropping rectangle - please fork current code and look at OverlayView class.

**Comment by developer--** [comment]
Ok, thanks. I'll try

**Comment by Rainer-Lang** [comment]
@shliama Could you give us some reasons WHY you choose this approach?
