### ISSUE TITLE
Crop this image crash in version 2.0

### ISSUE THREAD

**Issue by start141** [Yalantis/uCrop#100]
I can't catch any exception in java code, I think it is a native error.

![mirrorsedgemegahighres](https://cloud.githubusercontent.com/assets/6055764/14977235/f56d48f8-1144-11e6-838b-d4f293a7acf0.jpg)

**Comment by start141** [comment]
please do not scale or rotate this image in UCropActivity.

**Comment by iRYO400** [comment]
105MP image... for what? It's 2016, not a 2018

**Comment by start141** [comment]
@iRYO400 just for test.
maybe another smaller images has the same problem!

**Comment by shliama** [comment]
Yeah, I could reproduce it, and yes, it's just out of native memory crash :(
We are working on improvements to performance, but for now, it's great tool to work with < 16MP images.
