### ISSUE TITLE
Bounds for bitmap could not be retrieved from Uri

### ISSUE THREAD

**Issue by start141** [Yalantis/uCrop#101]
I got a toast "Bounds for bitmap could not be retrieved from Uri" every times when "crop random image".

**Comment by shliama** [comment]
This is because api that I've used https://unsplash.it/ isn't working at the moment.

**Comment by start141** [comment]
thanks

**Comment by harshitha0193** [comment]
I got a toast "Bounds for bitmap could not be retrieved from Uri" when i take a picture from the camera

**Comment by saymumsany** [comment]
I am facing the same issue while crop the image. Is this issue resolved ? I am using com.github.yalantis:ucrop:2.2.8 . I am facing this issue in Xiaomi Redmi note 8A device and some Realme devices.
