### ISSUE TITLE
Temp file created under picture folder

### ISSUE THREAD

**Issue by tuhin10** [Yalantis/uCrop#102]
After cropping the image it creates a copy of the image inside pictures folders. Is there any solution in the library to delete temp files after cropping?

**Comment by shliama** [comment]
At the moment you can handle that yourself. Remember, you give input & output uris to the library, and it won't use any other places to create a file.
So - just deleted files for both uris when you need to clean up.

**Comment by tuhin10** [comment]
got the idea thanks for your help.
