### ISSUE TITLE
Cropping doesn't work on photos taken in portrait mode

### ISSUE THREAD

**Issue by rmunk** [Yalantis/uCrop#106]
When I try to crop portrait photos, either from the photo album or directly from the camera, after setting crop area and applying the crop I get the whole image (not cropped) rotated by 90 degrees clockwise.
When cropping landscape pictures everything works ok.
I tried it in my application as well as in your demo application and it behaves the same.

My phone is Galaxy J5 (SM-J500H), Android 5.1.1

**Comment by shliama** [comment]
Thanks for the issue. This is related to https://github.com/Yalantis/uCrop/issues/111
Currently working on a fix.

**Comment by shliama** [comment]
@rmunk please try to use library version 2.1.0 - now EXIF data should be processed properly.
