### ISSUE TITLE
Library size is more than 1.3 mb

### ISSUE THREAD

**Issue by tuhin10** [Yalantis/uCrop#107]
Is it possible to shrink the size of the library?? Its adding approx 1.3 mb to my app apk.

**Comment by shliama** [comment]
If you use it to crop avatars and do not need to keep images quality as original - just stay with version 1.5.0 because 2.0.0 added native code and libraries to handle high-res images better (of course added in size)

**Comment by tuhin10** [comment]
@shliama thanx
