### ISSUE TITLE
proguard issue

### ISSUE THREAD

**Issue by sunnykinger** [Yalantis/uCrop#108]
1.5.0 worked just fine for me and yesterday I updated it to 2.0.0. 
I was making the release build and it gave me errors like can't find referenced class okhttp.OkHttpClient (I don't remember the full package name). 
so I had to put these lines to generate a release build.
`-dontwarn com.yalantis.ucrop**
-keep class com.yalantis.ucrop** { *; }
-keep interface com.yalantis.ucrop** { *; }`

**Comment by shliama** [comment]
Hi and thanks for the report.
I'll updated readme with proguard info :octocat:

**Comment by shliama** [comment]
Updated README.md
