### ISSUE TITLE
resource @attr/colorPrimary is marked as private

### ISSUE THREAD

**Issue by sunnykinger** [Yalantis/uCrop#109]
Version: 2.0.0
In some layout files I am using `?attr/actionBarSize` and `?attr/colorPrimary`. It displays warning `The resource @attr/colorPrimary is marked as private in com.yalantis:ucrop`. 

It doesn't causes any problems though. Just wanted to report.

**Comment by shliama** [comment]
Thanks for your report :octocat: 
But unfortunately I cannot reproduce this. I'm sure the library only makes own values private (so you do not see a bunch of ucrop_xxx dimens/colors/etc). Maybe I am wrong |(• ◡•)|
