### ISSUE TITLE
Error when importing library with gradle

### ISSUE THREAD

**Issue by khrizt** [Yalantis/uCrop#110]
Hi,

I'm giving a shot this library and I imported in my android project, with only the Gradle sync I got this error:

`Error:(35) No resource identifier found for attribute 'srcCompat'` 

Is there any library or dependency I don't know about?

Thanks

**Comment by shliama** [comment]
Hi and thanks for giving our library a shot :)
I think you should define vector support in your gradle config:
http://android-developers.blogspot.com/2016/02/android-support-library-232.html 

P.S. what version of support library and gradle plugin do you use?

**Comment by khrizt** [comment]
I'm using support library version 23.1.1 and gradle 2.1.0. I'll add the vector support and try again, thanks!

**Comment by khrizt** [comment]
Adding 

`vectorDrawables.useSupportLibrary = true`

to build.gradle didn't solve the error...

**Comment by shliama** [comment]
Have you updated support library version to at least 23.2.1 (now it's 23.3.0) ?

**Comment by khrizt** [comment]
sorry man, I'm stupid! xDD now works
