### ISSUE TITLE
Library no cropping what it should

### ISSUE THREAD

**Issue by khrizt** [Yalantis/uCrop#111]
Hi,

Implementing UCrop in my project I found a problem when cropping some images, I'm attaching the screenshots, hope they help:

Cropping the image

![screenshot_2016-05-05-17-38-34](https://cloud.githubusercontent.com/assets/725227/15048104/45cd424a-12e8-11e6-8f7d-65a446263b5c.png)

The result

![screenshot_2016-05-05-17-38-44](https://cloud.githubusercontent.com/assets/725227/15048253/083ae404-12e9-11e6-88a4-d5606ff2e166.png)

Looks like rotates the image and does not get the correct coordinates. Maybe something with the meta-data of the images, sometimes I had problems with rotated images from Samsung or LG cameras.

**Comment by shliama** [comment]
How can I reproduce it? Do you touch/change image position before cropping?
Please attach the original image.

**Comment by khrizt** [comment]
Sorry here is the original image and yep I change the image position before cropping

![20160505_173429](https://cloud.githubusercontent.com/assets/725227/15048782/3e74bafc-12eb-11e6-9c71-661dba9a0a72.jpg)

Attaching the image appeared in landscape format so it looks like it's something about meta-data rotation with attribute ExifInterface.TAG_ORIENTATION.

**Comment by shliama** [comment]
Yeah, I could reproduce it on my device too. Seems to be issue with Exif properties.
I'll try to fix in the next update :)

**Comment by khrizt** [comment]
Thanks man! I'll put it on my app on the next update.

**Comment by shliama** [comment]
@khrizt please try to use library version 2.1.0 - now EXIF data should be processed properly.

**Comment by khrizt** [comment]
Thanks man, I'll give it a try and tell you something

**Comment by khrizt** [comment]
Looks like everything is allright, I plan on adding your library to the release this week

**Comment by zzxxasp** [comment]
the bug is still exists in 2.1.0 from SonyZ5

**Comment by shliama** [comment]
@zzxxasp please, attach an image so I can reproduce the bug.

**Comment by TeeRawk** [comment]
outdated
