### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by yuhuibin123** [Yalantis/uCrop#112]
in Version: 2.0， in getMaxBItmapSize() ，the maxBitmapSize  is multiplied by 2. 
It can cause OOM

**Comment by shliama** [comment]
If it causes OOM - inSampleSize is multiplied by 2 until image can be processed.
I multiply maxBitmapSize by 2 so image quality is high enough to zoom in an image.
Modern devices can handle it easily :octocat:
