### ISSUE TITLE
Rotation with Picked image not working.

### ISSUE THREAD

**Issue by sachin-shelke** [Yalantis/uCrop#114]
Whenf we pick image from galary and trying to crop it with rotation, it won't rotate image. 
Im checking it throught Google Play Store app on Nexus 5.
Also image size not reduced.

**Comment by shliama** [comment]
So you are saying that library is not working at all? That's bad :(
Could you possibly attach an image so I can reproduce the bug myself?

**Comment by shliama** [comment]
@sachin-shelke please try to use library version 2.1.0 or check todays Google Play Store app update 1.2.1
