### ISSUE TITLE
Stackoverflow error after fixed times start Ucrop Activity from fragment (Android API 19)

### ISSUE THREAD

**Issue by nhudinh2103** [Yalantis/uCrop#115]
I have issues when start Ucrop Activity from fragment after 5 times in my phone.

Flows: Click -> Open Gallery -> CropActivity -> Return back to Click -> Open ...

I have tested it in 1.5 and 2.0 but both failed in API 19 (KitKat). 

When run it in API 21 (Lollipop) android studio emulator, eveything was fine.

Image:

![ucrop-error](https://cloud.githubusercontent.com/assets/17499217/15094118/cb4a30d0-14c4-11e6-808e-7539db8b843b.png)

Code to start UcropActivity:

```
private void startCropActivity(@NonNull Uri uri) {
        String destinationFileName = SAMPLE_CROPPED_IMAGE_NAME + ".png";

        Activity activity = getActivity();

        if (activity != null) {
            UCrop uCrop = UCrop.of(uri, Uri.fromFile(new File(activity.getCacheDir(), destinationFileName)));

            uCrop = config(uCrop);

            uCrop.start(activity, this); // this is a fragment

        }
    }
```

Stacktrace:

> 05-08 02:10:13.887 28064-28064/com.cse.hcmut.mobileappdev E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                             Process: com.cse.hcmut.mobileappdev, PID: 28064
>                                                                             java.lang.StackOverflowError
>                                                                                 at android.text.TextLine.drawTextRun(TextLine.java:1000)
>                                                                                 at android.text.TextLine.handleText(TextLine.java:798)
>                                                                                 at android.text.TextLine.handleRun(TextLine.java:966)
>                                                                                 at android.text.TextLine.drawRun(TextLine.java:396)
>                                                                                 at android.text.TextLine.draw(TextLine.java:194)
>                                                                                 at android.text.Layout.drawText(Layout.java:356)
>                                                                                 at android.widget.Editor.drawHardwareAccelerated(Editor.java:1414)
>                                                                                 at android.widget.Editor.onDraw(Editor.java:1337)
>                                                                                 at android.widget.TextView.onDraw(TextView.java:5318)
>                                                                                 at android.view.View.draw(View.java:14728)
>                                                                                 at android.view.View.getDisplayList(View.java:13588)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.getDisplayList(View.java:13580)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.getDisplayList(View.java:13580)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.getDisplayList(View.java:13580)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.draw(View.java:14739)
>                                                                                 at android.widget.FrameLayout.draw(FrameLayout.java:534)
>                                                                                 at android.widget.ScrollView.draw(ScrollView.java:1614)
>                                                                                 at android.view.View.getDisplayList(View.java:13588)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.getDisplayList(View.java:13580)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.getDisplayList(View.java:13580)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.getDisplayList(View.java:13580)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1131)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.getDisplayList(View.java:13580)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.getDisplayList(View.java:13580)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
>                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3070)
>                                                                                 at android.view.View.getDisplayList(View.java:13580)
>                                                                                 at android.view.View.getDisplayList(View.java:13635)
>                                                                                 at android.view.View.draw(View.java:14430)
>                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3252)
>                                                                                 at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1373)
>                                                                             	at android.view.Vi

**Comment by shliama** [comment]
Hi,
I can see that CoordinatorLayout & DrawerLayout is referenced in the stacktrace, but uCrop does not use both widgets.
Therefore I think you should search for a cause in your code.
