### ISSUE TITLE
Set minimum image width/height

### ISSUE THREAD

**Issue by DavzorD** [Yalantis/uCrop#122]
How can I set the minimum image width/height?

**Comment by tuhin10** [comment]
+1

**Comment by shliama** [comment]
Can you specify some requirements for the feature?
Should library prevent zooming less than minimum width/height?
What if supplied image is already less than minimum size?

It would be better if you provide me with some use-case in an application, so I can figure out the best API for the feature. :octocat:

**Comment by TeeRawk** [comment]
requirements not specified
