### ISSUE TITLE
How can we send UCrop features through UCrop.options?

### ISSUE THREAD

**Issue by omegasoft7** [Yalantis/uCrop#126]
Hi

We are trying to use your lib in our project. We are sending UCrop.options and then proceeding with Cropping. But problem is there are some features that we cant set on UCrop.option some features like:

UCrop.of(sourceUri, destinationUri)
    .withAspectRatio(16, 9)   <------
    .withMaxResultSize(maxWidth, maxHeight)  <------
    .start(context);

Do you have a solution to pass those parameters through UCrop.options?

**Comment by shliama** [comment]
You cannot do this at the moment. I've designed `Options` class to handle **secondary** configuration parameters. If you really need this feature - it would be faster to fork and edit the `UCrop` class.
Otherwise, you can wait and I'll add this feature in the next update.

**Comment by omegasoft7** [comment]
Will wait for that. Thanks

**Comment by shliama** [comment]
@omegasoft7 please check version 2.1.0 - I've added API so you can set those properties via both UCrop & Options classes.

**Comment by omegasoft7** [comment]
@shliama Thanks That is great
