### ISSUE TITLE
When do ResultCode == UCrop.RESULT_ERROR == 96 occurs?

### ISSUE THREAD

**Issue by icecoolcat** [Yalantis/uCrop#127]

**Comment by icecoolcat** [comment]
java.lang.NullPointerException: Both input and output Uri must be specified

**Comment by shliama** [comment]
`java.lang.NullPointerException: Both input and output Uri must be specified` - it means, you should not pass `null` to `UCrop.of(sourceUri, destinationUri)`

**Comment by icecoolcat** [comment]
Thanks i found out what the error is alr. Stupid mistake on my part. 👍
