### ISSUE TITLE
Why is 93% of the code in c++?

### ISSUE THREAD

**Issue by VictorAlbertos** [Yalantis/uCrop#128]
Hi :)

I've been surprised that almost the entire library is coded using c++. Is there any specific reason for this? Something due to image processing?

I'm just curious.

Thanks!

**Comment by shliama** [comment]
Hello,
uCrop is using [CImg](http://cimg.eu/) to process image, and it contains just one **.h** file that has 56k lines of c++ code. Therefore it's only 7% of Java code in total :octocat:

**Comment by VictorAlbertos** [comment]
Thanks ;)
