### ISSUE TITLE
Square options: bouncing and center crop

### ISSUE THREAD

**Issue by CeccoCQ** [Yalantis/uCrop#13]
Hi,
thanks for your awesome library.
I would to have some info about square aspect ratio. You can find a demo video here: https://youtu.be/XPj1yEXzl2U

As you can see, I have problem to crop at the top and the bottom of the selected image. I can crop correctly only if I add a zoom operation on the image.

Where am I wrong?

**Comment by shliama** [comment]
You are not wrong here. It's just how the library works at the moment :-1: 
I'm aware of the issue and working on the solution.
This problem has #1 priority atm so should be fixed soon.

#3 #6 Status will be updated in this issue

**Comment by shliama** [comment]
@CeccoCQ Please check version 1.2.0, above issue must be fixed. I've updated core logic so an image must correct its position smoothly and obviously.

**Comment by CeccoCQ** [comment]
Yes, I confirm that all works correctly!

Thank you man!
