### ISSUE TITLE
三星crop图片旋转

### ISSUE THREAD

**Issue by ifmvo** [Yalantis/uCrop#130]
三星手机crop后图片是逆时针旋转90度的

**Comment by shliama** [comment]
Please use english language for issues.
P.S. I'm aware of this bug, currently working on it.

**Comment by shliama** [comment]
@ifmvo please check version 2.1.0 - now EXIF data should be processed properly.

**Comment by AvinashJha1** [comment]
Hello version 2.1 is not working in in android studio of 22 sdk version .
