### ISSUE TITLE
Receiving width and height of croped image in activityResult

### ISSUE THREAD

**Issue by adauvalter** [Yalantis/uCrop#132]
After cropping, I encode an image with okio directly into base64 string. But to fulfill a server request I need to set width and height into request as well. Is there any possibility to receive as Ucrop.getWidth(data) such as uri?

**Comment by shliama** [comment]
You can do it easily, for example:

```java
private void getImageSize(@NonNull Uri uri){
   BitmapFactory.Options options = new BitmapFactory.Options();
   options.inJustDecodeBounds = true;
   BitmapFactory.decodeFile(new File(uri.getPath()).getAbsolutePath(), options);
   int imageHeight = options.outHeight;
   int imageWidth = options.outWidth;
}
```

**Comment by adauvalter** [comment]
ok, I tried already this workaround :) Anyway thank you. Issue could be close.
