### ISSUE TITLE
duplicate entry: okio/AsyncTimeout$1.class

### ISSUE THREAD

**Issue by xiadeye** [Yalantis/uCrop#133]
Error:Execution failed for task ':catwoman:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class

i have tried add:
 compile( 'com.yalantis:ucrop:1.5.0'){
        transitive = true
    }
and
 compile( 'com.yalantis:ucrop:1.5.0'){
        exclude module: 'com.squareup.okio'
    }
but it's useless ...
BTW,if I don't import uCrop,there is no problem

**Comment by shliama** [comment]
please try

 ```
compile ('com.yalantis:ucrop:1.5.0') {
    exclude group: 'okio'
}
```

**Comment by xiadeye** [comment]
@shliama it doesn't work...

**Comment by shliama** [comment]
same error?

**Comment by xiadeye** [comment]
yes

**Comment by xiadeye** [comment]
@shliama yes

**Comment by shliama** [comment]
Well, try to google how to combine two libraries with same dependencies without conflicts.
I have this library working on a several projects with different okhttp/okio versions and it's ok.
I don't think I can help you with that without looking into project code.

**Comment by xiadeye** [comment]
@shliama I finally fixed the problem by adding:
compile ('com.yalantis:ucrop:1.5.0'){
        exclude module:'okio'
    }

**Comment by shliama** [comment]
Good! Sorry, I was so close :(
