### ISSUE TITLE
Redmi Note2 (xiao mi mobile phone)

### ISSUE THREAD

**Issue by wallacedong** [Yalantis/uCrop#134]
Look at the picture here, sometimes happened
log: "width must be > 0"
![a](https://cloud.githubusercontent.com/assets/17972665/16374612/d0e068b0-3c89-11e6-8726-130548817da7.png)
![b](https://cloud.githubusercontent.com/assets/17972665/16374621/dbff4d60-3c89-11e6-97f1-f4eb347a3229.png)

**Comment by shliama** [comment]
What is the library version?

**Comment by wallacedong** [comment]
@shliama 2.1.0,but the 1.5 also has this problem,it crash when i click the "√"，the log is "width must be > 0"
My English is not good, I am sorry!

**Comment by shliama** [comment]
Please attach image file, so I can reproduce this bug.

**Comment by wallacedong** [comment]
![a](https://cloud.githubusercontent.com/assets/17972665/16375785/ca92b638-3c8f-11e6-8e6b-cd87ab45eef7.jpg)

**Comment by shliama** [comment]
I've looked and the first image again, and cannot see your crop area.

![screenshot_20160627-152537](https://cloud.githubusercontent.com/assets/2311626/16375938/89875874-3c7b-11e6-98d2-0265cfcf8f32.png)

What config do you use for UCrop?

**Comment by wallacedong** [comment]
@shliama This is my way of use
`UCrop.Options options = new UCrop.Options();
        options.setCompressionFormat(Bitmap.CompressFormat.JPEG);
        options.setHideBottomControls(true);
        options.setToolbarColor(getColor(activity, R.color.colorPrimary));
        options.setStatusBarColor(getColor(activity, R.color.colorPrimaryDark));
        UCrop.of(photoUri, Uri.fromFile(new File(FileManager.getTempFilePath(), String.valueOf(System.currentTimeMillis())))).withOptions(options)
                .withAspectRatio(1, 1).start(activity);`

**Comment by shliama** [comment]
"width must be > 0" - because you have no crop area selected. And I cannot reproduce it at all. Don't you have any other logs from the library?

**Comment by wallacedong** [comment]
`java.lang.RuntimeException: An error occured while executing doInBackground()
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at android.os.AsyncTask$3.done(AsyncTask.java:300)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at java.lang.Thread.run(Thread.java:818)
06-27 18:02:59.463 E/AndroidRuntime( 3068): Caused by: java.lang.IllegalArgumentException: width must be > 0
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at android.graphics.Bitmap.checkWidthHeight(Bitmap.java:387)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:678)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:647)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at com.yalantis.ucrop.task.BitmapCropTask.crop(BitmapCropTask.java:144)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:88)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:24)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
06-27 18:02:59.463 E/AndroidRuntime( 3068): 	... 4 more`

**Comment by shliama** [comment]
These are logs from 1.5.0? Can you post stacktrace for 2.1.0 starting from UCropActivity launch and until the crash?

And again, can you see crop bounds (white grid) that overlays image or not?

**Comment by wallacedong** [comment]
These are logs from 2.1.0, i'm trying to use the source code

**Comment by shliama** [comment]
Nope. "at com.yalantis.ucrop.task.BitmapCropTask.crop(BitmapCropTask.java:144)" are from old uCrop versions. Now there are no such code at all, because I don't even use `Bitmap.createBitmap` anymore.

**Comment by wallacedong** [comment]
ok,I try again,thinks

**Comment by wallacedong** [comment]
may be android studio instant run bug
