### ISSUE TITLE
current image matrix is not updated

### ISSUE THREAD

**Issue by lalavany** [Yalantis/uCrop#139]
Hi,

When I execute mGestureCropImageView.setImageMatrix(matrix), the mCurrentImageMatrix is not updated in TransformImageView class.

**Comment by shliama** [comment]
Hello,

that's because `mGestureCropImageView.setImageMatrix(matrix)` is not uCrop api, it is a method of the `ImageView` class. 
`mCurrentImageMatrix` is updated via other methods (e.g. postScale, postTranslate, postRotate).
Maybe it's not obvious, and I should refactor api a bit.

**Comment by shliama** [comment]
Please check the latest uCrop version :octocat: 
Now you can choose between:

##### Lightweight general solution 
```groovy
compile 'com.yalantis:ucrop:2.2.0' 
```

##### Get power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
``` groovy
compile 'com.yalantis:ucrop:2.2.0-native'
 ```
