### ISSUE TITLE
Could not load uri from Gallery.

### ISSUE THREAD

**Issue by HanderWei** [Yalantis/uCrop#141]
My code to select a picture:

```
Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
intent.setType("image/*");
startActivityForResult(intent, CHOOSE_FILE_RESULT_CODE);
```

then get Uri such like 

```
content://com.android.providers.media.documents/document/image%3A147994
```

and this:

```
file:///storage/emulated/0/Download/IMG_20150914_000751.jpg
```

but UCrop cannot load the image.(the progressbar is always running, the ImageView shows black background).

![Uploading 1.pic_hd.jpg…]()

Any help will be appreciated. Thanks!

**Comment by shliama** [comment]
Hello,

It would be nice if you attach those images and any logs so I can reproduce the bug.

**Comment by olivercm** [comment]
@shliama You can reproduce the bug by below

Intent intent = new Intent(Intent.ACTION_GET_CONTENT);
intent.setType("image/*");
startActivityForResult(intent, CHOOSE_FILE_RESULT_CODE);

in onActivityResult method, get uri by 

Uri selectedUri = data.getData();
UCrop uCrop = UCrop.of(MainActivity.this, selectedUri);

**Comment by shliama** [comment]
Please try the sample. It is working on whole bunch of different devices and has logic to pick images either from camera intent or from file pickers.
If you still have issues I need to know, are there any error logs? Attached image sample would be nice too.

**Comment by AvatarQing** [comment]
I met the same problem... Is there anyone solved this ?

**Comment by AvatarQing** [comment]
I wait in this page for several minutes, and finally it can show the image normally, but this wait too long! and after I relaunch app, it still has to wait several minutes to show the image.
I'm using `compile 'com.yalantis:ucrop:2.2.0'` on Nexus4 with Android 6.0.

**Comment by AvatarQing** [comment]
I read the ucrop's source code, I guess I found the problem. `BitmapLoadTask` is extend `AsyncTask`, and every instance of `AsyncTask` is using the same thread pool by default which has a small pool size. When our app use `AsyncTask` mutiple times in other place before open `UCropActivity`, `AsyncTask`'s default thread pool has reached max size, then open `UCropActivity`, `BitmapLoadTask` has to wait to execute until other instance of `AsyncTask`'s execution finished. I think the author should execute `BitmapLoadTask` on a custom thread pool.
