### ISSUE TITLE
Do you have an alternative for iOS?

### ISSUE THREAD

**Issue by dms90** [Yalantis/uCrop#144]
Great job! 👏 👏 

Do you have an alternative in Swfit to integrate in an iOS app?

Thanks and regards,
Diego

**Comment by shliama** [comment]
Thanks (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
Not yet, but it will be for sure :octocat: but no ETA yet.

**Comment by mxyolande** [comment]
what about now ?

**Comment by inni-indraneel** [comment]
Now ??

**Comment by NikhilManapure** [comment]
Now?

**Comment by khushDesai** [comment]
Now?

**Comment by gregory-light-it** [comment]
now?

**Comment by ghost** [comment]
now?
