### ISSUE TITLE
Mutate() is not supported for older platform

### ISSUE THREAD

**Issue by aliang5820** [Yalantis/uCrop#145]
`E/UCropActivity: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices`

excuse me,how to override it?

**Comment by shliama** [comment]
Hello
You just need to add following line to your project **colors.xml** file:
`<color name="ucrop_color_toolbar_widget">#your_color_here</color>`

**Comment by aliang5820** [comment]
ok,thx

**Comment by aliang5820** [comment]
excuse me, how to change the crop activity's toolbar background color?default is orange,i want to change to special color

**Comment by shliama** [comment]
What about taking a look at https://github.com/Yalantis/uCrop/blob/master/sample/src/main/java/com/yalantis/ucrop/sample/SampleActivity.java line 303? :)

**Comment by abhi08singh** [comment]
After Doing all these things i am getting the same Error

E/UCropActivity: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices

and the Tick will not appeared on the very right side of the cropper Screen , inspite of that it will show a progress dialog . and does not load the images .

the Phone Api level is 17 .
the day before today all things are working fine in my app

**Comment by shliama** [comment]
I'll make this message with Info priority in the next update so it doesn't confuse you.
if Mutate() is not supported - it just indicates that you won't be able to color progress bar via passing color to uCrop builder. But just add `ucrop_color_toolbar_widget` color resource inside your app `color.xml` file.

This error has nothing to do with image loading etc.
If your image doesn't load properly - please attach error logs & image if possible.

**Comment by TeeRawk** [comment]
resolved
