### ISSUE TITLE
Crop crash

### ISSUE THREAD

**Issue by aliang5820** [Yalantis/uCrop#146]
[log.txt](https://github.com/Yalantis/uCrop/files/351324/log.txt)

this is log, i dont kown how to fix the crash

**Comment by shliama** [comment]
Hello, I'll try to help you, but first - can you specify the device and Android version?

**Comment by aliang5820** [comment]
version: 4.4.4
device:vivo x5 max

**Comment by shliama** [comment]
Unfortunately I cannot do a lot with this crash cause:
`A/libc: Fatal signal 6 (SIGABRT) at 0x00002e9f (code=-6), thread 11980 (AsyncTask #4)`

Can you please attach the image file so I'll try to reproduce the error?

**Comment by TeeRawk** [comment]
outdated
