### ISSUE TITLE
Crop for Camera 

### ISSUE THREAD

**Issue by yasinkacmaz** [Yalantis/uCrop#147]
Hey i am using your library and i can able to crop images from gallery. I am using same method to crop image from camera but the Cropping Activity isnt launching. 

I am using like : 

```
UCrop.of(sourceUri,destinationUri)
                    .withOptions(options)
                    .withMaxResultSize(maxWidth, maxHeight)
                    .start(this);
```

And getting source uri from camera like that :

`Uri uricamera=data.getData();
                startCrop(uricamera,1000,1000);`

and destination uri : 
```
String destinationFileName = SAMPLE_CROPPED_IMAGE_NAME + ".png";
Uri destinationUri=Uri.fromFile(new File(getCacheDir(), destinationFileName));
```

I am opening camera and taking picture but crop activity cannot be launched. I got theese codes from your sample app and i want to use crop with camera too. So what should i do ?

**Comment by 401885064** [comment]
I have too problem  , do you work it?

**Comment by yasinkacmaz** [comment]
Can you check camera permission at runtime. Actaully can you test with 6.0 or higher device.
