### ISSUE TITLE
Freestyle cropping will return wrong UCrop.EXTRA_OUTPUT_CROP_ASPECT_RATIO

### ISSUE THREAD

**Issue by suau** [Yalantis/uCrop#150]
When Freestyle cropping is used, the returned aspect ratio in the extras is wrong.

**Comment by shliama** [comment]
Hello @suau and thanks for the issue.
I'll try to reproduce this and if there is a bug - I'll add a fix in the next library update.

**Comment by shliama** [comment]
I've reproduced the bug and the fix will be available soon with the new library update.

**Comment by TeeRawk** [comment]
resolved
