### ISSUE TITLE
Two finger rotate

### ISSUE THREAD

**Issue by canberkcakmak** [Yalantis/uCrop#151]
Hi :) is there any way to disable two finger rotate picture? Thank you so much

**Comment by canberkcakmak** [comment]
By the way here is my options: 

```
UCrop.Options options = new UCrop.Options();
        options.setCompressionFormat(Bitmap.CompressFormat.JPEG);
        options.setCompressionQuality(100);
        options.setToolbarColor(context.getResources().getColor(R.color.white));

        options.setToolbarWidgetColor(context.getResources().getColor(R.color.black));
        options.setStatusBarColor(context.getResources().getColor(R.color.colorPrimaryDark));

        UCrop.of(sourUri,destUri)
                .withOptions(options)
                .withAspectRatio(1, 1)
                .start(getActivity(),this);

```

**Comment by shliama** [comment]
Hello @canberkcakmak.
Yes you can control available gestures via `UCrop.Options.setAllowedGestures()` method.

**Comment by gikarasojo** [comment]
@shliama what about disabling image from moving around and instead enable the crop frame to move?

**Comment by shliama** [comment]
@gikarasojo I've chosen another way for this library - fixed crop frame and moving an image. It's possible to add this feature but it's another story :) Of course - fork/pull-requests are welcome :octocat:

**Comment by canberkcakmak** [comment]
Thank you. This is the way : 

`options.setAllowedGestures(UCropActivity.SCALE, UCropActivity.NONE, UCropActivity.SCALE);`
