### ISSUE TITLE
set EXTRA_STATUS_BAR_COLOR not working

### ISSUE THREAD

**Issue by xuetenglong** [Yalantis/uCrop#153]
android version 5.0.1
UCrop uCrop = UCrop.of(uri1, uri2);
                uCrop.getIntent(this).putExtra(UCrop.Options.EXTRA_TOOL_BAR_COLOR, ContextCompat.getColor(this, cn.com.jinyinmao.common.R.color.mis_actionbar_color));
                uCrop.getIntent(this).putExtra(UCrop.Options.EXTRA_STATUS_BAR_COLOR, ContextCompat.getColor(this, cn.com.jinyinmao.common.R.color.mis_actionbar_color));

statusbar color not change

**Comment by longerxue** [comment]
Mobile phone : Redmi Note2

**Comment by longerxue** [comment]
private void setStatusBarColor(@ColorInt int color) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
            if (getWindow() != null) {
                getWindow().setStatusBarColor(color);
            }
        }
    }

See the source code  should add getWindow().addFlags(WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS);

**Comment by shliama** [comment]
@longerxue Hello and thanks for the reported issue.
I'll take a look at this problem and add a fix in the next update.

**Comment by shliama** [comment]
I've added FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS to the current build, it will be available with the next library update very soon.

**Comment by shliama** [comment]
Please check the latest uCrop version :octocat: 
Now you can choose between:

##### Lightweight general solution 
```groovy
compile 'com.yalantis:ucrop:2.2.0' 
```

##### Get power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
``` groovy
compile 'com.yalantis:ucrop:2.2.0-native'
 ```

**Comment by TeeRawk** [comment]
resolved
