### ISSUE TITLE
Radius of the Round mask 

### ISSUE THREAD

**Issue by tomlobato** [Yalantis/uCrop#154]
Hello! Great lib. Saved my week :)
I`m using setOvalDimmedLayer(true). Is there a way to set the radius of the layer?

**Comment by shliama** [comment]
@tomlobato Hello and thanks for using uCrop :)

Well, there are no such feature atm. But you can override `ucrop_view.xml` layout and define your own paddings/size for the OverlayView.

**Comment by sench93** [comment]
setOvalDimmedLayer(true). After giving this options it is cropping square(rectangle) image not oval. Can you help ?

**Comment by shliama** [comment]
uCrop does not crop oval/circle out of bitmap, because it is useless. If you need to show it like avatar afterwards - use Fresco lib or some Picasso Circle transformation.

setOvalDimmedLayer() method is just to show user how it will look like after image is cropped.

**Comment by 3383389** [comment]
@shliama 

> But you can override ucrop_view.xml
Hello! Can you explain how to do this correctly?
I can'n find info for this
