### ISSUE TITLE
screen is not fluent at all

### ISSUE THREAD

**Issue by aliang5820** [Yalantis/uCrop#155]
if use a picture of the dark.when move picture, screen is not fluent at all

**Comment by shliama** [comment]
@aliang5820 excuse me, but I don't really understand what is the issue. Please, describe it better and attach an image so I can try to reproduce it.

**Comment by aliang5820** [comment]
Drag the tonal darker images, images move slowly

**Comment by shliama** [comment]
@aliang5820 now I see what you mean. Well it's in fact not clear when most of the image is black...
I can think of `android.support.v7.graphics.Palette` as a possible tool to solve this issue, but I need some time on research.

**Comment by TeeRawk** [comment]
outdated
