### ISSUE TITLE
FileUtils.getMimeType() is case sensitive

### ISSUE THREAD

**Issue by lucas34** [Yalantis/uCrop#158]
Hi,

I'm using the function getMimeType(File file) from FileUtils. 
My file name has an upper case extension : .JPG. My old camera saved the pictures like this.
Internally, you are using MimeTypeMap to resolve the mime type. This function is case sensitive.
I suggest to lower case the extension before sending this to MimeTypeMap tool. Otherwise the function will not resolve the mimetype.

I don't know how you are using the FileUtils internally and if this change will have side effect or not. 

Regards.

**Comment by shliama** [comment]
Hi @lucas34 ,
in fact uCrop doesn't use this method and almost all methods in `FileUtils`. That's kinda my fault, took it from the other project and didn't clean up :(
So unfortunately `FileUtils` won't have this method in the next update (don't want to keep unused stuff in the library). But hey, thanks for the info 👍
