### ISSUE TITLE
Changing color of the parent layout of bottom controls

### ISSUE THREAD

**Issue by dgngulcan** [Yalantis/uCrop#161]
Is it possible to change background color of bottom controls? 
The white space in the picture: http://imgur.com/a/yhnuS
Kind regards.

**Comment by shliama** [comment]
Hello @dgngulcan , yes you can do that by overriding `ucrop_color_widget_background` resource with your colour inside your project `color.xml` file.

**Comment by samuel-mobile-latte** [comment]
Thank you @shliama, just saved my time :)
