### ISSUE TITLE
I found the picture webp call Bitmap Crop Task.crop CImage error occurs

### ISSUE THREAD

**Issue by pollyyeung** [Yalantis/uCrop#166]
java.io.IOException: [instance(0,0,0,0,0x0,non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '/storage/emulated/0/tencent/QQ_Images/1465293604334.webp'.

**Comment by shliama** [comment]
Yes, those are not supported in 2.+ builds because uCrop uses native library and atm it has only libjpeg and libpng under the hood.
So you can either use 1.+ version or wait until I add that support (have it in plans but no ETA :octocat: )

**Comment by TeeRawk** [comment]
outdated issue
