### ISSUE TITLE
can I start camera intent along with uCrop?

### ISSUE THREAD

**Issue by maher640** [Yalantis/uCrop#167]
this library is awesome but can I start camera intent with uCrop feature at the same time? so that I capture a CROPPED IMAGE.

**Comment by blakazulu** [comment]
yes you can. the library gives you the cropping intent, all you have to do is provide it with the URI...
for example you can call the camera/gallery intent like this:

`if (cameraOrGallery == "Camera") {
                    Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
                    File file = new File(Environment.getExternalStorageDirectory(), "nameOfFile" +
                            String.valueOf(System.currentTimeMillis()) + ".jpg");
                    cameraUri = Uri.fromFile(file);
                    intent.putExtra(MediaStore.EXTRA_OUTPUT, cameraUri);
                    intent.putExtra("return data", true);
                    startActivityForResult(intent, PICK_FROM_CAMERA);
                } else {
                    Intent intent = new Intent();
                    intent.setType("image/*");
                    intent.setAction(Intent.ACTION_GET_CONTENT);
                    startActivityForResult(intent, PICK_FROM_FILE);
                }`

then in your onActivityResult:

`if (resultCode == Activity.RESULT_OK) {
//start crop activity if chosen action is picture from gallery
            if (requestCode == PICK_FROM_FILE) {
                startCropActivity(data.getData());
//start crop activity if chosen action is picture from camera - it starts right after u take the picture
            } else if (requestCode == PICK_FROM_CAMERA) {
                startCropActivity(cameraUri);
//handle your cropped file
            } else if (requestCode == UCrop.REQUEST_CROP) {
                handleCropResult(data);
            }
        }`

after this you should add your startCropActivity Method - this part calles the cropping method:

`private void startCropActivity(@NonNull Uri uri) {
        String destinationFileName = ParseUser.getCurrentUser().getUsername() + "_picture.png";

        UCrop uCrop = UCrop.of(uri, Uri.fromFile(new File(getActivity().getCacheDir(),    destinationFileName)));

//if calling from a fragment use this:
        uCrop.start(getActivity(), currentFragment);
//if calling from Activity use this:
        uCrop.start(getActivity());
    }`

at the end  you add the method that handles the cropped picture handleCropResults:

` private void handleCropResult(@NonNull Intent result) {
        final imageCaptureUri = UCrop.getOutput(result);
        if (imageCaptureUri != null) {
            string path = imageCaptureUri.getPath();
            Bitmap croppedBitmap = BitmapFactory.decodeFile(path);
            imageview.setImageBitmap(croppedBitmap);
        } else {
            Log.e("crop uri is", " null");
        }
    }`

hope this works for you.

**Comment by maher640** [comment]
@blakazulu I don't think you understood my question. the regular procedure is:
1- capture image
2- store the image
3- get the image URI and passed along to the cropping activity
4- crop the image and save it.

what I need is:
**1- when you start camera intent, show cropping rectangle. Then when you take a picture, the taken picture is only what the rectangle sees.**
2- [rest of the procedure]

**Comment by blakazulu** [comment]
ohh ok... now I understand what u asked for.
interesting, i'll see if I can find an answer.

**Comment by maher640** [comment]
@blakazulu I hope you find something.

**Comment by mtkarimi** [comment]
hello brother
you need to create your own camera app with the grid guide lines
there is no default app that can do this, if you wanted we can work on this project toghether cuz i love photographying and this one is a feature that never done before. i mean as i know there is none.

**Comment by shliama** [comment]
Hello guys. No - uCrop cannot do this and I don't think it will be able to do it in the near future.
But as always, please, fork & pull:octocat:request, I'd love this feature!

**Comment by TeeRawk** [comment]
outdated

**Comment by charleyFeng** [comment]
Thank you very much .I solved my problem. @blakazulu

**Comment by blakazulu** [comment]
How did u solve it?

**Comment by rafaelkowal** [comment]
> yes you can. the library gives you the cropping intent, all you have to do is provide it with the URI...
> for example you can call the camera/gallery intent like this:
> 
> `if (cameraOrGallery == "Camera") { Intent intent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE); File file = new File(Environment.getExternalStorageDirectory(), "nameOfFile" + String.valueOf(System.currentTimeMillis()) + ".jpg"); cameraUri = Uri.fromFile(file); intent.putExtra(MediaStore.EXTRA_OUTPUT, cameraUri); intent.putExtra("return data", true); startActivityForResult(intent, PICK_FROM_CAMERA); } else { Intent intent = new Intent(); intent.setType("image/*"); intent.setAction(Intent.ACTION_GET_CONTENT); startActivityForResult(intent, PICK_FROM_FILE); }`
> 
> then in your onActivityResult:
> 
> `if (resultCode == Activity.RESULT_OK) { //start crop activity if chosen action is picture from gallery if (requestCode == PICK_FROM_FILE) { startCropActivity(data.getData()); //start crop activity if chosen action is picture from camera - it starts right after u take the picture } else if (requestCode == PICK_FROM_CAMERA) { startCropActivity(cameraUri); //handle your cropped file } else if (requestCode == UCrop.REQUEST_CROP) { handleCropResult(data); } }`
> 
> after this you should add your startCropActivity Method - this part calles the cropping method:
> 
> `private void startCropActivity(@nonnull Uri uri) {
> String destinationFileName = ParseUser.getCurrentUser().getUsername() + "_picture.png";
> 
> ```
>     UCrop uCrop = UCrop.of(uri, Uri.fromFile(new File(getActivity().getCacheDir(),    destinationFileName)));
> ```
> //if calling from a fragment use this:
> uCrop.start(getActivity(), currentFragment);
> //if calling from Activity use this:
> uCrop.start(getActivity());
> }`
> 
> at the end you add the method that handles the cropped picture handleCropResults:
> 
> `private void handleCropResult(@NonNull Intent result) { final imageCaptureUri = UCrop.getOutput(result); if (imageCaptureUri != null) { string path = imageCaptureUri.getPath(); Bitmap croppedBitmap = BitmapFactory.decodeFile(path); imageview.setImageBitmap(croppedBitmap); } else { Log.e("crop uri is", " null"); } }`
> 
> hope this works for you.

Would you have any examples of uCrop with capture images?
