### ISSUE TITLE
Saving cropped bitmap takes too long

### ISSUE THREAD

**Issue by blakazulu** [Yalantis/uCrop#169]
first of all let me say that this is a great library!
I only have one question, saving the cropped bitmap takes too long. Is there a way to speed it up?

**Comment by bigggge** [comment]
i have the same problem,but the demo is ok

**Comment by nilskassube** [comment]
This could have many reasons. Can you please submit more details, e.g. image size, device, Android version etc.

**Comment by blakazulu** [comment]
but the example works good on the same device.

**Comment by shliama** [comment]
Hello, thanks for the issue.
You can speed up this issue by attaching sample image files and device info so I can try to reproduce and check performance.

**Comment by TeeRawk** [comment]
outdated
