### ISSUE TITLE
java.io.IOException: cimg::fopen()

### ISSUE THREAD

**Issue by SaryElgmal** [Yalantis/uCrop#170]
When Trying to save the Image i receive this exception
java.io.IOException: cimg::fopen(): Failed to open file '/external/images/media/24' with mode 'wb'
[MainActivity - Copy.txt](https://github.com/Yalantis/uCrop/files/401939/MainActivity.-.Copy.txt)

[Solved]: the error was in my destinationUri

**Comment by royabh1** [comment]
I am having the same issue, could you please tell me what was wrong with your destination uri and how did you solve it?

**Comment by shliama** [comment]
@royabh1 I'd recommend you to check the sample, and compare your URI/path with the sample one.

**Comment by myinnos** [comment]
Same Issues 👎 again and again 💯

**Comment by shliama** [comment]
You may need to ask for read/write external storage permission.

**Comment by myinnos** [comment]
Did that same issue

**Comment by shliama** [comment]
Do you have this problem when using the sample app?

**Comment by myinnos** [comment]
NO

**Comment by myinnos** [comment]
Even in some times its working well! But most of the cases its throwing this error! 👎

**Comment by shliama** [comment]
IOException - either you don't have proper permissions, or file is not
valid (e.g., file is missing at time the library tries to access it or file
format is not png/jpeg).

**Comment by myinnos** [comment]
Permissions is fine! Why because. i tried with other `libs`, its works well. I think so there is a problem in this `lib`. Please check and update.

**Note that its not happening every time. So we cannot tell permission issues here.
And file missing:  It should fail every time if file not valid. But its working some times.**
