### ISSUE TITLE
Bitmap too large to be uploaded into a texture 

### ISSUE THREAD

**Issue by mrhuo** [Yalantis/uCrop#172]
When I take a picture use UCrop to crop, but I get this Warning.

W/OpenGLRenderer: Bitmap too large to be uploaded into a texture (3120x4160, max=4096x4096)

I think the code does not handle the acceleration of the hardware to open the pixel limit

**Comment by bigggge** [comment]
`       <activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:hardwareAccelerated="false"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>`

**Comment by mrhuo** [comment]
> <activity android:name="com.yalantis.ucrop.UCropActivity" android:hardwareAccelerated="false" android:screenOrientation="portrait" android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>

this can't help me, the cropView is blank, no image.

**Comment by mrhuo** [comment]
The screenshot like this:
![screenshot_2016-08-11-14-27-15-302_cn zhiweikeji](https://cloud.githubusercontent.com/assets/7203046/17580260/c83b715a-5fcf-11e6-9450-1222d401a83e.png)

**Comment by mrhuo** [comment]
@bigggge I think you need fix the code...

**Comment by bigggge** [comment]
Sorry,i cant help you. But android:hardwareAccelerated="false" is worked for me .You can see #121

**Comment by mrhuo** [comment]
@bigggge Thank you very much.

**Comment by milan-milojevic** [comment]
The proper solution is to use UCrop.Options setMaxBitmapSize() to make sure the OpenGLRenderer texture pixel limit is not exceeded

**Comment by mrhuo** [comment]
@milan-milojevic  Oh, thank you , I try

**Comment by shliama** [comment]
Please check the latest uCrop version :octocat: 
Now you can choose between:

##### Lightweight general solution 
```groovy
compile 'com.yalantis:ucrop:2.2.0' 
```

##### Get power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
``` groovy
compile 'com.yalantis:ucrop:2.2.0-native'
 ```

**Comment by TeeRawk** [comment]
resolved

**Comment by sharmavishal914** [comment]
Same issue coming for me 

![image](https://user-images.githubusercontent.com/29750055/94965994-1f754600-051a-11eb-9866-4f12769591e9.png)

I am using com.github.yalantis:ucrop:2.2.6
