### ISSUE TITLE
when i use uCrop,can't load other so

### ISSUE THREAD

**Issue by KevinLoveGitHub** [Yalantis/uCrop#174]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by KevinLoveGitHub** [comment]
I have already solved the problem, but I don't know the reason for this problem.
In my gradle.properties in the project root, add the line `android.useDeprecatedNdk=true.`
Add the following block to my `build.gradle` file
`android {
    ...
    defaultConfig {
        ...
        ndk {
            abiFilters "armeabi-v7a"
        }
    }
}`

**Comment by shliama** [comment]
Hm, that's strange and good to know that you've fixed it.
I'd like to know what was the error/other issues. But I think it's something with project building & gradle plugin.
