### ISSUE TITLE
rotate a image and the minScale is not change

### ISSUE THREAD

**Issue by rayboot** [Yalantis/uCrop#175]
I pick a image into cropActivity and rotate 90°.
I found that the image cannot fit the crop rect.Because the minScale is too big.

**Comment by shliama** [comment]
@rayboot thanks for the issue. I've reproduced this behaviour and yes, seems like a bug to me :octocat: 
Fixed this in the latest library version, should be out soon :)

**Comment by shliama** [comment]
Please check the latest uCrop version :octocat: 
Now you can choose between:

##### Lightweight general solution 
```groovy
compile 'com.yalantis:ucrop:2.2.0' 
```

##### Get power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
``` groovy
compile 'com.yalantis:ucrop:2.2.0-native'
 ```
