### ISSUE TITLE
Move the layout to sample *feature*

### ISSUE THREAD

**Issue by lucas34** [Yalantis/uCrop#176]
Hi,

When I include the dependency to your library, it will comes with the build in crop activity and a dependency to android support v7 (10k methods) and okhttp.

My suggestion is,
- Library only contains the crop tools and a interface to access the crop function. (Dependency free)
- Sample contains the crop activity with all the UI features.

Then it's up to everyone to use the same layout as the sample or not. I think in most of the case we do need to customise the layout anyway.

Cheers

**Comment by shliama** [comment]
Hello @lucas34,

I agree with you, and these ideas are on my mind for some time.
However it's all about time, you never have enough of it.

I'll definitely try to decouple library in the future, but cannot give you any ETA yet. :octocat:

**Comment by Peymansadeghzade** [comment]
Peymansadeghzade@gmail.com

**Comment by Peymansadeghzade** [comment]
-- 
P
