### ISSUE TITLE
About load a smaller image.

### ISSUE THREAD

**Issue by zhgrrshjt** [Yalantis/uCrop#177]
Hi,

When I use uCrop load a smaller image which size is 96x64, it doesn't work.
I should sleep a moment before return BitmapWorkerResult.

Cheers

**Comment by nilskassube** [comment]
What do you mean by "does not work"? We had reports from users of our app that on some devices the crop grid is not displayed. But we were not able to reproduce it on our test devices.

**Comment by zhgrrshjt** [comment]
sometimes OverlayView.onlayout invoked after setimagedata.

**Comment by shliama** [comment]
@nilskassube your issue is known and it is fixed and will be available in the new library build soon.

@zhgrrshjt I cannot reproduce any issue with images down to 24x24 pixels, can you give more details, and what do you mean by "I should sleep a moment before return BitmapWorkerResult."?

**Comment by TeeRawk** [comment]
resolved
