### ISSUE TITLE
when take photo  ucrop take a long time to deal with?

### ISSUE THREAD

**Issue by yanglichuan** [Yalantis/uCrop#178]
when take photo  ucrop take a long time to deal with?

how about

**Comment by nilskassube** [comment]
Please submit more details. On my device it does not take a long time.

**Comment by milan-milojevic** [comment]
maybe try setting UCrop.Options setMaxBitmapSize() to 1024/2048/4096 to see if it opens up faster?

**Comment by shliama** [comment]
Hello, thanks for the issue.
You can speed up this issue by attaching sample image files and device info so I can try to reproduce and check performance.

**Comment by Brajendra** [comment]
This is such a  nice library with lots of option, but unfortunately this library take very long time to load image, and try to show progress bar if user hide bottom bar.
