### ISSUE TITLE
  Float precision is too high, it will lead to the calculation is too complex and mobile rebound problem

### ISSUE THREAD

**Issue by swepthong** [Yalantis/uCrop#180]
Such modifications can solve the problem

in  RectUtils.java

    public static RectF trapToRect(float[] array) {
        RectF r = new RectF(Float.POSITIVE_INFINITY, Float.POSITIVE_INFINITY,
                Float.NEGATIVE_INFINITY, Float.NEGATIVE_INFINITY);
        for (int i = 1; i < array.length; i += 2) {
           float x = (float)(Math.round(array[i - 1] * 10))/10;//array[i - _1];
            float y = (float)(Math.round(array[i] * 10))/10;//array[i];
            r.left = (x < r.left) ? x : r.left;
            r.top = (y < r.top) ? y : r.top;
            r.right = (x > r.right) ? x : r.right;
            r.bottom = (y > r.bottom) ? y : r.bottom;
        }
        r.sort();
        return r;
    }

**Comment by swepthong** [comment]
There is a probability of occurrence，  image rebounds   when cropping  it after mobile. 

log displays follow:

 setImageToWrapCropBounds @@@
                                                            currentX: 491.99896,currentY=656.00616,
                                                            mCropRect=RectF(0.0, 0.0, 984.0, 738.0),
                                                            mCurrentImageCorners=[-0.0010356903, 0.006160736, 983.99896, 0.006160736, 983.99896, 1312.0062, -0.0010356903, 1312.0062],mCurrentImageCenter=[491.99896, 656.00616],
                                                            tempCurrentImageCorners=[1.9073486E-6, -287.0, 984.0, -287.0, 984.0, 1025.0, 1.9073486E-6, 1025.0],willImageWrapCropBoundsAfterTranslate=false

**Comment by shliama** [comment]
Hi @swepthong and thanks for the issue.
Yes you are right, I've modified source code and it will be available in the next library build soon.
