### ISSUE TITLE
It's a huge library

### ISSUE THREAD

**Issue by ankitbatra11** [Yalantis/uCrop#181]
It definitely appears better than the other android croppers but the size of this library is too huge to include in an android application. With proguard enabled, including this library in my application is adding 1.7 MB to the total size.

**Comment by MaleWxt** [comment]
yes,alright.i think also!

**Comment by shliama** [comment]
You can use library version 1.+ (I'll publish updates to the current 1.5.0 build) - it's lightweight but cannot handle HD images well because there are no native libraries.
If you need to be able to crop HD images - use 2.+ version then. I don't think 1.7 MB is too much for this feature.

**Comment by shliama** [comment]
Please check the latest uCrop version :octocat: 
Now you can choose between:

##### Lightweight general solution 
```groovy
compile 'com.yalantis:ucrop:2.2.0' 
```

##### Get power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
``` groovy
compile 'com.yalantis:ucrop:2.2.0-native'
 ```
