### ISSUE TITLE
when i use ucrop it shows  a toast "invalid marker " and suddenly the ucrop activity exit ,I want to know how to solve it.

### ISSUE THREAD

**Issue by happysmile123** [Yalantis/uCrop#184]
**java.io IOException  invalid marker**

**i submit the crop result**

**I can see the croped picture in result activity**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any _image files_, _URL_ and `stack trace` that can be used to reproduce the _bug_.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by shliama** [comment]
Hello @happysmile123, thanks for the issue.
I've just fixed this bug, it was related to ExifInterface and PNG files cannot live together.
Should be available in the next library build soon.

**Comment by shliama** [comment]
Please check the latest uCrop version :octocat: 
Now you can choose between:

##### Lightweight general solution 
```groovy
compile 'com.yalantis:ucrop:2.2.0' 
```

##### Get power of the native code to preserve image quality (+ about 1.5 MB to an apk size)
``` groovy
compile 'com.yalantis:ucrop:2.2.0-native'
 ```
