### ISSUE TITLE
How to get the cropped image's position of the original image?

### ISSUE THREAD

**Issue by westlinkin** [Yalantis/uCrop#188]
How can I get the cropped image's position of the original image?

For example, if the original image's size is 100x200, if the user cropped the center, and get a 50x50 image, can I get a `float` array that tells me the position of the cropped area? Like in this example, it is: left: 25, right: 75, top: 75, bottom: 125, if it is in the center.

**Comment by shliama** [comment]
Hello @westlinkin. Currently you cannot get this info from the crop result intent.

But you can fork library and try pass back variables from the `TransformImageView` class:
`mCurrentImageCorners, mCurrentImageCenter, mInitialImageCorners, mInitialImageCenter`.

Don't forget that user can rotate image freely (if you don't disable it).

**Comment by westlinkin** [comment]
Thanks.
