### ISSUE TITLE
Oval Cropping

### ISSUE THREAD

**Issue by sench93** [Yalantis/uCrop#189]
Oval overlaying returns rectangel bitmap. It will be okay if it crop oval part and make reactangle adding transparency to fill the rectangel. But it's just cropping rectangle background. So i want to understand what's the differnece between rectangle overlay and oval overlay when it's anyway cropping rectangle with backgroud. 

original image 

![screenshot_2016-09-05-18-34-46 1](https://cloud.githubusercontent.com/assets/20376013/18251027/63be09bc-738f-11e6-86e7-02b8fbc1d114.png)

with overlay image 

![screenshot_2016-09-05-18-35-26 1](https://cloud.githubusercontent.com/assets/20376013/18251038/74d4021a-738f-11e6-897a-9ecde0635e00.png)

cropped 
![screenshot_2016-09-05-18-35-32 1](https://cloud.githubusercontent.com/assets/20376013/18251048/7ce48eca-738f-11e6-914a-8f7819cc5067.png)

**Comment by shliama** [comment]
I don't see a need in cropping circle/oval out of the bitmap and filling corners with colour/transparency.
If you want to show "circle" image after crop - just use some library aka Fresco or Picasso that can transform any image to circle (showing avatars etc.).

Oval overlay option is just to show user how his "avatar" will look like after crop.

**Comment by ZacharyTech** [comment]
I also have such a demand, because the cut out of the pictures have to do post-processing
