### ISSUE TITLE
UCrop2.0+ version is conflict with IFLYTEK，I have to use 1.5 version.

### ISSUE THREAD

**Issue by Myple** [Yalantis/uCrop#191]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by shliama** [comment]
So, what is the issue? What is IFLYTEK? What errors do you have? How about filling the issue template? :)
