### ISSUE TITLE
CImg<unsigned char>::load(): Failed to recognize format of file 

### ISSUE THREAD

**Issue by olivercm** [Yalantis/uCrop#193]
**Do you want to request a _feature_ or report a _bug_?**
report a bug
**What is the current behavior?**
result code is UCrop.RESULT_ERROR
**What is the expected behavior?**
normal
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
modify file name to '/storage/emulated/0/PictureUnlock_59545_14730639426357.jpg@.pictureunlock.jpg', and select it, crop。The file name has two  '.jpg' 。
**Please attach any _image files_, _URL_ and `stack trace` that can be used to reproduce the _bug_.**
'/storage/emulated/0/PictureUnlock_59545_14730639426357.jpg@.pictureunlock.jpg'

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
2.1.2

**Comment by shliama** [comment]
@olivercm thanks for the issue. I think it's up to you to provide URI with the proper file name to the uCrop. So if you know that it can happen in your app - please modify the filename so it can be recognised by uCrop and native libraries.

**Comment by olivercm** [comment]
@shliama I found this bug not by modifying image uri to test UCrop. I first find it in some mobiles that have pictures in that format. So we not sure whether image in mobiles of consumer will have similiar format or not. Of course, modify image uri to normal can fix the bug. Thanks for your time.

**Comment by LittleKu** [comment]
@olivercm I got the same issue, can you show me how to modifying image uri to normal ? I'm newbie on android

**Comment by olivercm** [comment]
@LittleKu I did the same
