### ISSUE TITLE
Free style crop breaks aspect ratio

### ISSUE THREAD

**Issue by Edijae** [Yalantis/uCrop#195]
Am using the latest version of this library in my app that am building. i had a previous issue(#156) about crop frame not moving around but the issue is solved in the latest version.(great thanks for that)
My new issue is that when i specify `options.setFreeStyleCropEnabled(true);` and set aspect ratio to be `1:1` which is square, the aspect ratio is not maintained. one can still have crop a rectangular piece of image and i want a square one. 
Another thing is that when i set `options.setFreeStyleCropEnabled(false);` the crop frame cannot be moved around. 
- Is there a method that can be used to explicitly enable crop frame to move around when cropping  instead of image(this means disabling image movement and enabling crop frame movement)?
- what can i do to make aspect ratio maintained by crop frame?

![screenshot_2016-09-17-00-01-52](https://cloud.githubusercontent.com/assets/14346659/18601203/2b2c1394-7c6a-11e6-880b-c61e5e295bd7.png)
![screenshot_2016-09-17-00-02-26](https://cloud.githubusercontent.com/assets/14346659/18601213/3648d3ca-7c6a-11e6-8744-8f6c74c8a09c.png)

**Comment by androidapkr** [comment]
I faced same issue, when you use free style crop and then select any ration for example 4:3, then i select any portion its not stay on that ratio, it's become in freely.

**Comment by Legementarion** [comment]
Sorry for being late, this feature will be implement in next release 2.3.0   #405
Thank you for you report :)

**Comment by adiga-maf** [comment]
When you guys expect to go live with release 2.3.0?
