### ISSUE TITLE
declared this activity

### ISSUE THREAD

**Issue by Hitexroid** [Yalantis/uCrop#197]
i have declared UCropActivity 

> ```
>     <activity
>         android:name="com.yalantis.ucrop.sample.ResultActivity"
>         android:screenOrientation="portrait"/>
> ```

```
    <activity
        android:name="com.yalantis.ucrop.UCropActivity"
        android:screenOrientation="portrait"
        android:theme="@style/Theme.AppCompat.Light.NoActionBar"/>
```

but still returns this Error : 

> android.content.ActivityNotFoundException: Unable to find explicit activity class {com.hitex.ucrop/com.yalantis.ucrop.UCropActivity}; have you declared this activity in your AndroidManifest.xml?

**Comment by Cool04ek** [comment]
Is this question is still valid?

**Comment by TeeRawk** [comment]
outdated

**Comment by 2208Abhinav** [comment]
@TeeRawk I am also facing this error. How to slove it?

**Comment by Pablovs97** [comment]
@TeeRawk @2208Abhinav Same error here, you solve it?

**Comment by S1imo** [comment]
@Pablovs97 I had the same error, but I added the UCrop.Options class.

     **UCrop.Options options = new UCrop.Options();**
        UCrop.of(sourceUri, destinationUri)
                .withMaxResultSize(50, 50)
                .withAspectRatio(5f, 5f)
                **.withOptions(options)**
                .start(EditPerfEActivity.this);

**Comment by Ben-Manfouo** [comment]
For those who are facing the same issue with flutter, just delete the .build and the .idea directories at the root project tree and rebuild.

**Comment by MounirSd** [comment]
`flutter clean` worked for me

> For those who are facing the same issue with flutter, just delete the .build and the .idea directories at the root project tree and rebuild.
