### ISSUE TITLE
UCropActivity Customization Sample

### ISSUE THREAD

**Issue by aftabsikander** [Yalantis/uCrop#200]
Hello guys a really awesome library, I was looking for extending your existing UCropActivity to override some of the feature you provide i.e ( I don't want horizontal wheel for rotation would like to allow user to rotate image when pressing rotate button etc.)

Issue is that I am not sure how to extend your activity and override some of these functions It would be great if you include sample in your next release.

**Comment by aftabsikander** [comment]
@shliama Any help here..

**Comment by shliama** [comment]
@aftabsikander hi there.
Things that you've described above assume that you have some android/java development knowledge. Code is open-source and even have java-doc so I don't see any problems for you to just go and look into sources and figure it out yourself.
P.S. I did not create UCropActivity with "extending" it to customize library in mind. However you have plenty of options in UCrop.Builder. If it's not enough - you'd better for the library and customize it to your needs.
