### ISSUE TITLE
Orientation not fixed when 'original' is selected

### ISSUE THREAD

**Issue by achuinard** [Yalantis/uCrop#202]
If I select an image and simply leave the 'Original' option selected in the UCropActivity, the resulting image is not properly rotated. Shouldn't the rotation be fixed no matter what?

**Comment by TeeRawk** [comment]
Hello , @achuinard , so basically u opening ucrop activity, doing no changes and then the image gets rotated ?

**Comment by njovy** [comment]
@TeeRawk I'm having this issue as well. Doing no changes causes this issue.

**Comment by Legementarion** [comment]
@achuinard  , @njovy  Its a very strange things, I cant reproduce your issue, do you use latest version?

**Comment by rock31** [comment]
I'm having the same issue. Doing no changes leads to a portrait image being displayed as landscape image.
