### ISSUE TITLE
can't select photo for the Xiaomi note moblie

### ISSUE THREAD

**Issue by aaironman** [Yalantis/uCrop#203]
My mobile is XiaoMi Note,and can't select the photo in sdcard,show the warn load failed
the same problem for the demo version 2.2.0

**Comment by Cool04ek** [comment]
Can you please provide logs of the error?

**Comment by 401885064** [comment]
你可以看下我提交的这个 ，也行有用

https://github.com/Yalantis/uCrop/pull/192

**Comment by Cool04ek** [comment]
Is your PR #192 still actual? Not quite sure if you  are going to make changes I was asking about?

**Comment by TeeRawk** [comment]
outdated
