### ISSUE TITLE
[Feature Request] Empty Toolbar Title

### ISSUE THREAD

**Issue by vanniktech** [Yalantis/uCrop#208]
**Do you want to request a _feature_ or report a _bug_?**
Feature

**What is the current behavior?**
The toolbar title can not be unset.
calling setToolbarTitle() with `null` or `""` won't work since it is [checked for emptiness](https://github.com/Yalantis/uCrop/blob/4fd0876650f903bcd53330ae9edd5a8daf66cf96/ucrop/src/main/java/com/yalantis/ucrop/UCropActivity.java#L272)

**What is the wanted behavior?**
The toolbar title can be unset.
calling setToolbarTitle() with `null` or `""` won't display a title.

Happy to provide a PR for this one.

**Comment by Cool04ek** [comment]
@vanniktech we will be glad to receive PR from you. I think empty string would be enough. 
Thanks
