### ISSUE TITLE
[Feature Request] Customize Cross Drawable - R.drawable.ucrop_ic_cross

### ISSUE THREAD

**Issue by vanniktech** [Yalantis/uCrop#209]
**Do you want to request a _feature_ or report a _bug_?**
Feature Request

**What is the current behavior?**
There is no way of [changing the Cross Drawable in the upper right corner](https://github.com/Yalantis/uCrop/blob/4fd0876650f903bcd53330ae9edd5a8daf66cf96/ucrop/src/main/java/com/yalantis/ucrop/UCropActivity.java#L318).

**What is the expected behavior?**
Be able to change it via the Options API.

Happy to provide a PR for this one.

**Comment by Cool04ek** [comment]
@vanniktech we will be glad to receive PR from you. Thanks.
