### ISSUE TITLE
[Feature Request] Customize Done Drawable - R.drawable.ucrop_ic_done

### ISSUE THREAD

**Issue by vanniktech** [Yalantis/uCrop#210]
**Do you want to request a _feature_ or report a _bug_?**
Feature Request

**What is the current behavior?**
There is no way of [changing the Done Drawable in the upper right corner](https://github.com/Yalantis/uCrop/blob/4fd0876650f903bcd53330ae9edd5a8daf66cf96/ucrop/src/main/res/menu/ucrop_menu_activity.xml#L7).

**What is the expected behavior?**
Be able to change it via the Options API.

Happy to provide a PR for this one.

**Comment by Cool04ek** [comment]
@vanniktech We will be glad to receive PR from you. Thanks.
