### ISSUE TITLE
[Feature Request] Customize background color of the root View

### ISSUE THREAD

**Issue by vanniktech** [Yalantis/uCrop#211]
**Do you want to request a _feature_ or report a _bug_?**
Feature Request

**What is the current behavior?**
There is no way of [changing the background color of the root view](https://github.com/Yalantis/uCrop/blob/4fd0876650f903bcd53330ae9edd5a8daf66cf96/ucrop/src/main/res/layout/ucrop_activity_photobox.xml#L33).

**What is the expected behavior?**
Be able to change it via the Options API.

Happy to provide a PR for this one.

**Comment by Cool04ek** [comment]
@vanniktech WE are happy to receive PR from you. Thanks.

**Comment by Cool04ek** [comment]
@vanniktech Thank you very much for all requests you have provided
