### ISSUE TITLE
SecurityException in Version 2.2.0 when trying to display the image from the Gallery

### ISSUE THREAD

**Issue by vanniktech** [Yalantis/uCrop#212]
**Do you want to request a _feature_ or report a _bug_?**
Bug

**What is the current behavior?**
When selecting a picture from the Gallery and opening it with uCrop, via the returned Uri from the onActivityResult intent, the app will crash:

> Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=14071, uid=10350 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

**What is the expected behavior?**
To not crash and nonetheless display the chosen picture as it was done in version `1.5.0` of the library.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Let the user choose a picture from the gallery
2. Take the `Uri` from the onActivityResult callback and open uCrop with it
3. App will crash

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
Android versions affected: >= Marshmallow
Version 2.2.0 of uCrop is affected.

**Comment by Cool04ek** [comment]
@vanniktech Thank you for noticing this stuff. Basically, lib should not request for permissions - app should do it. But library should not crash as well. So we will provide fix. In case there is no permission lib will return result failed.

**Comment by vanniktech** [comment]
In my opinion the library should still work nonetheless as it did in version 1.5.0. Why would it return a failed result now?

**Comment by Cool04ek** [comment]
Because in new versions of Android, application needs to request permissions. Previously, app just need to put it in the Android Manifest. So it's up to app behaviour how permissions are requested - at the beginning, during the process of usage, etc.

**Comment by Cool04ek** [comment]
If user denies permission - non app or lib can fetch image.

**Comment by vanniktech** [comment]
I tried it with version 1.5.0 and somehow it was able to get the image from the camera. I was using the same device, same app and also on both external storage permissions were denied

**Comment by Cool04ek** [comment]
Because version 1.5.0 has targetSDK lower than 23. In this case all permission are granted by default. For SDK >= 23 it should be requested.

**Comment by vanniktech** [comment]
Ah okay now I understand it, thanks for the clarification

**Comment by Cool04ek** [comment]
Your welcome. I will add milestone for the fix later. Thanks.

**Comment by aftabsikander** [comment]
+ 1 Feature, We have also faced this issue. Currently what we did was that we ask user for permission before hand and if permission is not available then we dont allow user to processed for crop feature.

**Comment by dejandobnikar** [comment]
I also noticed this issue.

@Cool04ek I have to disagree that library's targetSDK version is the reason for this. Permission system behaviour is determined by targetSDK version defined in your app.  

I dived into the implementation and found out the reason why `1.5.0` works and `2.2.0` does not. While `1.5.0`'s `BitmapLoadTask` only loads the bitmap from uri, in `2.2.0` there is `processInputUri()` which causes an exception (actually thrown in `FileUtils.getPath`). Reason for this is missing permission.

While I completely agree that app should handle permissions, not the library, I believe that the library should check permission and fallback to `1.5.0` behaviour.

**WHY?**  
Well, there is a way not to bother user with permissions: If image is picked from the gallery, temporary permission to access an image is granted. Cropping destination can be set to the path returned from `Context.getExternalFilesDir()`, which, starting with KITKAT, does not need external storage permission. 

Thoughts?

**Comment by Cool04ek** [comment]
@dejandobnikar You are right about BitmapLoadTask - that is what I ws talking about. But there is no sense in changing Sample app - it's just sample¯\_(ツ)_/¯
I have check your request and commented on it as well. Thank you.

**Comment by dejandobnikar** [comment]
@Cool04ek I agree, but Sample app was modified to show an example how to simplify things around permissions.

Sample app is now reverted.

**Comment by Cool04ek** [comment]
Fixed with #227
