### ISSUE TITLE
Original image gets zoomed in when clicked back.

### ISSUE THREAD

**Issue by sujeshshetty** [Yalantis/uCrop#217]
When I go into the Photobox/Image Crop screen, without any defined aspect ratio, Original radio button gets checked at the bottom and the Photobox displays the complete image without zoom, but in the same screen, If I select 1:1 aspect ratio [or any other radio option]  and click the Original (aspect ratio) radio button back again, the image is in a zoomed in state[the zoom which occurred when I clicked on 1:1 aspect ratio]., User has to again zoom out, to get back the original image.

Is there any way to reset the image to original zoomed out state, when original is clicked back ?

**Comment by Legementarion** [comment]
Not actual anymore, use last version of ucrop with ucropFragment
