### ISSUE TITLE
Appcompat lib no necessary

### ISSUE THREAD

**Issue by start141** [Yalantis/uCrop#22]
Thanks for a nice library!

uCrop extend AppCompatActivity, I think it is no necessary.
Can you use custom layout instead ActionBar and remove the appcompat lib? It will let the library smaller.
If you agree, I will pull a request.

Thanks again!

**Comment by shliama** [comment]
Are there any apps that do not use appcompat lib? Well - they should :)
What about appcompat theme?

**Comment by start141** [comment]
Some apps use holo/material theme.

**Comment by timkoers** [comment]
@start141 The AppCompat Lib makes sure that the result of various methods is exactly the same on all of the Android API platforms. Without this lib, coding an library that looks the same on every api version is very hard.
