### ISSUE TITLE
Does this library support Fragment ? because I have problem when I try to handle Callback in my onActivityResult 

### ISSUE THREAD

**Issue by amineghabi** [Yalantis/uCrop#222]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by Cool04ek** [comment]
No. Only Activity.

**Comment by amineghabi** [comment]
So You should indicate this my friend , Thanks :)

**Comment by Cool04ek** [comment]
If I understood your question right, you want to start fragment instead of activity when using uCrop. We have description in README.md how to use uCrop. And you can only start Activity. If you want start Fragment instead (i don't understand why you would need it) you can fork and implement it.

**Comment by amineghabi** [comment]
yes my friend I need to start uCrop from Fragment so can I use it or not ?

**Comment by Cool04ek** [comment]
You can start uCrop FROM Fragment. There is no difference where you start it. It will open new Activity any way. And you need to handle result in onActivityResult()

**Comment by HughJeffner** [comment]
I think the problem is `onActivityResult` is not getting called in the Fragment after the crop operation

**Comment by ravuthlong** [comment]
Adding on to the original question, the onActivityResult does get called, but it is called on the activity which holds the fragment.
