### ISSUE TITLE
Using the lightweight Ucrop when importing it as a module.

### ISSUE THREAD

**Issue by sujeshshetty** [Yalantis/uCrop#228]
**Do you want to request a *feature* or report a *bug*?**
Feature.

I want to use the lightweight general solution of Ucrop since my client want the Apk size to be less, 

I know that I need to include
compile 'com.yalantis:ucrop:2.2.0' - lightweight general solution
instead of
compile 'com.yalantis:ucrop:2.2.0-native(+ about 1.5 MB to an apk size)

but I'm using the library in my project as a module [Since I wanted to customize the library according to my needs] and not as a Gradle , so I always get the library with the native one. Is there a way I can use the lightweight general solution if I import it as a module?

**Comment by Cool04ek** [comment]
Hi! Yes, you need to fetch branch https://github.com/Yalantis/uCrop/tree/feature/non_native

**Comment by sujeshshetty** [comment]
Thanks for the info ! Totally missed it!
