### ISSUE TITLE
For better User Experience.

### ISSUE THREAD

**Issue by start141** [Yalantis/uCrop#23]
Sorry for my poor English!

Defect:
1. In the crop activity, selected the rotate button(middle of bottom bar), the image can't scale, 
if I want to resize the image I must to select the scale button(left of bottom bar) first, operation is not convenient. 
2. In the crop activity, selected the ratio button(right of bottom bar), when I resizing the image size, the rotate will change, it is reallyuncomfortable.

My solution:
1. When selected the rotate button(middle of bottom bar), we should make it scalable.
2. When selected the ratio button(right of bottom bar), we should make it keep ratio.

If you agree, I will pull a request soon.

Thanks!

**Comment by shliama** [comment]
It's not a defect - it's how it works by design :)

**Comment by start141** [comment]
Oh!
Maybe add options to custom tab(scale, rotate, ratio)'s gestures behaviour(enabled simultaneously).

**Comment by shliama** [comment]
Yeah, that is good idea.

**Comment by Rainer-Lang** [comment]
gestures would be cool

**Comment by shliama** [comment]
Please check 1.2.2
UCrop.Options #setAllowedGestures() method.

**Comment by start141** [comment]
Very nick!
