### ISSUE TITLE
Image compression doesn't work with Fragment

### ISSUE THREAD

**Issue by ankurt-optimus** [Yalantis/uCrop#230]
```
   public void start(@NonNull Context context, @NonNull android.support.v4.app.Fragment fragment) {
        start(context, fragment, REQUEST_CROP);
    }
```

Image compression doesn't seem to work when i use this method to use Ucrop in a fragment

**Comment by windzie** [comment]
I found this same problem

**Comment by p1nkydev** [comment]
@ankurt-optimus Hello! In version 2.2.2 we have added uCrop fragment. That should help.
