### ISSUE TITLE
Remove READ_EXTERNAL_STORAGE Requirement

### ISSUE THREAD

**Issue by forrestbice** [Yalantis/uCrop#237]
As mentioned at the end of the discussion on [this issue](https://github.com/Yalantis/uCrop/issues/135#issuecomment-229000948), [`READ_EXTERNAL_STORAGE`](https://developer.android.com/reference/android/Manifest.permission.html#READ_EXTERNAL_STORAGE) is not a requirement of Android but of UCrop. [Line 109 of FileUtils](https://github.com/Yalantis/uCrop/blob/4fd0876650f903bcd53330ae9edd5a8daf66cf96/ucrop/src/main/java/com/yalantis/ucrop/util/FileUtils.java#L109) raises the issue

For reference and examples see [this answer](http://stackoverflow.com/a/37166704/1406986) which leads to [this Big Android BBQ talk](https://www.youtube.com/watch?v=C28pvd2plBA) with [slides available here](https://speakerdeck.com/ianhanniballake/forget-the-storage-permission-alternatives-for-sharing-and-collaborating?slide=28)

Being able to use Ucrop without the `READ_EXTERNAL_STORAGE` permission would be greatly appreciated by developers and users

**Comment by Cool04ek** [comment]
Hi. As far as I understand your question relates to this issue #212. Please, check it out.

**Comment by forrestbice** [comment]
@Cool04ek #212 is related however removing the permission should still be doable
