### ISSUE TITLE
小米 红米 note3 改变裁剪比例后抛异常：ExifInterface only supports saving attributes on JPEG formats

### ISSUE THREAD

**Issue by siongu** [Yalantis/uCrop#241]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by Cool04ek** [comment]
Sorry, I don't understand your question
