### ISSUE TITLE
Get X, Y, Width, Height, Angle of cropped image?

### ISSUE THREAD

**Issue by DmitriiSemeniuc** [Yalantis/uCrop#243]
On callBack method onBitmapCropped() I receive parameters: uri, width, height. How can I get also X, Y and rotate angle?

**Comment by Cool04ek** [comment]
Hi. For now, lib doesn't provide this functionality. You can either fork it and provide a PR or simply add lib as a module and change it in the code.

**Comment by vanniktech** [comment]
Some of the things I added - #219

**Comment by DmitriiSemeniuc** [comment]
Thank you for the answer
