### ISSUE TITLE
it will not save new image to File destination when rotate only 

### ISSUE THREAD

**Issue by liminghuanghengtian** [Yalantis/uCrop#246]
**Do you want to request a *feature* or report a *bug*?**
report a bug
**What is the current behavior?**
i find that it will not save rotated image to the destination File while just rotating with the aspect-ratio of the original image, without crop. the destination File  is not rotated image but original image
**What is the expected behavior?**
it can save my rotated image with the aspect-ratio of the original image
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
curVersion: 2.2.0

**Comment by markocausevic** [comment]
Hi, I'm also facing the same issue in my project. Would love to see this bug fixed, please :)

**Comment by DmitriiSemeniuc** [comment]
Hi @liminghuanghengtian, the input and output file paths should be different. Please try this: 
...
mGestureCropImageView.setImageUri(inputImageUri, outputImageUri);
...

**Comment by TeeRawk** [comment]
Hello @liminghuanghengtian  please confirm, if @DmitriiSemeniuc answer was helpful to you.

**Comment by wanjijul** [comment]
Same problem here:

Solve it by using a simple trick so that "Should crop" will always return true.

set:
.withMaxResultSize(getInputImageWidth - 1, getInputImageHeight - 1)
