### ISSUE TITLE
Set minimum image width/height

### ISSUE THREAD

**Issue by tree1224** [Yalantis/uCrop#247]
**Do you want to request a *feature* or report a *bug*?**
New api request to set result minimum width/height
the api would be fine if looks like withMaxResultSize(maxWidth, maxHeight).

**What is the current behavior?**
Can not set a limit for minimum width/height.

**What is the expected behavior?**
I would like to use uCrop in my photo editor/printer app, I would like to set a minimum width/height for result photo to have enough pixel for print.
user should make sure select image is large than minimum width/height before start crop if this minimum width/height was set.

I noticed there is a exist issue 122 report same requirement, but it was closed and I did not find a conclusion for this issue.
https://github.com/Yalantis/uCrop/issues/122

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by Legementarion** [comment]
@tree1224 Hello! I know it a little bit bad, but you can get image after crop, convert to bitmap, check it size and show warning or alert to user if something wrong. 

If you are dont agree, you can contribute this functional to our library, I will glad to accept your pull request. Thank you for issue :)

**Comment by hirengavit** [comment]
After crop we can get bitmap using Uri in onActivityResult like below
` final Uri resultUri = UCrop.getOutput(data);`

get bitmap from Uri and Check if it is of required size 

If not we can simply convert bitmap to required size in onActivityResult.

`Bitmap resizedBitmap = Bitmap.createScaledBitmap(originalbitmap, minWidth, minHeight, false);`
