### ISSUE TITLE
AnimatedVectorDrawable not working on Pre-L Versions

### ISSUE THREAD

**Issue by androidapkr** [Yalantis/uCrop#248]
E/dalvikvm: Could not find class 'android.graphics.drawable.AnimatedVectorDrawable', referenced from method android.support.graphics.drawable.AnimatedVectorDrawableCompat.isRunning

E/dalvikvm: Could not find class 'android.graphics.drawable.AnimatedVectorDrawable', referenced from method android.support.graphics.drawable.AnimatedVectorDrawableCompat.start

E/dalvikvm: Could not find class 'android.graphics.drawable.AnimatedVectorDrawable', referenced from method android.support.graphics.drawable.AnimatedVectorDrawableCompat.stop

**Comment by TeeRawk** [comment]
Hello, @androidapkr  , can you provide steps or some code fragment to reproduce this ?

**Comment by Legementarion** [comment]
unclear
