### ISSUE TITLE
Cropper doesn't move smooth after setFreeStyleCropEnabled(true).

### ISSUE THREAD

**Issue by UmairZameer** [Yalantis/uCrop#249]
After setFreeStyleCropEnabled property gets true, the cropper doesn't move smoothly. 
Is there any solution to make cropper move smooth like Android-Image-Cropper library does.

**Comment by TeeRawk** [comment]
Hello, @UmairZameer , can you provide list of devises that have not smooth movement ?

**Comment by Legementarion** [comment]
Unclear. Please check out last version, api was a little bit changed and everything work fine
