### ISSUE TITLE
How to mask OvalDimmedLayer antialias?

### ISSUE THREAD

**Issue by start141** [Yalantis/uCrop#25]
When using `canvas.clipPath` to draw oval dimmed layer, the oval should not antialias.

Like this img
![qq20160204-0 2x](https://cloud.githubusercontent.com/assets/6055764/12810547/d9f08dac-cb61-11e5-8546-a8ea4e679bfb.jpg)

If change to use `Xfermode` with the paint, it should be like this
![qq20160204-1 2x](https://cloud.githubusercontent.com/assets/6055764/12810556/e60c6d22-cb61-11e5-9fd0-9f8343e677e2.jpg)

The code line would
```java
    private static final int PAINT_FLAGS = Paint.DITHER_FLAG | Paint.FILTER_BITMAP_FLAG |
            Paint.ANTI_ALIAS_FLAG;
    private static final Paint MASK_BITMAP_PAINT;

    static {
        MASK_BITMAP_PAINT = new Paint(PAINT_FLAGS);
        MASK_BITMAP_PAINT.setXfermode(new PorterDuffXfermode(PorterDuff.Mode.DST_OUT));
    }

    ...

    Bitmap result = Bitmap.createBitmap(canvas.getWidth(), canvas.getHeight(), Bitmap.Config.ARGB_8888);

    Canvas ovalDimmedCanvas = new Canvas(result);
    ovalDimmedCanvas.drawColor(mDimmedColor);
    ovalDimmedCanvas.drawOval(mCropViewRect, MASK_BITMAP_PAINT);

    canvas.drawBitmap(result, 0, 0, new Paint(PAINT_FLAGS));
```

But, create bitmap drawing may a way which not good enough.

So, anybody know how to use `Xfermode` without create bitmap?

Thanks!

**Comment by shliama** [comment]
I've added fix in version 1.2.3.
The easiest & performance-safe way to fix that is to draw 1px line along the oval with the same color.
