### ISSUE TITLE
SecurityException

### ISSUE THREAD

**Issue by tvaamorim** [Yalantis/uCrop#250]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Receiving a lot of bug reports on Crashlytics
99% of the cases happened in Android > 6.0
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
`Caused by java.lang.SecurityException
android.os.Parcel.readException (Parcel.java:1620)
android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:183)
android.database.DatabaseUtils.readExceptionFromParcel (DatabaseUtils.java:135)
android.content.ContentProviderProxy.query (ContentProviderNative.java:421)
android.content.ContentResolver.query (ContentResolver.java:502)
android.content.ContentResolver.query (ContentResolver.java:445)
com.yalantis.ucrop.util.FileUtils.getDataColumn (FileUtils.java:109)
com.yalantis.ucrop.util.FileUtils.getPath (FileUtils.java:183)
com.yalantis.ucrop.task.BitmapLoadTask.processInputUri (BitmapLoadTask.java:171)
com.yalantis.ucrop.task.BitmapLoadTask.doInBackground (BitmapLoadTask.java:90)
com.yalantis.ucrop.task.BitmapLoadTask.doInBackground (BitmapLoadTask.java:41)
android.os.AsyncTask$2.call (AsyncTask.java:295)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:234)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
java.lang.Thread.run (Thread.java:818)`

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
I started after updating from  1.5 to 2.2.0
Now Using the version 2.2.0 (no native)

**Comment by TeeRawk** [comment]
Hello, @tvaamorim , can you please provide code fragment, so I can reproduce this issue?

**Comment by Legementarion** [comment]
fixed at last version 2.2.2
