### ISSUE TITLE
Influence the cancel button behavior in the UCropActivity

### ISSUE THREAD

**Issue by speedy2day** [Yalantis/uCrop#256]
I'm using the Yalantis library "UCrop" (v2.2.0) in my android app to crop, scale and rotate images coming from the built-in smartphone camera. When I call uCrop.start(this) the UCropActivity launches and in the upper left corner the cancel button appears as a little cross. 

Now when I press the cancel button, the app crashes with the following Exception:

    FATAL EXCEPTION: main Process: com.myapp.myappname, PID: 25034
    java.lang.RuntimeException: Unable to start activity
    ComponentInfo{com.myapp.myappname/com.myapp.myappname.myActivity}:
    java.lang.NullPointerException: Attempt to invoke virtual method
    'int java.lang.String.length()' on a null object reference

When I press the softkey-back-button I return savely to myActivity. 

Now the question is, how can I influence the behavior of the cancel button so that it either behaves like the back button or restarts myActivity in a way that doesn't cause an exception?

In the SampleActivity from the ucrop sample-project the cancel button behaves as I would expect.

**Comment by speedy2day** [comment]
I found a way to fix this issue I see with my app:

adding a `return true;`after the line `onBackPressed();` in the `onOptionsItemSelected(...)` method inside `UCropActivity` class will do the trick for me. 

Don't ask me why it would behave different when I press the softkey _back_ button.

You might want to include this fix in future versions.

**Comment by speedy2day** [comment]
I guess i better leave this issue open...

According to the android documentation 
https://developer.android.com/reference/android/app/Activity.html#onOptionsItemSelected%28android.view.MenuItem%29
`true` should be returned when the option was processed.

**Comment by TeeRawk** [comment]
Hello @speedy2day  can you please share the full stacktrace of exception ?

**Comment by speedy2day** [comment]
Hey @TeeRawk: Meanwhile I figured out, why my app was throwing. I had not set some bundle data. Thank you for offering your help.

In order to fulfill the android documentation I still believe one should return `true` when the item was consumed. c.f. pull request #257
