### ISSUE TITLE
how to  mirror the picture

### ISSUE THREAD

**Issue by zhangqiyang** [Yalantis/uCrop#26]

**Comment by CeccoCQ** [comment]
You can rotate it manually.

**Comment by zhangqiyang** [comment]
Just rotating  can‘t get mirror effect

**Comment by CeccoCQ** [comment]
You're right -.-

Then, you can mirror the image before to use the uCrop library via Bitmap. I think that this library doesn't provide this feature, because works only to crop and resize image.

**Comment by shliama** [comment]
Currently uCrop doesn't have "mirror" feature.

**Comment by zhangqiyang** [comment]
ok
