### ISSUE TITLE
Download not working in android nougat

### ISSUE THREAD

**Issue by sjenasears** [Yalantis/uCrop#263]
Getting image exposed beyond app through intent.getdata() error

**Comment by TeeRawk** [comment]
Hello, @sjenasears . If you try to open photo from a gallery app for example it shows you an error, is this correct ?

**Comment by KucherenkoIhor** [comment]
Hello, @sjenasears I think we need to update our project and use [FileProvider](https://developer.android.com/reference/android/support/v4/content/FileProvider.html) to prevent this crash. Could you provide logs?
