### ISSUE TITLE
Where is "setToolbarCropDrawable" method?

### ISSUE THREAD

**Issue by wonsuc** [Yalantis/uCrop#269]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
cannot find "setToolbarCropDrawable" method

**What is the expected behavior?**
change "Toolbar icons"

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
2.2.0
2.2.0-native

I want to change toolbar buttons. But I can't find "setToolbarCropDrawable" method in "UCrop.java" class. I even tried 2.2.0-native but still doesn't exist.

Is there any alternative way to change icon drawable of toolbar buttons?

**Comment by TeeRawk** [comment]
Hello, @wonsuc , there is no such method in this library. It  may be available in future versions.

**Comment by wonsuc** [comment]
Then what is this method for?
https://github.com/Yalantis/uCrop/blob/master/ucrop/src/main/java/com/yalantis/ucrop/UCrop.java#L451-L456

**Comment by KucherenkoIhor** [comment]
@wonsuc , Hi
you can see progress bar in right side of toolbar during cropping. If I understood right you would can use this method to replace progress bar with your drawable.

**Comment by wonsuc** [comment]
@KucherenkoIhor I mean if I use uCrop library with gradle, there is no such functions(2.2.0, 2.2.0-native both) So I just cloned 2.2.0-native's master branch and there is the function. I dunno why I can't use this function in gradle version's library file.

**Comment by Legementarion** [comment]
@wonsuc Hi, it happened because github ucrop source code has this fix, but it wasnt build as release version. Now it works fine. I think i can close the issue.
