### ISSUE TITLE
Decoding image in ui thread

### ISSUE THREAD

**Issue by dmytrodanylyk** [Yalantis/uCrop#27]
Hi, thanks for great library.

When I am using `setImageUri` it decode image in `UI` thread. Why you decided to make image decoding in `UI` thread?

[UCropActivity.java](https://github.com/Yalantis/uCrop/blob/master/ucrop%2Fsrc%2Fmain%2Fjava%2Fcom%2Fyalantis%2Fucrop%2FUCropActivity.java#L128)

**Comment by franciscofranco** [comment]
Good question.

**Comment by shliama** [comment]
@dmytrodanylyk Yep, I think I was focused more on other features and have not paid attention on that part. It's definitely will be fixed in the next update.

**Comment by shliama** [comment]
Fixed in 1.3.0
