### ISSUE TITLE
in UCropActivity , when i crop small image,  the background is black. i want set white , what should i do?

### ISSUE THREAD

**Issue by xlc1540697096** [Yalantis/uCrop#272]

**Comment by xlc1540697096** [comment]
And background have a uCrop app logo , i want to hide ,what should i do ?help me ,please.

**Comment by xlc1540697096** [comment]
I choose a samll image ,and crop it .The result image background is black.  Like this
[photo](http://ww3.sinaimg.cn/large/0060lm7Tgy1fdy3gd83mgj30dq0muq46.jpg)

**Comment by xlc1540697096** [comment]
Maybe I find some solutions.Remember to use PNG,not jpg.

**Comment by KucherenkoIhor** [comment]
xlc1540697096, Hi
* png-24 supports different levels of transparency. Each pixel can have an opacity between 0 and 255, with 0 as completely transparent.
* jpg does not support transparency.
I think, it's the reason of problem.
