### ISSUE TITLE
cropCImg work slowly

### ISSUE THREAD

**Issue by JinJieGu** [Yalantis/uCrop#276]
I find cropCImg(...) work slowly,Is compress make it slowly? could i cancel compress it?

**Comment by KucherenkoIhor** [comment]
@PigFlyy, Hi
uCrop isn't able to cancel compress now. But we will try to implement it. 
Thank you for pointing this out.

**Comment by EveryIsNormal** [comment]
I have the same problem , the picture size is about 4 MB , and i found cropCimg will waste a lot of time .  there has another way to solve the problem . thank you.

**Comment by PigFlyy** [comment]
@EveryIsNormal My way is compress it firstly,then crop, what about you ?

**Comment by Legementarion** [comment]
cropCImg this is function of external open source lib - cimg, and they know about problem of slow work, so i hope update of this lib will fix it

**Comment by myth2loki** [comment]
I used the latest version of uCrop, but I got so slow progressing

**Comment by logcatemail** [comment]
uCrop.withMaxResultSize(300, 300);   set MaxResultSize,you can do it
