### ISSUE TITLE
How to stop Image comression when using camera 

### ISSUE THREAD

**Issue by mehul0** [Yalantis/uCrop#279]
**When i'm using camera the result image is so blur in Crope**

**Also final image is blur**

**i'm also remoed ImageComressionFormat & ImageCompressionQuality but the result is same**

**also tried options.setCompressionFormat(Bitmap.CompressFormat.JPEG);
And option.setCompressionQuality(100)**

**i;m using latest vesion of uCrop And Android API Version of 25**

**Comment by ThathaPavanNagaraju** [comment]
same issue @mehul0 did you figured it out to make image clear ??

**Comment by Legementarion** [comment]
@ThathaPavanNagaraju Hi! show your code, please. If camera returned blur image its not ucrop problem
