### ISSUE TITLE
Preload low quality, then load full image

### ISSUE THREAD

**Issue by rafaelekol** [Yalantis/uCrop#28]
Can we preload low quality image(thumbnail) first, and then when full image available replace it with full image. Such behaviour has IOS crop library RSKImageCropper.

**Comment by shliama** [comment]
Sorry but I don't think I understand you feature request. Can you give more info?

**Comment by rafaelekol** [comment]
We have image web search in our app. Which provides thumbnail and original image. We want for our user to click on the thumbnail in  image websearch, then we will open your uCrop and show firstly thumbnail while we will download original in background, when original is ready we will switch it with thumbnail. 
Why we need this? Because this will speedup responsiveness of app. This way transition to your crop screen will be faster.

**Comment by shliama** [comment]
Well, I think you should fork the library and change it yourself in order to get what you want. I don't think we'll implement such feature soon.
