### ISSUE TITLE
Can't change status bar color due to Theme.AppCompat.Light.NoActionBar

### ISSUE THREAD

**Issue by Pintu1909** [Yalantis/uCrop#281]
When I am using style Theme.AppCompat.Light.NoActionBar for this Library project can't change status bar color

Programmatically and not to add  status bar color in Xml File..

**Comment by gouravd** [comment]
UCrop.Options options = new UCrop.Options();
options.setToolbarColor(ContextCompat.getColor(context, R.color.black));
options.setStatusBarColor(ContextCompat.getColor(context, R.color.black));

UCrop.of(fileUri, destUri)
                .withAspectRatio(1, 1)
                .withMaxResultSize(cropsize, cropsize)
                .withOptions(options)
                .start(context, this);

**Comment by brije111** [comment]
further if you want to change color of active Rotate or Zoom button:-
options.setActiveWidgetColor(ContextCompat.getColor(this,R.color.colorAccent));
