### ISSUE TITLE
i got an Exception while crop image from camera on android N

### ISSUE THREAD

**Issue by chandanitnou** [Yalantis/uCrop#282]
Hello uCrop team i got the Exception bellow:

D/BitmapWorkerTask: copyFile
E/BitmapWorkerTask: Copying failed
java.io.FileNotFoundException: /

please fix it 
thanks.

**Comment by mengxn** [comment]
you just try this
`UCrop.of(inputUri, outputUri)
                            .withAspectRatio(1, 1)
                            .withMaxResultSize(100, 100)
                            .start(getActivity());`
and
`outputUri = Uri.fromFile(file)`

**Comment by Salmancs43** [comment]
Hi did you find this solution?

**Comment by rostopira** [comment]
Suggesting to add little hack to the library: https://stackoverflow.com/a/42437379/5593959

```
if(Build.VERSION.SDK_INT>=24){
   try{
      Method m = StrictMode.class.getMethod("disableDeathOnFileUriExposure");
      m.invoke(null);
   }catch(Exception e){
      e.printStackTrace();
   }
}
```

**Comment by Legementarion** [comment]
fixed at last release
