### ISSUE TITLE
OutOfMemoryError When I click again and again

### ISSUE THREAD

**Issue by XiaoQiWen** [Yalantis/uCrop#283]
Memory is not released in time，
When I repeat a click on a picture and then return to happen

**Comment by XiaoQiWen** [comment]
![image](https://cloud.githubusercontent.com/assets/26621530/24830749/9c13457e-1cbe-11e7-8eea-af41eef3c87a.png)

**Comment by XiaoQiWen** [comment]
I tried to modify and avoid memory overflow
```
TransformImageView

private Bitmap mbitmap;
@Override
public void setImageBitmap(final Bitmap bitmap) {
        mbitmap = bitmap;
        setImageDrawable(new FastBitmapDrawable(mbitmap));
}
@Override
    protected void onDetachedFromWindow() {
        super.onDetachedFromWindow();
        if (mbitmap!=null || !mbitmap.isRecycled()){
            mbitmap.recycle();
        }
    }
```
This frees up memory

Or you have other ways to solve this problem

**Comment by XiaoQiWen** [comment]
After this change I found a new problem

I chose an invalid photo or a non-existent photo The program will crash
```
I/Process: Sending signal. PID: 15658 SIG: 9
```
I think it is jni reasons

**Comment by Legementarion** [comment]
@XiaoQiWen Hello! did you try last version? problem still reproduced?

**Comment by Legementarion** [comment]
unclear
