### ISSUE TITLE
Smaller crop height

### ISSUE THREAD

**Issue by JcmeLs** [Yalantis/uCrop#290]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
Want to adjust the minimum cutting height.
**What is the expected behavior?**
Smaller cutting height.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I need smaller cutting height.
![image](https://cloud.githubusercontent.com/assets/12932339/25376298/3504d1a2-29d6-11e7-9029-24a4089e4170.png)

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
com.github.yalantis:ucrop:2.2.1

Thank you very much for writing Ucrop. I would like to ask how to adjust the minimum cutting height. I noticed that the minimum height is now three grids.

**Comment by cillyk** [comment]
how did you achieve this

**Comment by pleasehelpalex** [comment]
I also really need this!
