### ISSUE TITLE
Rotate doesn't work on square images

### ISSUE THREAD

**Issue by ISCHI** [Yalantis/uCrop#294]
If the image has the same height and width and you do nothing except rotate the image by 90°, the rotation is not saved.
I found the problem in BitmapCropTask.java - there is only a "shouldCrop" check. This checks only if crop is needed (by height/width). 
 
` private boolean crop(float resizeScale) throws IOException {
        ...
        if (shouldCrop ) {
            ....`

Maybe the a simple check if rotation needed helps
` private boolean crop(float resizeScale) throws IOException {
        ...
        if (shouldCrop  || mCurrentAngle != 0 ) {
            ....`

see pull request: https://github.com/Yalantis/uCrop/pull/295

**Comment by Legementarion** [comment]
@ISCHI Hello! I checked your case in last ucrop version (2.2.2) and everything work fine. I think this issue is fixed.
If you dont mind I will close the issue, or if your problem still reproduce, please reopen and give more information.

Thank for your issue :)
