### ISSUE TITLE
Possible to do custom crop aspect ratios?  *Feature*

### ISSUE THREAD

**Issue by Herzogdb** [Yalantis/uCrop#299]
Currently there is a set of pre-defined common aspect ratios (1:1, 4:3, 3:4, 2:3, 3:2, 16:9, 9:16 + aspect ratio of the original image). 

1) Is it possible to customize these?
2) Is it possible to customize the labels (and keep the ratio as it, for example "2x2" instead of 1:1".
3) Is it possible to choose how many ratios are displayed on the screen?

**Comment by Legementarion** [comment]
Already in develop
