### ISSUE TITLE
Question: is it possible to avoid bouncing ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Yalantis/uCrop#3]
if I move the rectangle outside of the bitmap, it sends me back to where I was.

Is it possible to avoid this, and instead have one of these behaviors:
1. just stay there, and crop what's shown.
2. send me to the nearest place that's ok.

The reason is that it's very hard, for example, to crop the image including the edges. 
Same goes for when the image is rotated.

**Comment by shliama** [comment]
Our desired behavior is "send me to the nearest place that's ok".
I'm aware of the issue and trying to find a solution at the moment :octocat:

**Comment by AndroidDeveloperLB** [comment]
@shliama It would be great to be able to have the choice of what to use.
Also, thank you for this cool library.

**Comment by CeccoCQ** [comment]
+1

**Comment by shliama** [comment]
Please check version 1.2.0, above issue must be fixed. I've updated core logic so an image must correct its position smoothly and obviously.

**Comment by AndroidDeveloperLB** [comment]
@shliama Seems to work perfectly.

**Comment by AndroidDeveloperLB** [comment]
Will you also consider the other solution?

**Comment by shliama** [comment]
No, current behavior is by design. Image cannot be cropped if it does not fill the cropping bounds - so it must be forced to fill em.

**Comment by AndroidDeveloperLB** [comment]
@shliama Well, we could choose which color/background to use for the parts that are not of the cropped area of the bitmap.

**Comment by shliama** [comment]
This is how our UCropActivity works. But it's not final - so you are able to extend it and create any behaviour you want.

**Comment by AndroidDeveloperLB** [comment]
@shliama Maybe some day. Currently I'm quite busy. Sorry and thank you for your time.
