### ISSUE TITLE
I want to change setCropGridColumnCount(); runtime as UCrop.Options changes....

### ISSUE THREAD

**Issue by AnkitaKoladiya** [Yalantis/uCrop#302]
Here is my code, I am unable to change setCropGridColumnCount() as I click on the options.

> UCrop.Options options = new UCrop.Options();
> options.setAspectRatioOptions(2,
                                   new AspectRatio("2", 2.0f, 1.0f),
                                   new AspectRatio("4", 4.0f, 1.0f), 
                                   new AspectRatio("6", 6.0f, 1.0f));
> options.setCropGridColumnCount(2);
> options.setCropGridRowCount(0);
> 

i.e If I click option "6",
AspectRatio("6", 6.0f, 1.0f)
I want to set  options.setCropGridColumnCount(6); 

Please help me..

**Comment by Legementarion** [comment]
@AnkitaKoladiya Hello! As I see, at now it impossible. Please wait for release 2.3.0, it will be release UcropView, which can change option dynamically and without any bundles. 
Thanks for issue  ;)
