### ISSUE TITLE
Any option to disable swap ?

### ISSUE THREAD

**Issue by acurax** [Yalantis/uCrop#306]
is there any option to disable swapping in aspect ratio buttons?

**Comment by jbrathod1312** [comment]
have you found the solution ? I am stucked with this

**Comment by acurax** [comment]
No, I didn't. Sorry, Good luck.

**Comment by Legementarion** [comment]
@acurax  @jbrathod1312  Unfortunately this is not realized yet. In next release 2.3.0 will be implemented UcropView, so you may create your-self control panel as you wish 

Thanks for issue :)
