### ISSUE TITLE
No dialog or confirmation that the cropping has started

### ISSUE THREAD

**Issue by timkoers** [Yalantis/uCrop#31]
When cropping an image with `D/TransformImageView: Image size: [4160:3120]` the cropping takes a while. This is not the first priority, but I think you should include a dialog that says something like 

> Processing image...

That would prevent multiple clicks on the crop button and a inpatient user.

Thanks in advance,

Tim

**Comment by shliama** [comment]
Thanks for the feedback :+1: 
And yes, I think it must be added in future update .

**Comment by CeccoCQ** [comment]
+1

**Comment by timkoers** [comment]
No problem, I think I have a custom workaround of the statusbar colors. I'll post the possible solution in the proper issue.

**Comment by timkoers** [comment]
Any updates regarding this issue?

**Comment by shliama** [comment]
Please try version 1.4.0.
Now library shows progress bar and locks UI while loading/cropping image process.
