### ISSUE TITLE
how to change unselected widget color?

### ISSUE THREAD

**Issue by kkarrkid7** [Yalantis/uCrop#312]
I have a problem using this library.
I want to change unselected widget color. but I can't find solution
how to change widget color?
![untitled](https://user-images.githubusercontent.com/11553001/26932744-6bb4093e-4c9f-11e7-8190-807df8be0387.png)

**Comment by Legementarion** [comment]
@kkarrkid7 Hello! Thank you for issue, but unfortunately now, you cant do this. Please wait for next release with UcropView, where you can use custom control panel or create pull request with your solution, we will grad to accept it;)
