### ISSUE TITLE
[instance(0,0,0,0,0x0,non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '/storage/emulated/0/Tencent/QQ_Images/-30f17111747bb151.webp'.

### ISSUE THREAD

**Issue by LuckSiege** [Yalantis/uCrop#315]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by Lebron6** [comment]
I met this problem too. Do you have a solution?

**Comment by Legementarion** [comment]
Please - just try to use 2.2.2 non-native

**Comment by azri92** [comment]
So, the non-native solution is able to handle image file formats other than jpg & png?
