### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by mahendrushivam** [Yalantis/uCrop#316]
Got exception querying content://com.amazon.identity.auth.device.MapInfoProvider.mShop.lite.m2b/bulk_data. Failing after 1 retries.
                                                                                                                      java.lang.IllegalArgumentException: Unknown URL content://com.amazon.identity.auth.device.MapInfoProvider.mShop.lite.m2b/bulk_data
                                                                                                                          at android.content.ContentResolver.insert(ContentResolver.java:1322)

**Comment by severianremi** [comment]
Hello, @mahendrushivam could you provide more information?
Could you provide your code?

**Comment by Legementarion** [comment]
Seems like you try to provide non supportable image format, anyway it still unclear
