### ISSUE TITLE
android emulator java.io.FileNotFoundException "Android N"

### ISSUE THREAD

**Issue by BenCherif** [Yalantis/uCrop#317]
Hi  there , last days i've faced a bug  on android N . i can't get the image from camera or from gallery  .I think the reason is this on =>    Uri.fromFile() it's not work on android N. Plse fix this  .

Kind regards

**Comment by AnkushWalia** [comment]
yes its is issue of file exposed exception. i have changed this code with compatible with nougat. you check it out from this link https://github.com/AnkushWalia/EasyAndroidDevelopment/tree/master/ucrop

**Comment by Legementarion** [comment]
Fixed at last version of Ucrop 2.2.2

**Comment by BenCherif** [comment]
Thanks
