### ISSUE TITLE
i have a question about UcropView

### ISSUE THREAD

**Issue by devPaw** [Yalantis/uCrop#320]
Hello
I have a question about the last part when we crop and show the cropped image, everything works fine but I don't want the image can move when I  touch it, How can I disable that?
Thank you

**Comment by Legementarion** [comment]
@devPaw Do you mean image crop result on ResultActivity, from sample? If I understood you correctly, indeed you can set result to ImageView instead UCropView, 
`imageView.setImageURI(imgUri);`
this might freeze you picture :)

**Comment by devPaw** [comment]
Thank you
