### ISSUE TITLE
resultCode == UCrop.RESULT_ERROR

### ISSUE THREAD

**Issue by Lebron6** [Yalantis/uCrop#323]
Throwable: Throwable   ：[instance(0,0,0,0,0x0,non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '/storage/emulated/0/hupu/games/image/hupuImage/HupuBBS_170626144341-1242822577.png'.

**Comment by severianremi** [comment]
Hello, @Lebron6.
Could you give more information? 
Please, specify android version and show your code
Thanks!

**Comment by Legementarion** [comment]
unclear
