### ISSUE TITLE
Only rotating the image does not trigger change

### ISSUE THREAD

**Issue by reeceengle** [Yalantis/uCrop#324]
When rotating an image, if the image does not need to be cropped (length / width changed) then the library does not alter the image.  

If I have a square image, rotate it 90 degrees and hit save... My changes go unsaved because shouldCrop comes through as false.  I would argue that in this case the photo should be modified.

**Comment by hero0812** [comment]
This issue is the same as #326

**Comment by severianremi** [comment]
This issue was fixed

**Comment by glaucioleonardo** [comment]
Great!  It worked!
