### ISSUE TITLE
Hope to cut the picture after the rotation

### ISSUE THREAD

**Issue by dielian-wizard-ly** [Yalantis/uCrop#326]
When the image is rotated by 90 degrees, the crop image still does not rotate before the picture. Hoping to change the picture after the crop rotation

**Comment by hero0812** [comment]
As the code in BitmapCropTask.java shows:
 boolean shouldCrop = shouldCrop(mCroppedImageWidth, mCroppedImageHeight);
        Log.i(TAG, "Should crop: " + shouldCrop);

        if (shouldCrop) {
            boolean cropped = cropCImg(mImageInputPath, mImageOutputPath,
                    cropOffsetX, cropOffsetY, mCroppedImageWidth, mCroppedImageHeight,
                    mCurrentAngle, resizeScale, mCompressFormat.ordinal(), mCompressQuality,
                    mExifInfo.getExifDegrees(), mExifInfo.getExifTranslation());
            if (cropped && mCompressFormat.equals(Bitmap.CompressFormat.JPEG)) {
                ImageHeaderParser.copyExif(originalExif, mCroppedImageWidth, mCroppedImageHeight, mImageOutputPath);
            }
            return cropped;
        } else {
            FileUtils.copyFile(mImageInputPath, mImageOutputPath);
            return false;
        }
 if you just rotate the image ,the var shouldCrop will return false ...

**Comment by severianremi** [comment]
Hello, @dielian-wizard-ly, @hero0812.  Fix for this issue was merged into master.
