### ISSUE TITLE
Is there any way to prevent crop rect go beyond image width and height?

### ISSUE THREAD

**Issue by virengujariya** [Yalantis/uCrop#327]
I don't want to zoom in photo

**Comment by KucherenkoIhor** [comment]
Hi, @virengujariya. Thank you for your feedback. Please provide more info about your trouble.

**Comment by Legementarion** [comment]
unclear

**Comment by chnouman** [comment]
@KucherenkoIhor I want to set the maximum width to 500 px. How can I achieve this?
