### ISSUE TITLE
Cost time of cropping image 

### ISSUE THREAD

**Issue by rexydimen** [Yalantis/uCrop#330]
I try to use the newest version with native code to crop image in the album of Samsung Phone,but it cost too much time. A picture with pixels 2880*2880 about cropped origin size will cost 49000ms about!! What's wrong with it?

**Comment by KucherenkoIhor** [comment]
HI,  @rexydimen. Thank you for your feedback. Are you sure that you need such a big picture? I think no. Please visit this [page](https://developer.android.com/topic/performance/graphics/load-bitmap.html). Using this tutorial, you can decrease the size of your bitmap and after this crop it.
