### ISSUE TITLE
Using UCroop from Madule

### ISSUE THREAD

**Issue by Mahdihp** [Yalantis/uCrop#332]
Error:Execution failed for task ':ucrop:transformNativeLibsWithStripDebugSymbolForRelease'.
> A problem occurred starting process 'command '/home/mahdi/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-strip''

**Comment by severianremi** [comment]
Hello, @Mahdihp. Could you give more information about this issue?
Please, describe: Where. What happened. Conditions.
Steps to reproduce: What should I do to reproduce the issue.
Thanks!

**Comment by Legementarion** [comment]
unclear
