### ISSUE TITLE
load uCrop on fragment

### ISSUE THREAD

**Issue by miladcoder** [Yalantis/uCrop#335]
dear developers
i want load uCrop on fragment
is it possible ?

**Comment by severianremi** [comment]
Hello, @miladcoder. 
If you want to  start uCrop activity from the fragment use code below:

private void startCropActivity(@NonNull Uri uri) {
        Uri destinationFileName = createFileUri();
        UCrop.of(uri, destinationFileName)
                .withAspectRatio(1, 1)
                .start(getContext(), this, UCrop.REQUEST_CROP);
}
If you want start uCrop fragment. There is no feature in our library for now.

**Comment by Harrypulvirenti** [comment]
+1 for this feature request.

**Comment by Legementarion** [comment]
@miladcoder @Harrypulvirenti  Check out new version of Ucrop 2.2.2, you can get UCropFragment instead UcropActivity

**Comment by ming-xiaoxiao** [comment]
> Hello, @miladcoder.
> If you want to start uCrop activity from the fragment use code below:
> 
> private void startCropActivity(@nonnull Uri uri) {
> Uri destinationFileName = createFileUri();
> UCrop.of(uri, destinationFileName)
> .withAspectRatio(1, 1)
> .start(getContext(), this, UCrop.REQUEST_CROP);
> }
> If you want start uCrop fragment. There is no feature in our library for now.

it is helpful for me !!

**Comment by ChristopherDuran** [comment]
Hi developers, i`m so sorry if is my fault but i want to use this library in my app, in a fragment, but its not working good, well, the uCrop load sucess, the image too, all the tools works fine, but if i press in Crop image and i user Image.setImageUri(imageUriResultCrop); my image that i have in my xml not change, what would can be?, i have used the two versions, the lightweight general solution and the native too.

This is my code in my Fragment: 
ImageView InstagramImagev;

Inside onCreateView:
InstagramImagev = view.findViewById(R.id.InstagramImage);
return view;

This is the code in my button:
startActivityForResult(new Intent().setAction(Intent.ACTION_GET_CONTENT).setType("image/*"), CODEIMGGALLERY);

And now the methods
 @Override
        public void onActivityResult(int requestCode, int resultCode, @Nullable Intent data)
        {
            super.onActivityResult(requestCode, resultCode, data);
            if (requestCode == CODEIMGGALLERY && resultCode == Activity.RESULT_OK)
            {
                Uri imageUri = data.getData();
                if (imageUri != null)
                {
                    startCrop(imageUri);
                }
            }
            else if (requestCode == UCrop.REQUEST_CROP && resultCode == Activity.RESULT_OK)
            {
                Uri imageUriResultCrop = UCrop.getOutput(data);
                if (imageUriResultCrop != null)
                {
                    Toast.makeText(getActivity(), "Image Cropped", Toast.LENGTH_SHORT).show();
                    InstagramImagev.setImageURI(imageUriResultCrop);
                }
            }
        }

        private void startCrop(@NonNull Uri uri)
        {
            String destinationFileName = SAMPLE_CROPPED_IMG_NAME;
            destinationFileName += ".jpg";
            UCrop uCrop = UCrop.of(uri, Uri.fromFile(new File(getActivity().getCacheDir(), destinationFileName)));
            uCrop.withAspectRatio(1, 1);
            //uCrop.withAspectRatio(3, 4);
            //uCrop.useSourceImageAspectRatio();
            //uCrop.withAspectRatio(2, 3);
            //uCrop.withAspectRatio(16, 9);
            uCrop.withMaxResultSize(500, 500);
            uCrop.withOptions(getCropOptions());
            uCrop.start(getActivity(), UCrop.REQUEST_CROP);
        }
        private UCrop.Options getCropOptions()
        {
            UCrop.Options options = new UCrop.Options();
            options.setCompressionQuality(70);

            //CommpressingType
            options.setCompressionFormat(Bitmap.CompressFormat.PNG);
            options.setCompressionFormat(Bitmap.CompressFormat.JPEG);

            //UI
            options.setHideBottomControls(false);
            options.setFreeStyleCropEnabled(true);

            //Colors
            options.setStatusBarColor(getResources().getColor(R.color.colorPrimary));
            options.setToolbarColor(getResources().getColor(R.color.colorPrimary));
            options.setToolbarWidgetColor(getResources().getColor(R.color.White));

            options.setToolbarTitle("Crop Image");
            return options;
            
        }


Thanks for all help guys
