### ISSUE TITLE
Cannot resolve symbols sourceUri and destinationUri

### ISSUE THREAD

**Issue by prasad9323** [Yalantis/uCrop#336]
I am fairly new to android development , and want to use your library for college projext, i have integrated it with gradle, but i am not sure how to start the crop activity, i have put "UCrop.of(sourceUri, destinationUri)
                        .withAspectRatio(1, 1)
                        .withMaxResultSize(maxWidth, maxHeight)
                        .start(this);" on a button to start activity but i get pop up saying "Cannot resolve symbols sourceUri" , smae for destinationUri. I know this might be a silly issue and not worth your time, but I'm really hoping to find an answer.Thank you
![capture](https://user-images.githubusercontent.com/16685522/29249091-71d1f9a4-8046-11e7-9df7-eb2d39bcb8d2.PNG)

**Comment by vxhviet** [comment]
`sourceUri` is the uri to your picture that you want to crop, `destinationUri` is the uri to the destination file that will hold the crop output. Sample code:

```
Uri CROP_INPUT_URI = Uri.fromFile(new File("/storage/emulated/0/Pictures/test/input.jpg"));
Uri CROP_OUTPUT_URI = Uri.fromFile(new File("/storage/emulated/0/Pictures/test/cropout.jpg"));

Ucrop.of(CROP_INPUT_URI, CROP_OUTPUT_URI).start(this);
```
