### ISSUE TITLE
prevent scaling poor quality images 

### ISSUE THREAD

**Issue by developer--** [Yalantis/uCrop#34]
Can you tell me how to stop scaling imageview by touching. I want to call img.setScaleEnabled(false);
when the scaled image pixels count will be less than device screen pixelCount / 4.

**Comment by shliama** [comment]
If you want to add any custom logic - please fork or just include the library as module and add any needed changes.
Also you can try to play with UCrop.Options.setMaxScaleMultiplier() method which basically sets multiplier that is used to calculate max image scale from min image scale.

P.S. What about images that are less than device screen pixelCount / 4 originally?
