### ISSUE TITLE
Possible to move the crop window, resize manually?

### ISSUE THREAD

**Issue by Herzogdb** [Yalantis/uCrop#341]
**Do you want to request a *feature* or report a *bug*?**
FEATURE

**What is the current behavior?**
Currently the crop window is fixed and user must move the image with gestures or using the zoom/rotate/crop. If I have a fixed crop ratio, it seems the crop option has no function so it can be excluded.

Said another way, used cannot move a crop box around the photo. The photo must be moved under the crop box. Sometimes you cannot move the photo in one direction because you are not zoomed in enough and the images bounces back (which creates a bad user experience).

For example, this Android Image Cropper lets you move the crop window around.
https://github.com/ArthurHub/Android-Image-Cropper/blob/master/art/demo.gif?raw=true

**What is the expected behavior?**
Can I move a fixed ratio crop window around the page and make it bigger or smaller.

**Comment by Legementarion** [comment]
Thank you for your issue)

**Comment by Legementarion** [comment]
@Herzogdb Hello! You can just set freeCropStyle like an option of Ucrop, you can look at uCrop sample. And it will work like on your demo gif. Use latest ucrop version :)

Hope it solved
