### ISSUE TITLE
when UCropActivity in fragment,need getCropData in Activity. And why the toobar can't set title

### ISSUE THREAD

**Issue by lhholylight** [Yalantis/uCrop#343]
When start UCropActivity in fragment,need getCropData in Activity. 
Why you don't use toolbar.setTitle And add on TextView in toolbar.
I see the sound code can setToolbarCancelDrawable but the maven source not this option

**Comment by Legementarion** [comment]
@lhholylight Use UCropFragment instead UCropActivity, it will help you customize toolbar as you want, UcropFragment available at last version 2.2.2

Hope it helped you :)
