### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by BruceLiCh** [Yalantis/uCrop#344]
if uCrop.withAspectRatio(3, 4);
then   options.setCompressionQuality(20) not work

**Comment by Legementarion** [comment]
@BruceLiCh Hello! Are you sure that you doing everything right? Because I just reproduce it with ucrop sample and everything work fine. Could you show your code?

**Comment by Legementarion** [comment]
So, have noticed that problem about Compression Quality is real #366 and I will try to fix it, Thank for your report
