### ISSUE TITLE
Bug with cancel button

### ISSUE THREAD

**Issue by jburridge88** [Yalantis/uCrop#345]
Current behaviour:
When the calling activity has a parent activity set (for the purposes of up/back navigation) the UCrop activity takes on this parent attribute. Then, when the cancel button (aka home button) in the UCrop activity is pressed, the app will navigate back to the calling activity's parent, with no onActivityResult or similar methods triggered in the calling activity.

Expected behaviour:
The UCrop activity should by default take on the calling activity as its parent activity so cancelling the activity falls back to the original activity.

To reproduce:
Set up an activity which opens a 2nd activity. Set the parent activity of this 2nd activity to the first activity. Have the 2nd activity open a UCrop activity. Press the X cancel/home button in the top-left corner. Navigation moves to the 1st activity, instead of the 2nd.

UCrop version: 2.2.1
Android SDK version min 23, target 26, tested on 24.

**Comment by cheng-github** [comment]
sorry,I was weak in android.Could you explain to me how to set up an activity open a 2nd activity and let the 2nd open a UCrop activity and set the parent activity of this 2nd activity to the first activity.....
Please tell me detail .... thank u very muck. T_T @jburridge88

**Comment by cheng-github** [comment]
o  I hava found the solution for this bug..Just need to addthe next code :
protected void onActivityResult(int requestCode, int resultCode, Intent data){
case UCrop.REQUEST_CROP:
                if (resultCode == RESULT_OK){
//do what u need to do.............everything is Ok then
}
}

**Comment by jburridge88** [comment]
That is not a solution, that is the method which should be called but isn't. Technically you could add that method to the parent as well, but that is not a viable solution - the intermediate activity must be retained.

**Comment by Legementarion** [comment]
@jburridge88 Hello! You could use UcropFragment instead of UcropActivity, please check out last version of ucrop
