### ISSUE TITLE
appcompat-v7:26.0.1 use uCrop  crop loading long time

### ISSUE THREAD

**Issue by SpiritMan** [Yalantis/uCrop#349]
uCrop 2.2.1
appcompat-v7:26.0.1
image from  camera，The cut page has been loaded，Show image for a long time，
i use appcompat-v7:25.0.0, is very quick ,why?

**Comment by SpiritMan** [comment]
when you first launcher app ,Will happen

**Comment by SpiritMan** [comment]
no body help me

**Comment by chenxi0203** [comment]
i use uCrop 2.2.1 and appcompat-v7:23.2.1    The cut page has been loaded，Show image for a long time too

**Comment by Legementarion** [comment]
@SpiritMan Please, check out last version 2.2.2

**Comment by prasanthvel** [comment]
I have updated the library and tried to crop an Image file size is nearly 14 MB. It takes 7 sec to complete the cropping process

**Comment by nthieu90** [comment]
I got same issue #610
