### ISSUE TITLE
image-dimensions after cropping

### ISSUE THREAD

**Issue by TheWhiteLlama** [Yalantis/uCrop#35]
Hi there!

Is there an easy way of getting the cropping-dimensions after the crop has been done by the user? Since I don't know if the user chooses '4:3', '16:9', etc. I currently have to decode the size of the saved image manually.

Would probably be nice if it was passed after the cropping

**Comment by shliama** [comment]
In 1.3.0 you can get result crop aspect ratio via `UCrop.getOutputCropAspectRatio()` method.
