### ISSUE TITLE
Can you Please let me know similar library like ucrop in ios.. Ucrop library is in Android not in ios.. any other simila one please suggest me

### ISSUE THREAD

**Issue by saengeetaswamy** [Yalantis/uCrop#356]
Please suggest some library in ios similar to ucrop.. Atleast for Rotate option any library .

Can you Please let me know similar library like ucrop in ios.. Ucrop library is in Android not in ios.. any other simila one please suggest me

**Comment by lamson** [comment]
@saengeetaswamy https://github.com/TimOliver/TOCropViewController
