### ISSUE TITLE
Help Required

### ISSUE THREAD

**Issue by aboutgaurav** [Yalantis/uCrop#357]
I was wondering how can i disable image **compression** feature.

Thank you team **Yalantis** for making such an awesome library.

**Comment by Legementarion** [comment]
Hello @aboutgaurav ! I think you can use this -
```
UCrop.Options options = new UCrop.Options();
options.setCompressionQuality(0));
```
by default ucrop use - DEFAULT_COMPRESS_QUALITY = 90

**Comment by aboutgaurav** [comment]
@Legementarion  Thanks
