### ISSUE TITLE
can't give assets URI

### ISSUE THREAD

**Issue by vimalchandhru** [Yalantis/uCrop#358]
My question is exactly this: [https://stackoverflow.com/questions/46996601/how-to-give-assets-uri-in-yalantis-ucrop](url)
Is anything error in my code?

**Comment by Legementarion** [comment]
@vimalchandhru I guess it no clear way, instead of using the assets dir, put the file into /res/raw, and you can then access it using the following URI: android.resource://com.your.packagename/" + R.raw.your_file

I think it solved :)
