### ISSUE TITLE
it will be crash in YunOS mobile

### ISSUE THREAD

**Issue by itchaosfun** [Yalantis/uCrop#360]
when i use MeiZu E2 to upload head portrait in bilibili app, it will be crash frequently

**Comment by Legementarion** [comment]
@itchaosfun Im sorry, but how bilibili app related to ucrop?

**Comment by Legementarion** [comment]
Many Chinese devices has custom firmware, that might override some standard android function. That why happens inexplicable errors, so you must resolve it before you use public library. Library cant cover all Chinese firmware cases, just only most popular.
