### ISSUE TITLE
Crop frame invisible

### ISSUE THREAD

**Issue by Slik1002** [Yalantis/uCrop#361]
Hello.

I use RxPaparazzo and I added crop after choose picture. If I want use original aspect ratio and others then crop frame invisible after initialization. 

Code example: 

`val originalAspect = AspectRatio("Original"), 0f, 0f)`
`val firstAspect = AspectRatio("First", 218f, 123f)`
`val secondAspect = AspectRatio("Second", 340f, 123f)`
`logoOptions.setAspectRatioOptions(0, originalAspect, firstAspect, secondAspect)`

**Comment by Legementarion** [comment]
@Slik1002 Hello! Did you solve you problem?

**Comment by Legementarion** [comment]
unclear
