### ISSUE TITLE
Here's a bug

### ISSUE THREAD

**Issue by ChinaTengFei** [Yalantis/uCrop#362]
When cropping, you can not drag the image by triggering a long press and dragging again

Reference Code

GestureDetector.java   line 593

case MotionEvent.ACTION_MOVE:
if (mInLongPress || mInContextClick) {
                    break;
}

just look here ,it in here break this event

**Comment by Legementarion** [comment]
@ChinaTengFei Hello! I don't think that it's a bug. Most user start to drag the image immediately; it's a more usual user experience. In case if the user starts to long press and then to drag and nothing happens, I believe it will be obvious what the mistake here is.

But anyway, thank you, for your issue :)
