### ISSUE TITLE
Docs don't alert users you expose support-v4 library

### ISSUE THREAD

**Issue by gjsalot** [Yalantis/uCrop#369]
You should add a warning to your docs that you expose some libraries. For example support-v4. You should show users they may need to add the following:

```
implementation('com.github.yalantis:ucrop:2.2.1') {
    exclude module: 'support-v4'
}
```

**Comment by Legementarion** [comment]
@gjsalot Hello! Please check out last ucrop version. Now we use implementation instead of compile and this might be fix it.

Thank you for your issue :)
