### ISSUE TITLE
How to set aspet ratio for free modle?

### ISSUE THREAD

**Issue by flycumt** [Yalantis/uCrop#375]
I want to set aspet ratio for free modle, not just dynamic, hope user to ajust it as he wishes.

**Comment by UltramanTIGA** [comment]
same problem. Have you found way to solve?

**Comment by Legementarion** [comment]
Hi @flycumt ! As shown in ucrop sample you can set -
`UCrop.Options().setFreeStyleCropEnabled(true);`

Is that what you want?

**Comment by Legementarion** [comment]
If you want use aspect ratio with freestyle mode, wait for next release, it now in develop
