### ISSUE TITLE
Want the scaling (Zoom in, zoom out ) of image with seek bar 

### ISSUE THREAD

**Issue by shivchauhan09** [Yalantis/uCrop#379]
In current library the zooming In and zoom out of images is based on horizontal  scale wheel.

But i require the scaling on image with seekbar .
When i am using the same methods the horizontal scale wheel is using.Its not working properly.Please help to introduce the zoom in and out with seekbar.

**Comment by Legementarion** [comment]
Hi @shivchauhan09 ! In Ucrop library zoom based on custom - HorizontalProgressWheelView, I dont see any api or method to replace this view

**Comment by Legementarion** [comment]
So, in next release you will can do it with UcropView, just add your self control panel with seekbar and add listener with setScale, I dont know how much it is convenient but it will.
One more time - just wait ucrop 2.3.0 ;)
