### ISSUE TITLE
Light status bar

### ISSUE THREAD

**Issue by vmartynyuk** [Yalantis/uCrop#383]
How can I change status bar icons as lightstatusbar?

**Comment by Legementarion** [comment]
@vmartynyuk Hi! what do you mean? Can you show example?

**Comment by wa1demar** [comment]
@Legementarion in app I can add to theme parameter lightstatusbar = true. That parameter changes status bar icons to black. After that I can set status bar color, for example, white.

**Comment by Legementarion** [comment]
@vmartynyuk @wa1demar , Hi again, I reproduced want you want and here my conclusion - Use UCropFragment instead UcropActivity, with UCropFragment you can customize your theme as you want. UCropFragment available at last version of Ucrop (2.2.2). Hope I helped you :)

**Comment by vmartynyuk** [comment]
Yep! That's what I want! Thanks!!

**Comment by Legementarion** [comment]
You are welcome :)
