### ISSUE TITLE
NumberFormatException: For input string: "raw:/storage/emulated/0/Download/ic_launcher.png"

### ISSUE THREAD

**Issue by UltramanTIGA** [Yalantis/uCrop#386]
I choose a picture from download folder to crop,it crash and report a error in FileUtils class line 158:

**java.lang.NumberFormatException: For input string: "raw:/storage/emulated/0/Download/ic_launcher.png"**

I search issues about this question,I found a way that update okhttp3 and appcompact version to solve.But I check my project,the okhttp version is 3.8.1,and appcompact-v7 version is 26.1.0,they are all new version,but the question is still alive.

In case,the system version I test is Oreo(8.0)

**Comment by SMH17** [comment]
I don't use okhttp and I have latest appcompat-v7:27.1.0 but I get the same error. Unfortunately this library seems broken on more recent Android versions.

**Comment by pBalakris** [comment]
Here is the solution: 
https://github.com/Yalantis/uCrop/issues/318

**Comment by Legementarion** [comment]
Fixed at last version of Ucrop 2.2.2
