### ISSUE TITLE
Please give a sample about how to use UCropView

### ISSUE THREAD

**Issue by shayegh** [Yalantis/uCrop#397]
I want to use ucrop in a view instead of imageview please give a sample how to do this (like Instagram crop ability)

**Comment by Legementarion** [comment]
@shayegh Unfortunately, you cant use ucrop like a single view. It will be implemented as soon as it possible. But if you want you could try copy code from [UCropActivity](https://github.com/Yalantis/uCrop/blob/master/ucrop/src/main/java/com/yalantis/ucrop/UCropActivity.java) like a sample and implement it to your project. It a hard work, you should understand how it works, but it possible :)

**Comment by maxtracking** [comment]
@Legementarion Why cannot UCropView be used as a single view? It's a public class, isn't it? Yes, one needs to set it up a bit but that's about it.

**Comment by Legementarion** [comment]
@maxtracking So its a public, true. Just for result screen, like shown in sample, you can use it. But if you wanna use it for crop or something else, I recommend you dont do that, this can lead to unknown consequences, crashes, e.t.c.

**Comment by maxtracking** [comment]
Well, in my case I have to because I need to implement some sort of multiple image sharing with the option of editing them in place. What would you recommend in such case? Right now I've created my own activity with ```UCropView``` (I described it in more details in another thread about restoring ```UCropView``` from previous state), and it works OK except ```OverlayView``` cropping rectangle

**Comment by Legementarion** [comment]
@maxtracking I dont understand how you want to edit them all. Multiple Image cropping in a single window, one by one like Whatsapp ?

**Comment by maxtracking** [comment]
@Legementarion One by one, exactly like Whatsapp, so I need to have a way to restore the image state back and forth.

**Comment by Legementarion** [comment]
@maxtracking So, you can do like [there](https://github.com/Yalantis/uCrop/issues/398) 

But unfortunately, you cant save the image crop state, as far as I understand you. But if you want, you can create pull request with your solution. It will help our community :) Or if you have a lot of time, just wait, I will add this feature in todo list

**Comment by maxtracking** [comment]
@Legementarion On the contrary, I **can** save image crop state (ie getting its Matrix and then calling ```setImageMatrix()``` on gesture view). What cannot do yet is to restore **OverlayView**'s cropping rectangle. There is a method to get it but not to set. I'd be happy if UCrop library does something in that direction when I call ```gestureView.setCropRect(rect)```.

**Comment by Legementarion** [comment]
@maxtracking Oh, Okay, can you create pull request with this feature?
