### ISSUE TITLE
Feature: support for multiple images cropping in a single window

### ISSUE THREAD

**Issue by vipulasri** [Yalantis/uCrop#398]
**Do you want to request a *feature* or report a *bug*?**
Feature Request

**What is the current behavior?**
An only single image can be cropped at a time.

**What is the expected behavior?**
Multiple Image cropping in a single window like Whatsapp

**Comment by Legementarion** [comment]
@vipulasri Hello! I think its very custom feature. You could just wait for new ucrop release, which implement ucrop fragment and create yourself screen, something like that - 

![screenshot from 2018-03-30 11 56 22](https://user-images.githubusercontent.com/12141781/38131890-74c4ba32-3411-11e8-88e7-07073ef5a9a3.png)

So, to fragment view you insert ucrop Fragment, then to RecyclerView introduce horizontal layout manager: 

```
LinearLayoutManager layoutManager = new LinearLayoutManager(this, LinearLayoutManager.HORIZONTAL, false);
RecyclerView myCropList = (RecyclerView) findViewById(R.id.recyclerView);
myCropList.setLayoutManager(layoutManager);
```
And create yourself recyclerView adapter with image items, then set onClick to items and just pass image to ucrop fragment

Hope I helped you :)

**Comment by vipulasri** [comment]
@Legementarion Yeah, it will work :) Thanks 👍

**Comment by Mayank1904** [comment]
Hi , If I select multiple images from gallery and handle crop one by one and its working fine, but REQUEST_CROP calls only one time, so how do I get multiple crop images
