### ISSUE TITLE
UCropFragmentCallback 

### ISSUE THREAD

**Issue by R3l0ad3d** [Yalantis/uCrop#399]
in version 2.2.1-native UCropFragmentCallback not found

**Comment by Legementarion** [comment]
@R3l0ad3d Hello! This feature isnt tested yet, but if your heart is brave you could try this :)
`implementation 'com.github.yalantis:ucrop:2.2.2'`

This version in pre-release as you can see
![screenshot from 2018-04-05 12 41 53](https://user-images.githubusercontent.com/12141781/38358773-e807fe0c-38ce-11e8-98d1-92fc07963ba3.png)

**Comment by Legementarion** [comment]
Nowaday you can use ucrop:2.2.2, it out of pre-release.
