### ISSUE TITLE
Support Circular Frame

### ISSUE THREAD

**Issue by devflow** [Yalantis/uCrop#4]
nowdays. many UI using the circle profile images...

just there are guide frame, output must not be circle image.

really thanks for sharing awesome library.

**Comment by hearsilent** [comment]
https://github.com/Yalantis/uCrop/pull/2

Waiting for reopen.

**Comment by shliama** [comment]
This feature will be added in next update. Stay tuned :cake:

**Comment by Rainer-Lang** [comment]
@shliama Is it now included?

**Comment by vanniktech** [comment]
There's a bug with this in 2.2.0 - #225
