### ISSUE TITLE
EXIF Data is not being written to the cropped picture

### ISSUE THREAD

**Issue by timkoers** [Yalantis/uCrop#40]
When having cropped a picture, the EXIF data is not being written or copied from the original image.

I'll try and see what I can do, but don't expect anything soon.

**Comment by JohnWowUs** [comment]
Why would you want the EXIF data preserved for a cropped image?

**Comment by timkoers** [comment]
@JohnWowUs Because that's a part of the image as well. It's not visible however, when uploading the cropped image to a site that handles EXIF data, the user needs to set it manually now.

**Comment by shliama** [comment]
@timkoers Please try version 2.0 and comment if there are any issues :octocat:

**Comment by timkoers** [comment]
I'll enable my uploading code and try your update! Sadly enough there is no need for me to continue using this library. :-( I'll definitely keep it inside my head for any future project!

**Comment by VovaStelmashchuk** [comment]
The current version 2.2.8, has the issue. 

The image lost the EXIF tag with location after crop image. I think the issue need to be reopen.

**Comment by VovaStelmashchuk** [comment]
My mistake, The permission ACCESS_MEDIA_LOCATION require for getting location information from the media files.
