### ISSUE TITLE
Why resized bitmap not anti-aliased?

### ISSUE THREAD

**Issue by 1001101** [Yalantis/uCrop#404]
BitmapCropTask.java:117
***
                Bitmap resizedBitmap = Bitmap.createScaledBitmap(mViewBitmap,
                        Math.round(mViewBitmap.getWidth() * resizeScale),
                        Math.round(mViewBitmap.getHeight() * resizeScale), false);

***

https://github.com/Yalantis/uCrop/blob/offsets_non_native/ucrop/src/main/java/com/yalantis/ucrop/task/BitmapCropTask.java#L119

**Comment by Legementarion** [comment]
@1001101 Hello! You can open Bitmap.java and look at method - createBitmap

```
         paint = new Paint();
         paint.setFilterBitmap(filter);
         if (transformed) {
             paint.setAntiAlias(true);
         }
```
As you can see, anti-Alias set true, if our bitmap is transformed and is it do it. Our last bool value it is a filter, that is responsible for the approximations. Usually it is used when a small image is enlarged in size to improve the picture quality. With a reduction or crop, as a rule, there is no such need.

**Comment by Legementarion** [comment]
I think I answered to your question
