### ISSUE TITLE
 Bounds for bitmap could not be retrieved from Uri

### ISSUE THREAD

**Issue by lifuyuan123** [Yalantis/uCrop#414]
Some models often appear this problem, is there any way to solve it?

**Comment by Legementarion** [comment]
@lifuyuan123 Hello! Could you explain your problem more detail?

**Comment by Legementarion** [comment]
@lifuyuan123 So, anyway check your image before, it may be corrupted.
Next code throw this exception, as you see, we check bitmap size

```
        val parcelFileDescriptor: ParcelFileDescriptor?
        try {
            parcelFileDescriptor = context.contentResolver.openFileDescriptor(inputUri, "r")
        } catch (e: FileNotFoundException) {
            return BitmapResult(bitmapException = e)
        }

        val fileDescriptor: FileDescriptor
        if (parcelFileDescriptor != null) {
            fileDescriptor = parcelFileDescriptor.fileDescriptor
        } else {
            return BitmapResult(bitmapException = NullPointerException("ParcelFileDescriptor was null for given Uri: [$inputUri]"))
        }

        val options = BitmapFactory.Options()
        options.inJustDecodeBounds = true
        BitmapFactory.decodeFileDescriptor(fileDescriptor, null, options)
        if (options.outWidth == -1 || options.outHeight == -1) {
            return BitmapResult(bitmapException = IllegalArgumentException("Bounds for bitmap could not be retrieved from the Uri: [$inputUri]"))
        }

```

**Comment by lifuyuan123** [comment]
@Legementarion Thanks. It's wrong to have some phones taking photos and returning the photo uris.

**Comment by Legementarion** [comment]
@lifuyuan123 Is that was sarcasm? ) Sorry, but im really want to help

**Comment by hfc123** [comment]
试试这个
try {
                        MediaStore.Images.Media.insertImage(getContentResolver(), toFile.getAbsolutePath(), mTackPhotoName, null);//图片插入到系统图库
                    }catch (FileNotFoundException e) {
                        e.printStackTrace();
                    }
                    sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE,mTakePhotoUri));//通知图库刷新

**Comment by ashik169** [comment]
is this issue resolved? should I call the below statement? while camera RESULT_OK

> 试试这个
> try {
> MediaStore.Images.Media.insertImage(getContentResolver(), toFile.getAbsolutePath(), mTackPhotoName, null);//图片插入到系统图库
> }catch (FileNotFoundException e) {
> e.printStackTrace();
> }
> sendBroadcast(new Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE,mTakePhotoUri));//通知图库刷新

**Comment by saymumsany** [comment]
I am facing the same issue while crop the image. Is this issue resolved ? I am using com.github.yalantis:ucrop:2.2.8 . I am facing this issue in Xiaomi Redmi note 8A device and some Realme devices.
