### ISSUE TITLE
java.io.IOException: cimg::fopen(): Failed to open file '/storage/emulated/0/ProGallery/croppedImage1524925983972.png' with mode 'wb'.

### ISSUE THREAD

**Issue by krutikpoojara** [Yalantis/uCrop#417]
Issue generate samsung galaxy note 8 when i am crop image and save my path

**Comment by Legementarion** [comment]
@krutikpoojara Hello! Please try to use non-native version!

**Comment by azri92** [comment]
@Legementarion any explanation why native version would have this issue?

**Comment by Legementarion** [comment]
@azri92 This is code from Cimg. I think in this case I need more information about issue, to reproduce and debug it. But generally it can be anything

> 
>  //! Open a file.
>     /**
>        \param path Path of the filename to open.
>        \param mode C-string describing the opening mode.
>        \return Opened file.
>        \note Same as <tt>std::fopen()</tt> but throw a \c CImgIOException when
>        the specified file cannot be opened, instead of returning \c 0.
>     **/

```
std::FILE *res = 0;
      if (*path=='-' && (!path[1] || path[1]=='.')) {
        res = (*mode=='r')?stdin:stdout;
#if cimg_OS==2
        if (*mode && mode[1]=='b') { // Force stdin/stdout to be in binary mode.
          if (_setmode(_fileno(res),0x8000)==-1) res = 0;
        }
#endif
      } else res = std::fopen(path,mode);
      if (!res) throw CImgIOException("cimg::fopen(): Failed to open file '%s' with mode '%s'.",
                                      path,mode);
      return res;
```

**Comment by divysoni3** [comment]
This problem is in targetSdkVersion 29, Below 29 it is working fine.

**Comment by jerinamathews** [comment]
This problem still exists in version 2.2.8

> java.io.IOException: cimg::fopen(): Failed to open file '/storage/emulated/0/Pictures/Cropped_Image' with mode 'wb'.
      at com.yalantis.ucrop.task.BitmapCropTask.cropCImg(Native Method)
      at com.yalantis.ucrop.task.BitmapCropTask.crop(BitmapCropTask.java:156)
      at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:103)
      at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:36)
      
Anyone found any solution?
