### ISSUE TITLE
change theme color to my application theme

### ISSUE THREAD

**Issue by walaa118** [Yalantis/uCrop#418]
how can i use my theme colors instead of your orange?

**Comment by azri92** [comment]
There are a few options you can set with the uCrop class. These include:
```
setStatusBarColor(int) // commonly colorPrimaryDark
setToolbarColor(int) // commonly colorPrimary
setToolbarWidgetColor(int)
setActiveWidgetColor(int)
```

Keep in mind that the Toolbar title text color is default to _white_, so you can't have a white toolbar.
