### ISSUE TITLE
Disable image orientation

### ISSUE THREAD

**Issue by aboutgaurav** [Yalantis/uCrop#419]
Hi guys i am using this awesome library in one of the my app. Its working flawlessly.

**Current behaviour?**
When i tap on same aspects ratio its changes cropping grid orientation from vertical  to horizontal and vice-versa.

I was looking to disable that feature. Any help and guide will be really helpful.

**Comment by Legementarion** [comment]
@aboutgaurav Hello! Thank you for question, unfortunately you cant disable this feature, but you can do some hack, you should implement ucrop library like a project module, like in ucrop sample, so in gradle -
`    implementation project(':ucrop')`
Then just found UcropActivity or UcropFragment (i dont know what you use for your project), and just comment that lines where you find aspect ratio. But be careful, it might caused to unexpected errors, so test it before release.

**Comment by aboutgaurav** [comment]
@Legementarion  Thanks.

**Comment by Legementarion** [comment]
@aboutgaurav You are welcome :)
