### ISSUE TITLE
Http/Https as uri source not supported

### ISSUE THREAD

**Issue by gromiloff** [Yalantis/uCrop#42]
By code I can see what only file uri supported as source for launch library.
If try to set uri as link to image - get exeption java.io.FileNotFoundException: No content provider

It's because BitmapLoadUtils.decode use only one provider, which try to open existing file on read:
context.getContentResolver().openFileDescriptor(uri, "r")

So,  I think need include functionality for support another uri types.

**Comment by shliama** [comment]
Yes it's not supported nowadays. Sure it's a good feature but I can't give you any estimates. Any contribution is welcome :octocat:

**Comment by JohnWowUs** [comment]
What's the use case for this feature? Is there really a scenario where you want to crop a remote image?

**Comment by gromiloff** [comment]
@JohnWowUs the question is in correct logic.
If you want crop remite image and no need save tmp file before crop and remove after, then this is your requested scenario.

For example, I want set avatar from facebook album. I have the url of image. So, now I must save tmp image to fs, crop, remove tmp image.
But I no need saving operations in app logic.
Lib may do it self.

How would it implement  - the question to lib owner. :)

**Comment by shliama** [comment]
I won't say that we'll never implement this feature, but it definitely doesn't have top priority at the moment. Currently top priority feature is performance and high-resolution image processing via native code.

**Comment by gromiloff** [comment]
it's not high issue)

**Comment by shliama** [comment]
Http/Https Uri support was added in 1.4.0 :octocat:
