### ISSUE TITLE
default back button and toolbar buttons handling

### ISSUE THREAD

**Issue by devloperAditya** [Yalantis/uCrop#422]
I am unable to Handle Default Back button or the Cross button on the tool bar it is giving me error !!! Anyone there who knows this

**Comment by Legementarion** [comment]
@devloperAditya Hello! please, show me your code

**Comment by devloperAditya** [comment]
@Legementarion hello,
@Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        handleCropResult(data);
    }

    public void setupUI(){
        UCrop uCrop = UCrop.of(myUri, Uri.fromFile(new File(getCacheDir(), new Date().getTime() + ".jpg")));
        uCrop = configure(uCrop);
        uCrop.start(ActivityEditPhoto.this);
    }
    public UCrop configure(UCrop uCrop){
        UCrop.Options options = new UCrop.Options();
        options.setToolbarColor(ContextCompat.getColor(this, R.color.crop_toolbar));
        options.setFreeStyleCropEnabled(true);
        options.setCompressionFormat(Bitmap.CompressFormat.JPEG);
        options.setCompressionQuality(29);
        return uCrop.withOptions(options);
    }

    private void handleCropResult(Intent result) {
        final Uri resultUri = UCrop.getOutput(result);
        if (resultUri != null) {
            Intent i = new Intent(ActivityEditPhoto.this, ActivityFilters.class );
            i.putExtra("imageUri",resultUri.toString());
            startActivity(i);
        } else {
            Toast.makeText(this, R.string.toast_cannot_retrieve_cropped_image, Toast.LENGTH_SHORT).show();
        }
    }

**Comment by Legementarion** [comment]
@devloperAditya Hi again! So as I see, you use UcropActivity and there only one way to know activity is finished or not, and it handle result on onActivityResult. But if you want you can use UcropFragment instead, and write yourself toolbar and handle action of cross btn and back btn in your activity, please checkout ucrop sample and you will see how to do it :)

**Comment by devloperAditya** [comment]
@Legementarion Thank you very much
