### ISSUE TITLE
Customize Actionbar color and statusbar color

### ISSUE THREAD

**Issue by Vibinreji** [Yalantis/uCrop#429]
Can anyone help me to change actionbar and statusbar color?

**Comment by Legementarion** [comment]
@Vibinreji Hello! just use UcropFragment instead of UcropActivity,  and everything will fine and paint you toolbar as you want :)

**Comment by Vibinreji** [comment]
I am initating Ucrop like this only.

UCrop.of(sourceUri, destinationUri)
    .withAspectRatio(16, 9)
    .withMaxResultSize(maxWidth, maxHeight)
    .start(context);
How can i use fragment instead of Activity? Can u give me a code snippet plz

**Comment by Legementarion** [comment]
@Vibinreji Try this code from sample :

```
public void setupFragment(UCrop uCrop) {
        fragment = uCrop.getFragment(uCrop.getIntent(this).getExtras());
        getSupportFragmentManager().beginTransaction()
                .add(R.id.fragment_container, fragment, UCropFragment.TAG)
                .commitAllowingStateLoss();
    }
```
Also you might update ucrop to last version 2.2.2
