### ISSUE TITLE
take photo then crop crash happened

### ISSUE THREAD

**Issue by z102339** [Yalantis/uCrop#43]
when i take photo then start crop application crash,but when i select pic from gallery it's ok

**Comment by shliama** [comment]
I think the reason is - wrong Uri. Can you post here an error stacktrace?

**Comment by Kudaybergen** [comment]
@shliama  Which Uri has to be?

**Comment by shliama** [comment]
You can check out the sample. Currently it supports picking images from both local storage or cloud services (e.g. Google Photos or Dropbox). So content/file Uris are fine.

**Comment by Kudaybergen** [comment]
@shliama on android 6.0 it works fine?

**Comment by Kudaybergen** [comment]
@shliama here is my Uri `Uri.parse("content:/capture.jpg");`

**Comment by shliama** [comment]
Yes, it works fine.
But your Uri is not correct.

**Comment by Kudaybergen** [comment]
@shliama What about Genymotion?

**Comment by Kudaybergen** [comment]
@shliama What can be wrong with uCrop
Here is a log
`CameraApp: java.io.FileNotFoundException: No content provider: content://me.capick.app.capture/capture.jpg`

**Comment by shliama** [comment]
Try this: http://stackoverflow.com/questions/3288619/what-to-do-when-java-io-filenotfoundexception-no-content-provider

**Comment by Kudaybergen** [comment]
@shliama Thank u!

**Comment by z102339** [comment]
it's phone's problem ,if i open camera via intent the application will
crash, so  i am sorry about that,  and thanks for your uCrop,it woks very
well.....

2016-02-27 19:31 GMT+08:00 Oleksii <notifications@github.com>:
