### ISSUE TITLE
add text or lines

### ISSUE THREAD

**Issue by psohm** [Yalantis/uCrop#430]
**Do you want to request a *feature* or report a *bug*?**
Feature

It would be very nice to add the feature : adding some items text or line (for example)

**Comment by Legementarion** [comment]
@psohm Hello! Sorry but i think this is not main target of this lib, you could implement it by yourself. Just create fork and then create for example onLongTap event on OverlayView onTouchEvent, where you add custom edit text. Thanks for your issue!
