### ISSUE TITLE
Disable buttons from UI and use free crop & rotate. Bug - No effect if touch in rectangle

### ISSUE THREAD

**Issue by sleepstream** [Yalantis/uCrop#431]
![ezgif-4-d7d1fd673c](https://user-images.githubusercontent.com/10279518/41104609-788f49a4-6a74-11e8-8215-1e2f458a1656.gif)
Redmi Note 4
Android 7.0
'com.github.yalantis:ucrop:2.2.2'

Is it possible to disable (not to show) buttons but still have free crop and rotate?

**Comment by sleepstream** [comment]
disable buttons, found in issue #186

> Currently you can hide bottom view withUCrop.Options.setHideBottomControls(true) method.

**Comment by Legementarion** [comment]
@sleepstream Hello! This isnt a bug :) this crop overlay havent on touch events, you should touch outside of overlay to zoom or rotate, and touch borders of overlay to resize it.

Ucrop has option - setHideBottomControls, try this to hide bottom controls

**Comment by sleepstream** [comment]
It's not comfortable.
From time to time there is big image and big crop rectangle and it's not posssible to resize image from outside of rectangle.

It'll be better if crop overlay have on touch event for double touch.
I can post one more gif to show what i mean.

**Comment by Legementarion** [comment]
@sleepstream  I still waiting for your next gif :)

**Comment by sleepstream** [comment]
One moment!

**Comment by sleepstream** [comment]
![ezgif-2-31f96d081a](https://user-images.githubusercontent.com/10279518/41973862-eed18e56-7a1e-11e8-8d4c-307936834b6c.gif)

Look on it.

I have big picture and want to crp big area.
First i need to rsize crop area to small and next to resize image.
After that i have to resize crop overlay back;

**Comment by p1nkydev** [comment]
@sleepstream Currently you can hide bottom view withUCrop.Options.setHideBottomControls(true) method.

**Comment by SATTIRAMYASRI** [comment]
@sleepstream how did you changed the bottom layout to scale,crop rotate. in my case i am getting crop,rotate,scale.i want to change this layout to crop,scale,rotate.please tell me on how to do it
