### ISSUE TITLE
Implementing Tilt functionality in the image.

### ISSUE THREAD

**Issue by penzebra** [Yalantis/uCrop#435]
I am using UCROP library and able to rotate the image but not able to get code for tilt image horizontally and vertically, for tilt I used rotationY and rotationX on image but white spaces appears in container. 
Please check the attached image and kindly reply...

![tilt_image_issue](https://user-images.githubusercontent.com/16957688/42157007-34754c60-7e0a-11e8-91bb-8b1737a25dc4.png)

**Comment by Legementarion** [comment]
@penzebra Wow! This is Amazing! So how can i help you? our library doesnt support tilt

**Comment by penzebra** [comment]
@Denko Smith

**Comment by penzebra** [comment]
In this library only rotation is integrated , Would you kindly integrate vertical and horizontal tilt of the image.

**Comment by p1nkydev** [comment]
@penzebra It will be added in next releases
