### ISSUE TITLE
resultCode 96 on Android 5.1.1 

### ISSUE THREAD

**Issue by z85510** [Yalantis/uCrop#436]
Thanks for great library but it has a bug on android 5.1.1
resultCode always return 96 but in other phone or sdk it's Ok.

this is my code : 

val uCrop = UCrop.of(resultUri, destination)
that resultUri and destination isn't null ,

resultUri  =
file:///storage/emulated/0/Android/data/com.geexer.dev.cansell/cache/EasyImage/dded5621-d32a-4b39-97cb-71a5918a62c3-984231982.jpg

destination= 
file:///data/data/com.geexer.dev.cansell/cache

what's wrong ? please help me to solve this problem, thanks a lot

**Comment by Legementarion** [comment]
@z85510 Hello! Try to use like in sample, but I dont sure about it
```
UCrop uCrop = UCrop.of(resultUri, Uri.fromFile(new File(getCacheDir(), destinationFileName)));
uCrop.start(this);
```

Totally you could get error from intent extra, maybe it provide more info.
`getIntent().getExtras().getSerializable(UCrop.EXTRA_ERROR)`
 Please let me know, if it works

**Comment by AhmadIzaz** [comment]
@p1nkydev were you able to solve this ???

**Comment by Nikunj2505** [comment]
did you find any solution ?

**Comment by AhmadIzaz** [comment]
@Nikunj2505 I wasnt able to solve so i used another one for basic cropping
