### ISSUE TITLE
How to disable rotation while cropping the image

### ISSUE THREAD

**Issue by devloperAditya** [Yalantis/uCrop#437]
Hello @Legementarion ,
I want to disable the rotation of image while cropping the image (i am not talking about rotation feature)
while i try to crop my image free style roataion is enabled due to which some images gets tilt a little while cropping how can i disable it ???

**Comment by agonist** [comment]
I'm also looking to achieve that, have you find the way ?

**Comment by p1nkydev** [comment]
@devloperAditya It is not supported, you can fork current branch, implement it and, if you want, create a pull request.

**Comment by TheMilanTej** [comment]
I am facing the same issue

**Comment by Dimezis** [comment]
You can disable rotation on the aspect ratio tab, for instance
```Kotlin
setAllowedGestures(UCropActivity.SCALE, UCropActivity.ALL, UCropActivity.SCALE)
```
