### ISSUE TITLE
Support for AndroidX Packages

### ISSUE THREAD

**Issue by frozenex** [Yalantis/uCrop#438]
Unable to use the library with androidx packages.

**Comment by Legementarion** [comment]
@frozenex Hello! Could you give me some logs or error log ?

**Comment by peterhav** [comment]
I'm getting this type of Lint warnings: com.yalantis.ucrop.UCropActivity is not assignable to android.app.Activity.

**Comment by channae** [comment]
My project throws the same error after migrating to AndroidX. Seems like latest uCrop release does not adhere the latest AndroidX package naming convention

**Comment by channae** [comment]
I'll be quoting something which went on Glide AndroidX migration thread which catches my attention. This was the point they made before they decide to migrate. 

> What's the point of not migrating to androidx?
> I think whoever prefers to remain on the old version of first class libs and not target Android P, will also not mind using older version of glide as well.

I guess it makes sense to migrate uCrop to the androidx. If uCrop does not support androidx it will be forcing developers to avoid using latest package naming convention in their project. 
If uCrop migrates to androidx it will be catching up with google's latest package naming convention while whoever does not want to incorporate can use older version of uCrop as whoever don't wanna incorporate latest changes on android won't mind using older version of uCrop. Makes sense

**Comment by p1nkydev** [comment]
@frozenex androidx is comming

**Comment by e-hai** [comment]
@p1nkydev at what time?

**Comment by p1nkydev** [comment]
Hello, sorry for long answer, about few weeks I guess.

чт, 18 июля 2019, 7:23 Eveo <notifications@github.com>:
