### ISSUE TITLE
Button X for close the crop

### ISSUE THREAD

**Issue by yankelandroid** [Yalantis/uCrop#439]
**Do you want to request a *feature* or report a *bug*?**
feature
**What is the current behavior?**
scree blank
**What is the expected behavior?**
close the activity
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
2.2.0

When i click on the button x instead of closing the activity i have a blank screen

**Comment by Legementarion** [comment]
@yankelandroid Hello! Could you show me your code? I need to see how you call ucropActivity

**Comment by yankelandroid** [comment]
yes of course , but i dont use UCropActivity.
I create my own activity.

 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_crop);

        UCrop.Options options = new UCrop.Options();

        options.setToolbarColor(ContextCompat.getColor(this, android.R.color.black));
        options.setStatusBarColor(ContextCompat.getColor(this, android.R.color.black));

        Uri uri = Uri.parse(getIntent().getStringExtra("uri"));

        UCrop uCrop = UCrop.of(uri, Uri.fromFile(new File(getCacheDir(), getSaltString() + ".jpg")));
        uCrop.withOptions(options);
        uCrop.start(CropActivity.this);
    }

 @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        try {
            if (data != null) {
                final Uri resultUri = UCrop.getOutput(data);
                if (resultUri != null) {
                    Intent intent1 = getIntent();
                    intent1.putExtra("uri_cropped", resultUri.toString());
                    setResult(RESULT_OK, intent1);
                    finish();
                }
            }
        } catch (Exception ignored) {

        }


    }

**Comment by p1nkydev** [comment]
@yankelandroid Unfortunately, when you are passing  uCrop.start(CropActivity.this); It is not gonna open your activity, it will simply get the context. By now we are not supporting custom activity.

**Comment by EdgarArsenyan** [comment]
Hello, I want to crop half the image and the black background at the back
