### ISSUE TITLE
How i can change the toolbar color of the crop image class?

### ISSUE THREAD

**Issue by hemantagarg** [Yalantis/uCrop#441]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by hemantagarg** [comment]
I m using 2.2.2 version , this is not a issue i m just asking a query

**Comment by Legementarion** [comment]
@hemantagarg Hi! so you can add to bundle color using tag - EXTRA_TOOL_BAR_COLOR
Or you can use just UcropFragment instead activity and configure you toolbar in your activity as you want 

```
 UCrop uCrop = UCrop.of(uri, Uri.fromFile(new File(getCacheDir(), destinationFileName)));

        uCrop = basisConfig(uCrop);
        uCrop = advancedConfig(uCrop);
        fragment = uCrop.getFragment(uCrop.getIntent(this).getExtras());
        getSupportFragmentManager().beginTransaction()
                .add(R.id.fragment_container, fragment, UCropFragment.TAG)
                .commitAllowingStateLoss();

```

**Comment by MenaouerH** [comment]
> commitAllowingStateLoss

Does'nt work for me i want add it as fragment but i can't
