### ISSUE TITLE
Android Studio 3.2 AndroidX dex issue

### ISSUE THREAD

**Issue by laindow** [Yalantis/uCrop#442]
**Do you want to request a *feature* or report a *bug*?**
Compilation issue - bug

**What is the current behavior?**
Cannot compile application

**What is the expected behavior?**
Should compile and run

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Create a project in Android Studio 3.2
Use new package of libraries AndroidX
//Gradle depends
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.0.0-beta01'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.2'
    implementation 'androidx.lifecycle:lifecycle-extensions:2.0.0-beta01'
    implementation 'androidx.legacy:legacy-support-v4:1.0.0-beta01'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.0-alpha3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0-alpha3'

    //Image processing
    implementation 'com.github.yalantis:ucrop:2.2.2'
    //implementation 'com.github.yalantis:ucrop:2.2.2-native'
}

Simple usage just to run activity
        message.setOnClickListener {

            val sourceUri = Uri.fromFile(File("//assets/im_1.png"))
            val destUri = Uri.fromFile(File("out.png"))
            UCrop.of(sourceUri, destUri)
                    .withAspectRatio(16f, 9f)
                    .withMaxResultSize(1000, 1000)
                    .start(activity as AppCompatActivity)
        }

Try to compile it. You will end up with Dex compilation error. Logs below

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

:app:generateDebugInstantRunAppInfo UP-TO-DATE
:app:transformClassesWithDexBuilderForDebug
AGPBI: {"kind":"error","text":"Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED
:app:buildInfoGeneratorDebug

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/0.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/1.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/2.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/3.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/4.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/5.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/6.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/7.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/8.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/9.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/10.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/11.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/12.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/13.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/14.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/15.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/16.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/17.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/18.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/19.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/20.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/21.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/22.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/23.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/24.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/25.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/26.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/27.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/28.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/29.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/30.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/31.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/32.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/33.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/34.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/35.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/36.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/37.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/38.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/39.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/40.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/41.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/42.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/43.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/44.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/45.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/46.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/47.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/48.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/49.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/50.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/51.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/52.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/53.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/54.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/55.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/56.jar, /Users/u205843/Desktop/projects/trash/try/CapImage/app/build/intermediates/transforms/dexBuilder/debug/57.jar
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: android.support.v4.os.ResultReceiver$MyResultReceiver

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
40 actionable tasks: 20 executed, 20 up-to-date

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

Version 2.2.2

AndroidX libraries - API version doesn't matter

I think it didn't work. 
AndroidX provide new set of classes. I guess you include old support4/support7 into library.

Best regards,
Konstantin.

**Comment by pradeepay** [comment]
Same Issue without compilation with 27... Please help

    compileSdkVersion 27
    buildToolsVersion '27.0.3'

Log Trace: 

:app:compileDebugSources UP-TO-DATE
:app:transformClassesWithDexBuilderForDebug UP-TO-DATE
AGPBI: {"kind":"error","text":"Program type already present: com.yalantis.ucrop.UCrop$Options","sources":[{}],"tool":"D8"}
:app:transformDexArchiveWithExternalLibsDexMergerForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\0.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\1.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\2.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\9.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\13.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\14.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\15.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\16.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\17.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\18.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\25.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\26.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\27.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\28.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\32.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\39.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\40.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\41.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\42.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\43.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\44.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\45.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\46.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\47.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\48.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\49.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\53.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\54.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\55.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\56.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\57.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\58.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\59.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\60.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\61.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\62.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\63.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\64.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\65.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\66.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\71.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\72.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\73.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\74.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\75.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\76.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\93.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\94.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\95.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\99.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\100.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\101.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\102.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\103.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\104.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\105.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\106.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\107.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\108.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\109.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\110.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\111.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\112.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\113.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\114.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\118.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\132.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\133.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\135.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\136.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\146.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\147.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\148.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\149.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\150.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\151.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\152.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\153.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\154.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\155.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\156.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\157.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\161.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\162.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\163.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\164.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\165.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\166.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\167.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\168.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\169.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\170.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\171.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\172.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\173.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\174.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\175.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\176.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\177.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\178.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\179.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\180.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\181.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\182.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\183.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\184.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\185.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\186.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\187.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\189.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\190.jar, /**Project Name**/\app\build\intermediates\transforms\dexBuilder\debug\191.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s

**Comment by p1nkydev** [comment]
@laindow @pradeepay androidx support is coming soon!

**Comment by pradeepay** [comment]
Thank you.

*Thanks & Regards,*


 Every 3000 sheets of paper cost us a tree. Let's consider our
environmental responsibility before printing this e-mail - *Save paper.*
*This email may contain confidential and privileged material for the sole
use of the intended recipient. Any review, use, distribution or disclosure
by others is strictly prohibited. If you are not the intended recipient (or
authorized to receive for the recipient), please contact the sender by
reply email and delete all copies of this message*.
