### ISSUE TITLE
UCropActivity.setupViews() NullPointerException

### ISSUE THREAD

**Issue by bsobe** [Yalantis/uCrop#46]
I'm using uCrop like 
**UCrop.of(imageUri, destination)
.withAspectRatio(16, 9)
.withMaxResultSize(640, 360)
.start(this);**

But, in UCropActivity.setupViews() which is optional UI function, I get nullPointerException at the 
**Bundle optionsBundle = getIntent().getBundleExtra(UCrop.EXTRA_OPTIONS)**
because optionsBundle is Null. 
I think that if I don't use UCrop.withOption() function, it should use default colors or something like that. 
Am I use uCrop right? or should I use UCrop.withOption() function?

**Comment by lennonliuyong** [comment]
同问

**Comment by Jeevuz** [comment]
Agree with @bsobe, will be great to use default colors of the app and default options if withOptions is not called.

**Comment by beiliubei** [comment]
+1

**Comment by patilnaveen** [comment]
+1

**Comment by HosseinKurd** [comment]
i have same problem
how to fix it ?

**Comment by PGMacDesign** [comment]
Same issue here. Will have to leave this out of the project until there is a fix.

**Comment by patilnaveen** [comment]
Work around for this issue, explicitly sending the options to UCrop.

Bundle optionsBundle = new Bundle();

optionsBundle.putInt(UCrop.Options.EXTRA_STATUS_BAR_COLOR, Color.WHITE);
optionsBundle.putInt(UCrop.Options.EXTRA_TOOL_BAR_COLOR, Color.WHITE);
optionsBundle.putInt(UCrop.Options.EXTRA_UCROP_COLOR_WIDGET_ACTIVE, Color.WHITE);
optionsBundle.putInt(UCrop.Options.EXTRA_UCROP_TITLE_COLOR_TOOLBAR, Color.BLACK);
optionsBundle.putString(UCrop.Options.EXTRA_UCROP_TITLE_TEXT_TOOLBAR, "Crop Image");
optionsBundle.putInt(UCrop.Options.EXTRA_UCROP_LOGO_COLOR, Color.BLACK);

UCrop.of(imageUri, destination)
        .withAspectRatio(16, 9)
        .withMaxResultSize(640, 360)
        .withOptions(optionsBundle)
        .start(this);

**Comment by shliama** [comment]
Sorry for dumb error :( 
Fixed in 1.3.1
