### ISSUE TITLE
Image not getting rotated when it matches original image size

### ISSUE THREAD

**Issue by pablote** [Yalantis/uCrop#465]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If the user rotates an image by exactly 90 degrees, it then chooses the exact inverse aspect ratio (say the image was taken in 16:9, then choose 9:16), and the selection frame is chosen so that it fully selects the image, uCrop seems to be returning the original image, without respecting the user's rotation. This does not happen if the rotation drifts slightly from 90, or even if selection crops the image a bit.

**What is the expected behavior?**

I would expect that if a user only rotates an image, then uCrop should return a new rotated image. As I said earlier, this is already the case if the rotation is not exactly 90, or if the images gets cropped a bit.

uCrop 2.2.2
android 7.1.1

**Comment by p1nkydev** [comment]
@pablote  It will be fixed in the next release.

**Comment by hieuseesaa** [comment]
@p1nkydev 
Hello 
Has this problem been fixed?

**Comment by p1nkydev** [comment]
@hieuseesaa Checked right now and yes, after rotation crop area is exactly like image's side.
