### ISSUE TITLE
How to set x, y, width and height for grid before start ucrop activity?

### ISSUE THREAD

**Issue by balkarov** [Yalantis/uCrop#470]
Hello!
Thank you for your library!

How to set x, y, width and height for grid before start ucrop activity?

**Comment by balkarov** [comment]
I found for get x and y
```
data.getIntExtra(UCrop.EXTRA_OUTPUT_OFFSET_X, 0);
data.getIntExtra(UCrop.EXTRA_OUTPUT_OFFSET_Y, 0);
```
how to set initial it?

**Comment by liukefu2050** [comment]
I also need fixed width and height pictures.

**Comment by CodePoem** [comment]
Currently this lib only support aspect ratio X,Y and max cropped image width and height.But I think It's enough, because this lib will handle fitting cropped image width and height when OOM or some other errors happened.

**Comment by p1nkydev** [comment]
@balkarov it is not supported at this time
