### ISSUE TITLE
sometime occur SecurityException

### ISSUE THREAD

**Issue by wslqm123** [Yalantis/uCrop#474]
in most time crop work well , but sometimes it will occur SecurityException
I have require ACTION_OPEN_DOCUMENT in provider before crop

Error messsge:

java.lang.RuntimeException:An error occurred while executing doInBackground()
android.os.AsyncTask$3.done(AsyncTask.java:365)
......
Caused by:
java.lang.SecurityException:Permission Denial: opening provider com.android.providers.media.MediaDocumentsProvider from ProcessRecord{5a77d2c 21343:com.meitu.wide/u0a111} (pid=21343, uid=10111) requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
android.os.Parcel.readException(Parcel.java:1945)
android.os.Parcel.readException(Parcel.java:1891)
android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:4779)
android.app.ActivityThread.acquireProvider(ActivityThread.java:6645)
android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2805)
android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1820)
android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1406)
android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1259)
android.content.ContentResolver.openInputStream(ContentResolver.java:979)
com.yalantis.ucrop.task.BitmapLoadTask.copyFile(BitmapLoadTask.java:210)
com.yalantis.ucrop.task.BitmapLoadTask.processInputUri(BitmapLoadTask.java:179)
com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:93)
com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:44)
android.os.AsyncTask$2.call(AsyncTask.java:345)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
java.lang.Thread.run(Thread.java:784)

**Comment by CodePoem** [comment]
Are you request persistent permissions?

**Comment by wslqm123** [comment]
What's persistent permissions?
Here is my code (before take photo ,I have get camera and storage permission ):

    /**
     * 拍照
     */
    fun takePhoto() {
        val takePhotoIntent = Intent(MediaStore.ACTION_IMAGE_CAPTURE)
        if (takePhotoIntent.resolveActivity(packageManager) != null) {
            val mAvatarFile = createTempAvatarImage()
            if (mAvatarFile != null) {
                mAvatarUri = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                    takePhotoIntent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION) //添加这一句表示对目标应用临时授权该Uri所代表的文件
                    /*7.0以上要通过FileProvider将File转化为Uri*/
                    FileProvider.getUriForFile(this, DEFAULT_PROVIDER_AUTHORITY, mAvatarFile!!)
                } else {
                    /*7.0以下则直接使用Uri的fromFile方法将File转化为Uri*/
                    Uri.fromFile(mAvatarFile)
                }
                takePhotoIntent.putExtra(MediaStore.EXTRA_OUTPUT, mAvatarUri)//将用于输出的文件Uri传递给相机
                startActivityForResult(takePhotoIntent, REQUEST_TAKE_PHOTO_CODE)//打开相机
            }
        }
    }


    /**
     * 打开相册
     */
    private fun openAlbum() {
        val openAlbumIntent = Intent(Intent.ACTION_GET_CONTENT)
        openAlbumIntent.type = "image/*"
        startActivityForResult(openAlbumIntent, REQUEST_CHOSE_PHOTO_CODE)
    }

    private fun cropImage(inputUri: Uri) {
        val maxSize = dip2px(200f)
        val cropFile = createTempAvatarImage()
        if (cropFile == null) {
            PLog.e("UserInfoActivity", "crop fail cause by create temp image fail")
            MTToast.show(R.string.crop_fail_userinfo_community)
            return
        }
        mCropUri = Uri.fromFile(cropFile)
        val options: UCrop.Options = UCrop.Options()
        options.setActiveWidgetColor(getResource().getColor(R.color.color_a1825d_framework))
        options.setToolbarColor(getResource().getColor(R.color.color_a1825d_framework))
        options.setHideBottomControls(true)

        mCropUri?.let {
            UCrop.of(inputUri, it)
                    .withAspectRatio(1.0f, 1.0f)
                    .withMaxResultSize(maxSize, maxSize)
                    .withOptions(options)
                    .start(this)
        }
    }


    override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?) {
        super.onActivityResult(requestCode, resultCode, data)
        if (resultCode == RESULT_OK) {
            when (requestCode) {
                REQUEST_TAKE_PHOTO_CODE -> {
                    mAvatarUri?.let {
                        cropImage(it)
                    }
                }
                REQUEST_CHOSE_PHOTO_CODE -> {
                    if (data?.data != null) {
                        cropImage(data.data)
                    }
                }

                UCrop.REQUEST_CROP -> {
                    data?.let {
                        val resultUri: Uri? = UCrop.getOutput(it)
                        val path = getRealPathFromUri(this, resultUri)
                        mViewModel.uploadAvatar(path)
                    }
                }
            }
        }
    }

**Comment by CodePoem** [comment]
You can look up SampleActivity in this lib:
```
private void pickFromGallery() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN
                && ActivityCompat.checkSelfPermission(this, Manifest.permission.READ_EXTERNAL_STORAGE)
                != PackageManager.PERMISSION_GRANTED) {
            requestPermission(Manifest.permission.READ_EXTERNAL_STORAGE,
                    getString(R.string.permission_read_storage_rationale),
                    REQUEST_STORAGE_READ_ACCESS_PERMISSION);
        } else {
            Intent intent = new Intent(Intent.ACTION_GET_CONTENT)
                    .setType("image/*")
                    .addCategory(Intent.CATEGORY_OPENABLE);

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
                String[] mimeTypes = {"image/jpeg", "image/png"};
                intent.putExtra(Intent.EXTRA_MIME_TYPES, mimeTypes);
            }

            startActivityForResult(Intent.createChooser(intent, getString(R.string.label_select_picture)), requestMode);
        }
    }
```
