### ISSUE TITLE
Caused by java.lang.illeagalStateException: Unknown URL:content://media/external/images/media/-708667163

### ISSUE THREAD

**Issue by Ccapton** [Yalantis/uCrop#477]
**Do you want to request a *feature* or report a *bug*?**
Caused by java.lang.illeagalStateException: Unknown URL:content://media/external/images/media/-708667163
![](https://raw.githubusercontent.com/Ccapton/android-crash/master/image/ucrop_bug.jpeg)

**What is the current behavior?**
**crash**

**What is the expected behavior?**
**select a picture normally**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by p1nkydev** [comment]
@Ccapton Try to use native variant

**Comment by holic21225** [comment]
@p1nkydev hello, how to solve this issue? This issue occurs in my own project too....the id of content is negative, like content://media/external/images/media/-507287521
