### ISSUE TITLE
If is it possible to set crop window - Oval? and set it position closer to the top? Because I would like to write the text on the bottom

### ISSUE THREAD

**Issue by alekseytimoshchenko** [Yalantis/uCrop#478]
Please explain me how I can to customize this crop lib?
This lib is exactly what I need, but instead of Rect crop window I need Oval that will be fixed close to the top. 

And also if is it possible to change the color of the area off the crop window?

Thanks

**Comment by CodePoem** [comment]
I have the same request.However, in my own experience, you can't be satisfied.All you can use is in this class UCrop.java.
In addition,I solve my request by my pull requests to support simple custom crop activity ui, but it's not accepted yet.
[https://github.com/Yalantis/uCrop/pull/475](url)
Hope some helpful~

**Comment by alekseytimoshchenko** [comment]
@CodePoem According to your pull request I understood that you provide the option to use your custom view, but what about the crop window? I need that it has Oval shape instead of Rect... What do you think about it?

**Comment by CodePoem** [comment]
@alekseytimoshchenko Currently, it seems that only support Rect and Circle (the setCircleDimmedLayer method).If you want to custom Oval crop window, I think you have to add  Oval 
 shape support in OverlayView.java (try to rewrite the drawDimmedLayer method).

**Comment by alekseytimoshchenko** [comment]
@CodePoem  Could you please upload your project with your commits to github or anything else? Because I see that I need my custom layout implementation... Thanks in advance

**Comment by alekseytimoshchenko** [comment]
@CodePoem Thanks a lot! You helped me a lot. Maybe you know the answer for this question. Look I am trying to copy and paste ucrop module to my project. But I am getting such error  `The module 'ucrop' is an Android project without build variants, and cannot be built.
Please fix the module's configuration in the build.gradle file and sync the project again.` do you know how to fix it?

**Comment by alekseytimoshchenko** [comment]
@CodePoem  I found the solution here https://stackoverflow.com/a/53932042/5709159 
Now all is ok)) thanks!
