### ISSUE TITLE
Option to edit picture in picture editing apps

### ISSUE THREAD

**Issue by vanniktech** [Yalantis/uCrop#48]
It would be nice to have an option to let the user still nonetheless choose another application to edit the picture further (e.g. Google Photos).

This can be archived using 

```java
Intent editIntent = new Intent(Intent.ACTION_EDIT);
editIntent.setDataAndType(uri, "image/*");
editIntent.setFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
startActivity(Intent.createChooser(editIntent, null));
```

Is there any interest in adding this to the core library?

**Comment by shliama** [comment]
I think it is an excess feature for the library. You can always add these four lines of code in your `onActivityResult` method and pass resulting Uri.

**Comment by vanniktech** [comment]
The only problem would be then that this 'trigger' would need to happen on another screen and not the one from uCrop which makes the feature itself a bit cumbersome.

Is there anyway to add custom views to this library and then also update the picture? To basically enable a back and forth between uCrop and other editing apps?
