### ISSUE TITLE
OverlayView is freely cropped according to a fixed ratio

### ISSUE THREAD

**Issue by Mixiaomi** [Yalantis/uCrop#488]
Hello!
Thank you for your library!
OverlayView is freely cropped according to a fixed ratio, such as 1:1 width and height constraints, but can be freely dragged and zoomed. How can I achieve this? thanks!!

**Comment by CodePoem** [comment]
I guess that you need to custom crop activity.Just like this Issue #478 .

**Comment by p1nkydev** [comment]
@Mixiaomi Checkout readme part about customization if it wouldn't help you, try to create custom activity.
