### ISSUE TITLE
16K image becomes lower than 1K

### ISSUE THREAD

**Issue by iRYO400** [Yalantis/uCrop#49]
I used the Sample from GPlay. When I tried to crop 3558x4656 image I got 520x660 in the output. Aspect Ratio =Original, 100% "zoom" and 100% quality. 
How can I solve it.

**Comment by iRYO400** [comment]
![photo-1454430690613-c5fbdb397f65](https://cloud.githubusercontent.com/assets/12654767/13489281/4b1b466c-e150-11e5-95ad-f83facb9e81f.jpg)
![1456994989669_samplecropimage](https://cloud.githubusercontent.com/assets/12654767/13489292/5d1e2028-e150-11e5-8dd9-7b65c347bb45.jpeg)

First is original, second cropped

**Comment by shliama** [comment]
Currently image is cropped with java and it's not really possible to allocate enough memory to load a Bitmap, than rotate and crop it. Therefore image is downscaled. However it's ok for a lot of the use cases - e.g. avatars.
However I'm working on native solution (currently no ETA) - so library will be able to preserve image resolution.

**Comment by iRYO400** [comment]
Okay, thanks for response

**Comment by iRYO400** [comment]
I'm still here and waiting for it :D

>    Version: 2.0 (COMING SOON)
> 
> Native image crop (able to crop high-resolution images).

**Comment by developer--** [comment]
would be great

**Comment by ben-zhong** [comment]
+1 also looking forward to this feature :)

**Comment by shliama** [comment]
Please try version 2.0 and comment if there are any issues :octocat:
