### ISSUE TITLE
ERROR: Failed to resolve: com.github.yalantis:ucrop:2.2.2

### ISSUE THREAD

**Issue by eyalUsEnergy** [Yalantis/uCrop#490]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by eyalUsEnergy** [comment]
Hi,
I have try to implements your library in my application.
I have added  - maven { url "https://jitpack.io" } in the repositories
After i have added -  implementation 'com.github.yalantis:ucrop:2.2.2'
When try to re-sync my gradle, i got the following error  - ERROR: Failed to resolve: com.github.yalantis:ucrop:2.2.2

**Comment by p1nkydev** [comment]
@eyalUsEnergy Makes sure that you added "maven { url "https://jitpack.io" }" in allprojects and not in buildscript
