### ISSUE TITLE
to support camera

### ISSUE THREAD

**Issue by hss01248** [Yalantis/uCrop#5]
Nowdays many apps require pic captured from camera ,will you add this function?

**Comment by shliama** [comment]
The library itself takes an Uri as an input. How to get an Uri - it's up to you ;)

I've implemented picking a image via Intent.ACTION_GET_CONTENT in the sample just to show you an example.
There are a lot of info - how to get an Uri from camera intent in the internet (e.g. on http://stackoverflow.com)

**Comment by Rainer-Lang** [comment]
@hss01248 Try EasyImage https://github.com/jkwiecien/EasyImage
