### ISSUE TITLE
Crop twice

### ISSUE THREAD

**Issue by Olaman** [Yalantis/uCrop#50]
Problem: My Imageview and Pick&CropButton are in the same activity. With this library, first time I pick and crop , then set the uri to imageview, It works well. Then i pick another photo and crop. No Crash.
But the imageview still display the former one. 

How to repeat：In your sample project. 1.add an imageview in activity_sample, 2. In SampleActivity's mehtod "handleCropResult()", row 291, use             mImage.setImageURI(resultUri);
            // ResultActivity.startWithUri(SampleActivity.this, resultUri);

pick and crop photos. You will find out.

How to fix this?

**Comment by Olaman** [comment]
I got it. Each time call " mImage.setImageURI(null) first " then call "mImage.setImageURI(resultUri)". It works.

**Comment by shliama** [comment]
Glad you've figured it out :)
