### ISSUE TITLE
Is there a way to customize the crop frame image?

### ISSUE THREAD

**Issue by Seichis** [Yalantis/uCrop#51]
I want to have another  image instead of the grid as the crop frame. Is there a way to do that fast or should I extend the UCropActivity to do that myself?

**Comment by CeccoCQ** [comment]
+1

**Comment by shliama** [comment]
Can you specify what exactly you want instead? 
Currently you can change the number of rows/columns of the grid (so if you set zero - it will be just a rectangle) or you can choose circle shadow overlay.

**Comment by CeccoCQ** [comment]
For example, adding an image like a frame.

**Comment by shliama** [comment]
Still not clear for me. What is the use case?
Anyway I don't think we're going to add this kind of feature soon.
