### ISSUE TITLE
App Crash using yalantis uCrop Library On UCropActivity.setupViews() NullPointerException

### ISSUE THREAD

**Issue by HosseinKurd** [Yalantis/uCrop#52]
After Import Yalantis uCrop to Project, when i want to Crop Image And Call Library Methods LogCat shows NullPointerException Crop Method Attached :

[crop.txt](https://github.com/Yalantis/uCrop/files/160340/crop.txt)

in Logcat

`Do Crop -> PICK FROM FILE : /storage/emulated/0/Android/data/com.emaarit.app.erbgroup/.files/storage/emulated/0/Android/data/com.emaarit.app.erbgroup/.files/.HK13670922/IMG_20160306_163157.jpg`

And 

`get Uri From Path -> Uri : /storage/emulated/0/Android/data/com.emaarit.app.erbgroup/.files/storage/emulated/0/Android/data/com.emaarit.app.erbgroup/.files/.HK13670922 	 file:///storage/emulated/0/Android/data/com.emaarit.app.erbgroup/.files/storage/emulated/0/Android/data/com.emaarit.app.erbgroup/.files/.HK13670922`

it means 'mImageCaptureUri' And getUriFromPath() Is Not Null

How To Fix It ?

**Comment by bsobe** [comment]
@HosseinKurd can you copy here all exception log?

**Comment by HosseinKurd** [comment]
I just Add 'UCrop.Options' To Crop Method

`        UCrop.Options options = new UCrop.Options(); // Here`
`        UCrop.of(mImageCaptureUri, getUriFromPath())`
`                .withAspectRatio(10, 10)`
`                .withMaxResultSize(UI.width, UI.height)`
`                .withOptions(options) // Here`
`                .start(this);`
 
And it Works!
Error Log Before Add New Line Attached

[error.txt](https://github.com/Yalantis/uCrop/files/160398/error.txt)

**Comment by bsobe** [comment]
Yes, current version of the uCrop needs a control statement for optional UCrop.Option. For now, you must use UCrop.Option and UCropActivity must use NoActionBar theme..

**Comment by shliama** [comment]
Fixed in 1.3.1
