### ISSUE TITLE
UCropActivity setToolbarColor ,setStatusBarColor error Resource

### ISSUE THREAD

**Issue by buivanlien** [Yalantis/uCrop#528]
When i setToolbarColor with setStatusBarColor i have problem with error in device lenovo,android 5.1, more device normal when set color, but when device lenovo error.
 Unable to start activity ComponentInfo{com.bbrosone.dev127/com.yalantis.ucrop.UCropActivity}: android.content.res.Resources$NotFoundException: Resource ID #0x7f0700a6.
Can you help me(Sorry with my bad English )
Thanks you

**Comment by sosasang** [comment]
Same crash. I think the reason is some attributes in ucrop_ic_cross.xml are not compatible with low Android version(for me, 99% reports are from devices running on Android 4)

**Comment by buivanlien** [comment]
I have fix when add //        AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
https://stackoverflow.com/questions/34417843/how-to-use-vector-drawables-in-android-api-lower-21
