### ISSUE TITLE
Crop webp image with com.github.yalantis:ucrop:2.2.2-native will fail

### ISSUE THREAD

**Issue by BenWong927** [Yalantis/uCrop#530]
This is a bug.
When I crop a webp format image file with uCrop-native, I can not get cropped image file.
The error message is :
 java.io.IOException: [instance(0,0,0,0,0x0,non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '/storage/emulated/0/tencent/MicroMsg/WeiXin/mmexport1558931524440.webp'
The image file is here:
[https://drive.google.com/open?id=1sxF35o6bLGXHn1yu07sCG_-iqJiGBouw](url)

The simplify code to reproduce the bug:
`String fromFile = "/storage/emulated/0/tencent/MicroMsg/WeiXin/mmexport1558931524440.webp";`
`String toFile ="/storage/emulated/0/test.webp";`
`BitmapCropTask.cropCImg(fromFile, toFile, 0, 0, 900, 1153, 0, 1,
                    0, 100, 0, 1);`

Another way to reproduce the bug is to use the uCrop sample and pick the webp image.
Neither ucrop:2.2.2-native nor ucrop:2.2.3-native can work as expected in my Android devices.

Can you solve the bug? Thank you.

**Comment by azri92** [comment]
Related to issue #166

**Comment by BenWong927** [comment]
> Related to issue #166

Thanks for your reply!

**Comment by azri92** [comment]
My pleasure. Unfortunately, it seems like the only solution for now is to convert images to jpeg or png before using uCrop. However, I haven't been able to find a native (c++) solution to convert from formats like webp, heic & gif.

**Comment by BenWong927** [comment]
I will try to solve the problem as you suggested. I will try to use [libwebp](https://chromium.googlesource.com/webm/libwebp) to do that.

**Comment by p1nkydev** [comment]
Duplicate #166
