### ISSUE TITLE
Fit the entire large image inside the fixed crop window

### ISSUE THREAD

**Issue by midhun-murali** [Yalantis/uCrop#532]
I have an image which has height greater than its width. I want to achieve something like user can pinch zoom out to fit the whole image inside a fixed cropping window. If there is any empty space after zooming out then it should be filled with a default color like black or white. 
Something like

<img width="867" alt="Screenshot 2019-05-30 at 1 38 44 PM" src="https://user-images.githubusercontent.com/16605758/58619020-9163cc80-82e1-11e9-89ee-1e937583a3eb.png">

Is this possible with this library.
And thank you for providing this wonderful library.

**Comment by p1nkydev** [comment]
@midhun-murali Hi, thanks for the feedback! This isn't possible yet, we will add it in some of next releases.

**Comment by kaustav07** [comment]
Is this implemented yet? I can't crop the image without data loss if I zoom out then it sprung back to fit the screen.
