### ISSUE TITLE
cropview screen is black

### ISSUE THREAD

**Issue by arash-jahani** [Yalantis/uCrop#54]
Sometimes when i choose an image , crop image viewer didnt shows anything (just a black screen) , after sometimes it workes
![device-2016-03-06-194855](https://cloud.githubusercontent.com/assets/2876900/13555407/1032cae8-e3d5-11e5-9bd1-0855f1dd1b67.png)

**Comment by HosseinKurd** [comment]
In My Case it's Because You selected Big Image Size And It takes some Second To Load It
Wait Some Seconds (10 Seconds) And Tell Me What Happeneds

**Comment by shliama** [comment]
I don't really know what kind of images you pick, but for me it never takes more than a second to show the image even if I pick some with 4k resolution. (I was testing on wide range of devices, including old bricks)

**Comment by HosseinKurd** [comment]
it happened some times
my device is HTC Desire 626 G+ Android 4.4.2

I Test 'Many' Images And After Selecting Pictures From Camera Directory It Happened

is it because heap memory ?
im myandroid manifest `android:largeHeap="true"`
so you can test it with fasle

**Comment by aelimill** [comment]
Same here after upgrading to 1.3.+ I had a lot of messages in logcat about freeing memory (repeated messages freed a couple of megabytes). I think this is related to background thread loading, when something goes wrong and it loops again and again.

**Comment by shliama** [comment]
Well, it tries to load downsampled Bitmap - if it fails with OOM - library will try to load even more downsampled Bitmap and so on.

**Comment by arash-jahani** [comment]
It happened sometimes i launch the app in every time when i pick an image , but after relaunch the app it's never happened on this launched instance.
Size of image is not the problem, because i pick images with small size

**Comment by shliama** [comment]
Unfortunately I cannot reproduce the issue. Can you give me stacktrace or something?

**Comment by issuetree** [comment]
I had same this issue. Test device is Samsung Galaxy Player 5.0 on Android 2.3.6.

**Comment by nmghelani** [comment]
I have changed color of widgets any layout as my app has dark theme. I have changed every color but still bottom widget color remains black and as background is also black, they are being hidden. I've attached ss of my ucrop activity. My color.xml is: 
`<color name="ucrop_color_toolbar">#000000</color>
    <color name="ucrop_color_statusbar">#ab000000</color>
    <color name="ucrop_color_toolbar_widget">#FFFFFF</color>
    <color name="ucrop_color_widget">#FFFFFF</color>
    <color name="ucrop_color_widget_active">#FFFFFF</color>
    <color name="ucrop_color_widget_background">#000000</color>
    <color name="ucrop_color_widget_text">#FFFFFF</color>
    <color name="ucrop_color_progress_wheel_line">#FFFFFF</color>
    <color name="ucrop_color_crop_background">#FFFFFF</color>
    <color name="ucrop_color_default_crop_grid">#80ffffff</color>
    <color name="ucrop_color_default_crop_frame">#ffffff</color>
    <color name="ucrop_color_default_dimmed">#8c000000</color>
    <color name="ucrop_color_default_logo">#FFFFFF</color>`

![ss1](https://user-images.githubusercontent.com/43907163/54040153-b832cb00-41ea-11e9-8493-b358a9f57747.png)
