### ISSUE TITLE
Integrated uCorp in Unity meet compile error

### ISSUE THREAD

**Issue by chriszhao001** [Yalantis/uCrop#544]
**Do you want to request a *feature* or report a *bug*?**
I think it is maybe a bug.
**What is the current behavior?**
When I try to integrated uCorp into Unity, I meet a compile error:
com.android.build.api.transform.TransformException: Error while generating the main dex list.
I check this error from web, This error was because of having two same classes in two modules. Which means maybe uCorp have some classes same in unity android lib.
**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
I just add uCorp lib in unity's build.gradle, which in C:\Program Files\Unity\Hub\Editor\2019.1.5f1\Editor\Data\PlaybackEngines\AndroidPlayer\Tools\GradleTemplates\mainTemplate.gradle, add two line like below:
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        flatDir {
            dirs 'libs'
        }
    }
}

dependencies {
    implementation 'com.android.support:multidex:1.0.1'
    implementation 'com.github.yalantis:ucrop:2.2.3'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
**DEPS**}

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
Any help will be great appreciated.

**Comment by TermLog** [comment]
@chriszhao001 uCorp wasn't designed for Unity.
