### ISSUE TITLE
Could not resolve com.yalantis:ucrop:1.3.+.

### ISSUE THREAD

**Issue by HosseinKurd** [Yalantis/uCrop#56]
When i want to launch my app from IDE (Android Studio) it shoews Build Error

`Error:A problem occurred configuring project ':app'.`
`> Could not resolve all dependencies for configuration ':app:_debugCompile'.`
`   > Could not resolve com.yalantis:ucrop:1.3.+.`
`     Required by:`
`         ErbGroup:app:unspecified`
`      > Failed to list versions for com.yalantis:ucrop.`
`         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/yalantis/ucrop/maven-metadata.xml.`
`            > Could not GET 'https://jcenter.bintray.com/com/yalantis/ucrop/maven-metadata.xml'.`
`               > Connection to https://jcenter.bintray.com refused`

whats problem ?
it worked yesterday, so today,  i can not launch it (no library added or removed or changed) !!!

**Comment by shliama** [comment]
Yes, I had some issues with updating the library to maven. Version 1.3.1 should be available in half an hour.

**Comment by HosseinKurd** [comment]
so change 1.3.+ to 1.3.1 ?

**Comment by shliama** [comment]
No. It's working with 1.3.+ already - just checked.
