### ISSUE TITLE
Enable crop gesture from horizontally and vertically  

### ISSUE THREAD

**Issue by GauravP123** [Yalantis/uCrop#565]
can we enable cropping from anywhere(4,5,6,7...) instead of 4 grid corners(0,1,2,3)? 

     0----4--->1
      |                |
     7|               |5
      |                |
      3<---6----2
     
And when we do rotation can we scale the image to fit xy

**Comment by TermLog** [comment]
@GauravP123
The changing of the cropping area is enabled only from the corners of the grid.

An image will be scaled automatically to fit XY of the cropping area if needed after rotation.
