### ISSUE TITLE
How to modify the size of the initial crop frame?

### ISSUE THREAD

**Issue by HyOrange** [Yalantis/uCrop#569]
I set the original ratio to 1:1.The initial clipping box is too big. I hope it's smaller. What should I do?
![image](https://user-images.githubusercontent.com/24643805/65227104-a49de080-dafa-11e9-9e0c-b9da9abcb236.png)

**Comment by Marina24** [comment]
Hi, @HyOrange you should use the original image ratio. Then your initial clipping box will be the same size as your image.
