### ISSUE TITLE
Is there a way to hide all tabs except for one.

### ISSUE THREAD

**Issue by fl1pflops** [Yalantis/uCrop#57]
I want to leave only a crop tab and disable a rotation tab.

**Comment by shliama** [comment]
I think you should extend UCropActivity and make these changes.

**Comment by vxhviet** [comment]
Dear @shliama, thanks you for your awesome work however I have a small question. I would like to extend `UCropActivity` for further customization. However, your `UCrop` is designed as a singleton with no public constructor and you hardcode the new opened activity to always be `UCropActivity` like this:

```java
public Intent getIntent(@NonNull Context context) {
        mCropIntent.setClass(context, UCropActivity.class);
        mCropIntent.putExtras(mCropOptionsBundle);
        return mCropIntent;
    }
```  

That makes referring to my extended UCropActivity impossible. Currently I'm just copy over the code, but I feel like there's a more elegant way to handle this.

Thank you so much for your time.

**Comment by shliama** [comment]
In fact you can do it right now:

Intent intent = uCrop.getIntent(context);
intent.setClass(context, YOUR_EXTENDED_ACTIVITY.class);
startActivity(intent);
