### ISSUE TITLE
UCrop.start should work with android.app.Activity

### ISSUE THREAD

**Issue by gildor** [Yalantis/uCrop#586]
After update to uCrop 2.2.4 I see that UCrop.start(activity) method requires AppCompatActivity, which is completely unnecessary because it just starts intent. Because of this change, we cannot use this method anymore from Activites that do not implement AppCompatActivity, even ones from AndroidX, like ComponentActivity or FragmentActivity. 

I believe this was not intentional change and should be reverted.

I see that it's not an issue in master, but still issue in 2.2.4. I can create a PR to fix it in 2.2.4 tag and create a new branch for 2.2.5

**Comment by TemMax** [comment]
Same issue. And now waiting for fix.

**Comment by gildor** [comment]
It's actually a bigger issue than just unnecessary restricted API, it's also binary incompatible

**Comment by p1nkydev** [comment]
@gildor Fixed
