### ISSUE TITLE
Kotlin Branch?

### ISSUE THREAD

**Issue by IronFuturist** [Yalantis/uCrop#588]
Just curious if you were going to create a kotlin branch?

**Comment by gildor** [comment]
What is "a kotlin branch"?

**Comment by IronFuturist** [comment]
Instead of writing this in java re-write it for kotlin? The language.

**Comment by gildor** [comment]
We have 90% of Kotlin code, but I see no reason to rewrite this library on Kotlin. What is the point of this? It anyway cannot be used on multiplatform, it will not add any value, just a waste of time
