### ISSUE TITLE
[Question] How to customize rotation from 0 to 270 with slide bar ?

### ISSUE THREAD

**Issue by chihung93** [Yalantis/uCrop#591]
Hello everybody,
I have a slider bar from 0 to 100, and I want to rotate from 0 to 270 degrees, but I don't know how to do that. I read the source code but only see this method `postRotate`

` mGestureCropImageView.postRotate(delta / ROTATE_WIDGET_SENSITIVITY_COEFFICIENT);`

Thanks.

**Comment by Marina24** [comment]
Hi, @chihung93 You can fork and implement similar logic for your needs to HorizontalProgressWheelView
