### ISSUE TITLE
File Loading Permission Issue

### ISSUE THREAD

**Issue by poudelanuj** [Yalantis/uCrop#594]
I recently updated my phone to android 10. When I load an image from the gallery, the activity crashes and image won't be loaded. But when I try with android 9 device it worked smoothly. [](url)
![Screenshot from 2019-11-19 17-00-32](https://user-images.githubusercontent.com/25714396/69142385-c7df0f00-0aee-11ea-9494-e61dce4deb79.png)

**Comment by Shirwee** [comment]
Same issue!
 Is there a timeline on a fix for this?

**Comment by xyzira** [comment]
Same here

**Comment by blessedCode07** [comment]
Facing same issue. How to fix this issue?

**Comment by HanGao1** [comment]
+1

**Comment by blessedCode07** [comment]
I was facing the same problem. Now i have found the solution. Check out here:

https://medium.com/@arkapp/accessing-images-on-android-10-scoped-storage-bbe65160c3f4?source=friends_link&sk=675c33e4595709bce43461ad01154391

**Comment by huang125** [comment]
+1

**Comment by huang125** [comment]
This is the important.
![image](https://user-images.githubusercontent.com/24449787/71516924-9d9b2100-28e6-11ea-89af-b1d5a8876b04.png)

**Comment by joker-fu** [comment]
#606

**Comment by poudelanuj** [comment]
add this line to the
 <application
......
        android:requestLegacyExternalStorage="true"
......../>
