### ISSUE TITLE
Questrion:Why i can not crop from the image's left-top corner?

### ISSUE THREAD

**Issue by SwordBearer** [Yalantis/uCrop#6]
When i drag the image to fit crop-frame's left-top corner, it go back to the crop-frame's center, how can i
avoid this?  thank you for this library.

**Comment by shliama** [comment]
I cannot understand your problem. Please add more information or/and attach video/gif that shows your problem.
Thanks

**Comment by SwordBearer** [comment]
@shliama Thank you for reply, my question is I found that i cannot crop the image from left-top corner

**Comment by shliama** [comment]
Still not sure if I understand the issue. 
If you want to remove padding around the crop frame - you can override that dimen in you application dimens.xml.

**Comment by shliama** [comment]
Please check version 1.2.0, above issue must be fixed. I've updated core logic so an image must correct its position smoothly and obviously.
