### ISSUE TITLE
About get the matrix to restore the image state

### ISSUE THREAD

**Issue by Lemniscate317** [Yalantis/uCrop#600]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

Thanks the library , it is good , it helps me to slove my project 's problem.
My english is not very good , sorry about it.
My project need to crop many pictures , so i need to crop one by one.
So i have a question , how can i store the pic's state which i can restore when i need to crop it.
I try to getImageMatrix , i can get a matrix object , and when i set it back by 'setImageMatrix', also invalidate it . But it does not work.
So i want to know how can i store the image's state(may be scale , translate and so on), so i can restore the state when i crop them one by one.
Hope you can reply me . 
Thanks you sir

**Comment by Marina24** [comment]
Hi, @Lemniscate317  You can save image crop state (ie getting its Matrix and then calling setImageMatrix() on gesture view). You cannot restore OverlayView's cropping rectangle. But if you want, you can create a pull request with your solution :)
