### ISSUE TITLE
Functionality to Flip image

### ISSUE THREAD

**Issue by mitsubisu** [Yalantis/uCrop#604]
Hi, uCrop is good library for crop the images, but flipping image is also very useful for users if we can implement that in this library. 

There are 2 type of flips which you implemented in Puzzle library (For collages) that is Horizontal flip and vertical flip, can you please add that in uCrop also.

Thanks.

**Comment by Marina24** [comment]
Hi, @mitsubisu flipping image feature is not required for this library. You can fork and implement it if you want.
