### ISSUE TITLE
Picture loses color quality after cropping

### ISSUE THREAD

**Issue by JoaoBGusmao** [Yalantis/uCrop#617]
**Do you want to request a *feature* or report a *bug*?** Report a bug

**What is the current behavior?**
After crop, the new image come a little different from the original, talking about it's color

**What is the expected behavior?**
The cropped image should have the same colors as the original

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
  - Clone and build the sample provided with this repository
  - Load the original image i'm providing below
  - Note: Don't crop it directly without change something

You will notice the color difference between the original image and the cropped one

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**
Original image:
![IMG_0758](https://user-images.githubusercontent.com/5897900/73284620-9ca22b80-41d3-11ea-9f30-0b23a24d884b.jpg)

Cropping without any change:
![Screenshot_2020-01-28-13-59-01-337_com yalantis ucrop sample](https://user-images.githubusercontent.com/5897900/73287597-3c61b880-41d8-11ea-8ef3-367d488d6ea5.jpg)

After crop:
![Screenshot_2020-01-28-13-59-32-771_com yalantis ucrop sample](https://user-images.githubusercontent.com/5897900/73287695-64e9b280-41d8-11ea-97da-fe00724c7ae9.jpg)

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
I tested using the sample provided with this repository, version 2.2.4 and this is the current head: `https://github.com/Yalantis/uCrop/commit/76a9f06f13785de24e09b808713ca6155d2cf8e1`

**Comment by p1nkydev** [comment]
Hello, thanks for your feedback! As far as I can see there is no quality loose after crop more than 10% In sample app by default quality is 90/100. Have you changed it? Any way, we will check this out and try to resolve it.

**Comment by JoaoBGusmao** [comment]
Happens with quality 100 as well. Try with my picture. If you dont see any changes, I will try to upload it to another place. There is a specific color configuration that is lost after cropping
