### ISSUE TITLE
Request to implement image decoder for webp and bmp images

### ISSUE THREAD

**Issue by androidapkr** [Yalantis/uCrop#624]
First of all thanks a lot for providing image cropper the best library for android but its only support PNG and JPEG only, as growing android market we need some more changes on image cropping tool.

The library only crop PNG and JPEG images only but some other image type are also necessary that must be implemented to enhance future of the Ucrop.
Future enhancement are to implement WEBP, BMP and Vector Images( SVG ) crop. Recently Android new features introduce that handle this functionality called [ImageDecoder](https://developer.android.com/ndk/guides/image-decoder) that can be helpful to implement that task.
Please make some upgrade,

**Comment by p1nkydev** [comment]
Hello, thanks for using library and feedback! We will check this out and maybe include in some of next releases.
