### ISSUE TITLE
"You may want to add this to your PROGUARD config" <- Clarify?

### ISSUE THREAD

**Issue by AdityaAnand1** [Yalantis/uCrop#629]
"You may want to add this to your PROGUARD config"

Found this a little funny. Is it NEEDED or not? "You may want to" sounds like if the user feels like it, sure, otherwise without it would also work.

So which is it?

Also, can we make some better rules as the current ones essentially just disable proguard

```
-dontwarn com.yalantis.ucrop**
-keep class com.yalantis.ucrop** { *; }
-keep interface com.yalantis.ucrop** { *; }
```

Better rules should be more specific, as to what can be touched and what cannot be.

Also, by packaging as aar you can just bundle in proguard rules for the library. No need to bother the developers using it.

Just some ideas 😁

**Comment by p1nkydev** [comment]
Hello, thanks for your attention. It was added to readme.

**Comment by AdityaAnand1** [comment]
Hmmm
![image](https://user-images.githubusercontent.com/13274079/76983345-43e54880-6963-11ea-8e52-9484be45a032.png)

**Comment by p1nkydev** [comment]
@AdityaAnand1 Please, check out the readme :)

**Comment by AdityaAnand1** [comment]
Ok, so no change was actually made to the README in the past 6 months. Or perhaps you haven't pushed the branch yet?

This issue should remain open until fixed or addressed 😄

**Comment by p1nkydev** [comment]
@AdityaAnand1 I mean current rules are fine and they was already added to the readme.

**Comment by AdityaAnand1** [comment]
Well, okay then. I won't bother you again. Thanks for your cool repo.
