### ISSUE TITLE
Crash Java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

### ISSUE THREAD

**Issue by ekhacahya** [Yalantis/uCrop#63]
I use the TabLayout, then use this lib for cropping an image, but the application crashes (force close) on the grounds java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
can I know the reason? thanks
FYI I use this version compile 'com.yalantis:ucrop:1.3.2'

**Comment by westlinkin** [comment]
Same problem here

**Comment by shliama** [comment]
It would be helpful to see the code. I understand that you won't want to share your app code so maybe you can extract just this TabLayout Activity and share repo link?

**Comment by westlinkin** [comment]
Maybe it has something to do with AndroidStudio, after I delete the app from the device and run it, it works fine.

**Comment by shliama** [comment]
I believe I had similar error while using Instant Run.

**Comment by Aazam9** [comment]
i have same issue in tabLayout     
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v7/internal/widget/TintManager
