### ISSUE TITLE
Cropped PNG image has corrupted colors

### ISSUE THREAD

**Issue by meteorra** [Yalantis/uCrop#631]
**Do you want to request a *feature* or report a *bug*?**
BUG. The bug is reproduced on uCrop sample project too.

**What is the current behavior?**
Cropped PNG image has corrupted colors
**What is the expected behavior?**
Cropped image has original colors
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
1. Upload attached picture
2. Crop the picture
3. See results
**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**
Original file:
![original](https://user-images.githubusercontent.com/29917962/75963587-ccc9a200-5ed6-11ea-8c3c-11a8c3bd5302.png)
Cropped file:
![cropped](https://user-images.githubusercontent.com/29917962/75963635-e10d9f00-5ed6-11ea-8bb8-d3c7b30118ae.png)

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
uCrop version - reproduces on 2.2.2 - 2.2.4
minSdkVersion = 21
compileSdkVersion = 28
targetSdkVersion = 28

**Comment by p1nkydev** [comment]
Duplicate #559
