### ISSUE TITLE
Canvas: trying to draw too large bitmap.

### ISSUE THREAD

**Issue by beigirad** [Yalantis/uCrop#648]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I pass a high-res image (10MB) to UCropFragment it crashed.
try [this image](https://upload.wikimedia.org/wikipedia/commons/f/ff/Pizigani_1367_Chart_10MB.jpg)

**What is the expected behavior?**
I expect it starts editing the image.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
Just choose a high-res image and see the crash.

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**
```
    Process: xxxxx, PID: 9937
    java.lang.RuntimeException: Canvas: trying to draw too large(290841740bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:229)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:97)
        at com.yalantis.ucrop.util.FastBitmapDrawable.draw(FastBitmapDrawable.java:41)
```

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
2.2.4

**Comment by beigirad** [comment]
I checked the source of this crash:
in [DisplayListCanvas](https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-28/blob/809dd8b7822332cdbc68939d777eb70a6951908a/android/view/DisplayListCanvas.java) has defined:
```
    private static final int MAX_BITMAP_SIZE = 100 * 1024 * 1024; // 100 MB
```

and then in [this line](https://github.com/AndroidSDKSources/android-sdk-sources-for-api-level-28/blob/809dd8b7822332cdbc68939d777eb70a6951908a/android/view/DisplayListCanvas.java#L227) 

```
int bitmapSize = bitmap.getByteCount();
if (bitmapSize > MAX_BITMAP_SIZE) {
     throw new RuntimeException(
         "Canvas: trying to draw too large(" + bitmapSize + "bytes) bitmap.");
 }
```

**Comment by Jeff11** [comment]
Is it possible to have a hot fix version for this? 

Since more and more people have get those high megapixel camera phones, this is now our number one crash reason.

**Comment by yushaojian13** [comment]
I suggest a more proper [solution](https://github.com/Yalantis/uCrop/pull/662).

int bitmapSize = decodeSampledBitmap != null ? decodeSampledBitmap.getByteCount() : 0;
if (bitmapSize > MAX_BITMAP_SIZE) {
    options.inSampleSize *= 2;
    continue;
}

**Comment by cuiti** [comment]
Seems like this crash is getting more impactful as time goes by. Any news about a next release?

**Comment by dpreussler** [comment]
hotifx would really be appreciate before everyone forks this library

**Comment by KDederichs** [comment]
any news on this? It's a rather annoying issue....

**Comment by asifbd** [comment]
I think a pull request with the [fix](https://github.com/Yalantis/uCrop/pull/690) has been merged and available in latest version (2.2.6)

**Comment by artisticdevil** [comment]
> I suggest a more proper [solution](https://github.com/Yalantis/uCrop/pull/662), it won't crash and will continue to crop.
> 
> ```
> int bitmapSize = decodeSampledBitmap != null ? decodeSampledBitmap.getByteCount() : 0;
> if (bitmapSize > MAX_BITMAP_SIZE) {
>     options.inSampleSize *= 2;
>     continue;
> }
> ```

Where should this code be placed??

**Comment by beigirad** [comment]
This issue has fixed in version 2.2.6

**Comment by sauniksingh** [comment]
` java.lang.RuntimeException: Canvas: trying to draw too large(290841740bytes) bitmap.
        at android.graphics.BaseCanvas.nDrawBitmap(Native method)
   at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:192)
   at android.graphics.Canvas.drawBitmap(Canvas.java:1660)
    at com.yalantis.ucrop.util.FastBitmapDrawable.draw(FastBitmapDrawable.java:41)
    at android.widget.ImageView.onDraw(ImageView.java:1444)`

Still getting same issue if we're trying to crop image more than 4mb. in NOKIA 6.1, Android 10, & UCROP version 2.2.6

**Comment by heihitesh** [comment]
I am getting the same error, 
Also when I get to the UCrop screen to crop the image, If I press the back button. then also I get the same error
