### ISSUE TITLE
android q adaptation problem

### ISSUE THREAD

**Issue by 7449** [Yalantis/uCrop#658]
Is there any problem if you use content :: uri

`BitmapLoadTask.copyFile`

    try {
            inputStream = mContext.getContentResolver().openInputStream(inputUri);
            outputStream = new FileOutputStream(new File(outputUri.getPath()));
            if (inputStream == null) {
                throw new NullPointerException("InputStream for given input Uri is null");
            }

            byte buffer[] = new byte[1024];
            int length;
            while ((length = inputStream.read(buffer)) > 0) {
                outputStream.write(buffer, 0, length);
            }
        }

outputUri.getPath () does not support non-cached directories in Android10
If this is the case, can only use the cache directory in android10. 

If use 

`mContext.getContentResolver (). OpenOutPutStream`

 can output to the corresponding

` MediaStore.MediaColumns.RELATIVE_PATH`

Low versions can still use 

`MediaStore.MediaColumns.DATA`

The only thing that may need to be multi-processed is the problem of blank database data when canceling cropping

**Comment by SjAndy88** [comment]
I have same issue +1
