### ISSUE TITLE
rounded crop option

### ISSUE THREAD

**Issue by yesidlazaro** [Yalantis/uCrop#66]
FEATURE REQUEST : i thinks it will be useful ,adding rounded crop option with rounded overlay

**Comment by shliama** [comment]
There is rounded overlay already.
Use `Options.setOvalDimmedLayer()` method to enable it.

Image itself won't be cropped as oval because it's useless. If you have rectangle image you can represent it as oval (using libraries aka Picasso, Glide, Fresco etc).

**Comment by yesidlazaro** [comment]
@shliama thanks

**Comment by vanniktech** [comment]
This has now become `setCircleDimmedLayer(true)` right?

**Comment by krupasamuel** [comment]
yes

**Comment by ganeshchenniah** [comment]
I m using this option with flutter and i m using ucrop version 2.26 . still i m not able to get circular crop .
When i select circular crop it throws debug print as "I/BitmapCropTask: Should crop: false" . Is there any thing i m missing ?

**Comment by shliama** [comment]
As far as I remember, uCrop doesn't actually crop your image with oval shape (i.e. removing pixels around oval area) - this option is just for UI, so users can see how their photo will look like as circle avatar.
Just use `ClipOval` widget in Flutter to make your square image result look like circle.

Just read my 5 years old comment above:
> There is rounded overlay already.
> Use `Options.setOvalDimmedLayer()` method to enable it.
> 
> Image itself won't be cropped as oval because it's useless. If you have rectangle image you can represent it as oval (using libraries aka Picasso, Glide, Fresco etc).
