### ISSUE TITLE
Scale down limit with setOvalDimmedLayer(true) 

### ISSUE THREAD

**Issue by InI4** [Yalantis/uCrop#67]
uCrop is very nice. This might well be not a bug, but a feature request. 

I am using an oval dimmed layer, cause I actually only need the oval part of the created final image. I can filter out the oval data from the image create by uCrop which of course delivers a square. 

However I realize, that scaling down is limited by the restriction, that the whole displayed square grid needs to be filled with some image data. Since I do not care for the space between the oval and the square, I'd like to be able to scale images somewhat smaller, i.e. no image data in some of the corners, as long as there is image data everywhere in that oval ...

**Comment by shliama** [comment]
I don't think it's an essential feature for the library, however you can achieve that after image is cropped.
Try to use `Path` and `clipPath()` method on `Canvas` to clear redundant pixels and save resulting Bitmap.

**Comment by InI4** [comment]
Ah, I see it is closed, this is OK, if you mean to, but as I understand the argument it is invalid. 

Of course it cannot be done afterwards: 
- I only care about the circular part of the image, not the quadratic one.
- uCrop does not let me scale down the image as much as I want to, cause it ensures, that the crop quadrat is completely filled with image data. Yes, I mind the gap between the square and the oval.
- Ergo: Scaling down to a circular image with no data in corners is plain impossible with uCrop.

The workaround would be something like embed the inital image in one with a sufficiently large bezel image and then use uCrop on that newly created image. I really need to look, how hard it is to disable the "square is covered" feature in uCrop?!
