### ISSUE TITLE
Image Crop Size too small

### ISSUE THREAD

**Issue by niorgai** [Yalantis/uCrop#69]
Hello, I got some problem in crop size.
I have a 3120px * 3120px picture, and my phone's screenWidth is 1080px. 
So I set both crop width and crop height to 1080.
But I can't get a 3120 * 3120 picture at last, why?

**Comment by shliama** [comment]
Please check this: https://github.com/Yalantis/uCrop/issues/49

**Comment by niorgai** [comment]
Thanks for your reply, I had copy this project and change some method to fix this problem, hope you provide some native method to solve the problem of bitmap's memory.

**Comment by shliama** [comment]
Yep, hope to finish native crop next week :octocat:
