### ISSUE TITLE
Supporting Different Languages (Localization)

### ISSUE THREAD

**Issue by devflow** [Yalantis/uCrop#7]

**Comment by shliama** [comment]
There are three labels in the library that may be localized:
```
 <string name="ucrop_label_original">Original</string>
 <string name="ucrop_label_edit_photo">Edit Photo</string>
 <string name="ucrop_menu_next">Next</string>
```

If you want - you may create a pull-request with localized strings.xml and I'll add it.

Sample won't be localized because it's just a sample of library usage.

**Comment by devflow** [comment]
Yes, that's right. but what do you think about add localized string by developer from app-side?
maybe it's very helpful when use the uncommon languages, or  change ``ucrop_label_edit_photo`` to ``"Edit Profile Image"``.


thanks.

**Comment by shliama** [comment]
@devflow you can override any string resource (or dimen or color) in your app. To change title just add 

```<string name="ucrop_label_edit_photo">Your custom title</string>```

in your app strings.xml file.

**Comment by blntylmn** [comment]
Note for anyone who read this topic.
There are 6 strings you can translate if you wish/want.
Just add these lines to your own projects app/src/main/res/values=> strings.xml
`<string name="ucrop_label_original">Original</string>`
`<string name="ucrop_label_edit_photo">Edit Photo</string>`
`<string name="ucrop_menu_next">Next</string>`
`<string name="ucrop_rotate">Rotate</string>`
`<string name="ucrop_scale">Scale</string>`
`<string name="ucrop_crop">Crop</string>`
and translate whatever language you need.

**Comment by mahyari** [comment]
> Note for anyone who read this topic.
> There are 6 strings you can translate if you wish/want.
> Just add these lines to your own projects app/src/main/res/values=> strings.xml
> `<string name="ucrop_label_original">Original</string>`
> `<string name="ucrop_label_edit_photo">Edit Photo</string>`
> `<string name="ucrop_menu_next">Next</string>`
> `<string name="ucrop_rotate">Rotate</string>`
> `<string name="ucrop_scale">Scale</string>`
> `<string name="ucrop_crop">Crop</string>`
> and translate whatever language you need.

It works for English strings.xml but not work for unsupported language like Persian! It shows original label `Edit Photo` on it.

**Comment by muhammad-hamza-shahid** [comment]
> > Note for anyone who read this topic.
> > There are 6 strings you can translate if you wish/want.
> > Just add these lines to your own projects app/src/main/res/values=> strings.xml
> > `<string name="ucrop_label_original">Original</string>`
> > `<string name="ucrop_label_edit_photo">Edit Photo</string>`
> > `<string name="ucrop_menu_next">Next</string>`
> > `<string name="ucrop_rotate">Rotate</string>`
> > `<string name="ucrop_scale">Scale</string>`
> > `<string name="ucrop_crop">Crop</string>`
> > and translate whatever language you need.
> 
> It works for English strings.xml but not work for unsupported language like Persian! It shows original label `Edit Photo` on it.

I am also working on same issue, it works great if I add these resources in english(default) string file, but when I paste same resources in other language files it picks its default string value from supported language and shows that text.

@shliama 
@blntylmn
