### ISSUE TITLE
java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from Uri

### ISSUE THREAD

**Issue by kirankumarkyasa** [Yalantis/uCrop#70]
When an Image taken using Camera everythign works fine, when an image is selected from Gallery it throws this Exception

**Comment by shliama** [comment]
Well, it seems you doing something wrong. Please try to use code from the sample, it works properly for me.

**Comment by raylee4204** [comment]
This consistently happens on my app as well.

<img width="994" alt="screen shot 2016-05-02 at 10 47 33 am" src="https://cloud.githubusercontent.com/assets/2085389/14957418/4c28f31a-1053-11e6-916e-7666e3ad64d1.png">

**Comment by ionutbejan** [comment]
Same thing here for me, but opposite. Doesn't work from Camera, because (my guess) of FileProvider (more precisely the location where I save the picture from camera)
