### ISSUE TITLE
HEIC/HEIF Images Failed to Recognise File Format with 2.2.6-native

### ISSUE THREAD

**Issue by pishangujeniya** [Yalantis/uCrop#706]
**Bug Report**

**What is the current behavior?**
- Throws Exception After Cropping
```java

E/SampleActivity: handleCropError: 
    java.io.IOException: [instance(0,0,0,0,0x0,non-shared)] CImg<unsigned char>::load(): Failed to recognize format of file '/data/user/0/com.yalantis.ucrop.sample/cache/SampleCropImage.png'.
        at com.yalantis.ucrop.task.BitmapCropTask.cropCImg(Native Method)
        at com.yalantis.ucrop.task.BitmapCropTask.crop(BitmapCropTask.java:143)
        at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:92)
        at com.yalantis.ucrop.task.BitmapCropTask.doInBackground(BitmapCropTask.java:31)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

```

**What is the expected behavior?**
- Should work normally.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
- With Samsung Galaxy Note 10 Lite, and in Camera Settings > Save Options > Turnon HEIC images
- Capture some and try to load it by Pick from Gallery Option from Sample uCrop App

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
- Version 2.2.6-native
- Tried on Android 29 API

> Works Perfect with 2.2.6 but does not work with 2.2.6-native

**Comment by Sub-Zero-1** [comment]
Any news on this? Have you solved it, as I have the same issue.

**Comment by pishangujeniya** [comment]
> Any news on this? Have you solved it, as I have the same issue?

Works Perfect with 2.2.6

Works Perfect with `implementation 'io.fotoapparat:fotoapparat:2.7.0'`

**Comment by Sub-Zero-1** [comment]
> > Any news on this? Have you solved it, as I have the same issue?
> 
> Works Perfect with 2.2.6
> 
> Works Perfect with `implementation 'io.fotoapparat:fotoapparat:2.7.0'`

That is not a solution. Working with the non-native version will decrease the cropped image resolution by estimated 50% and is therefore not applicable for me and my customers.
Fotoapparat is not a solution for this library issue at all.

**Comment by pishangujeniya** [comment]
> Working with the non-native version will decrease the cropped image resolution by estimated 50%

Who said this?

I am not facing any resolution reduction using non-native version.

**Comment by reallyMy** [comment]
I also encountered this problem，because this library does not currently support webp images.
My current solution is:
**1.Get the picture type first**
`public static String getImageType(String imagePath){
        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inJustDecodeBounds = true;
        BitmapFactory.decodeFile(imagePath, options);
        return options.outMimeType;
    }`
**2.If the picture is not in PNG format or JPG format，Store locally and convert to JPG format**
`public static String getBitmapNewPath(Context context,String imagePath){
        Bitmap bitmap = BitmapFactory.decodeFile(imagePath);
        return saveBitmap("webpImg",bitmap,context);
    }`
`private static String saveBitmap(String name, Bitmap bm, Context mContext) {
        String targetPath = mContext.getExternalFilesDir(null).getAbsolutePath();
        LogUtils.i("Save Path=" + targetPath);
        File file = new File(targetPath);
        if(!file.exists()) {
            boolean mkdirs = file.mkdirs();
            if(!mkdirs)
                return "";
        }
        File saveFile = new File(targetPath, name);
        try {
            FileOutputStream saveImgOut = new FileOutputStream(saveFile);
            bm.compress(Bitmap.CompressFormat.JPEG, 100, saveImgOut);
            saveImgOut.flush();
            saveImgOut.close();
            LogUtils.i("The picture is save to your phone!");
            return saveFile.getAbsolutePath();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
        return "";

    }`
**3.Then you can use the clipping function**
`String imageType = ImageUtils.getImageType(imgPath);
            if(!imageType.equals("image/png") && !imageType.equals("image/jpeg")){
                imgPath = ImageUtils.getBitmapNewPath(this, imgPath);
                if(TextUtils.isEmpty(imgPath))
                    imgPath = getImgPath();
            }
            Uri uri = Uri.fromFile(new File(imgPath));
            startCrop(uri);`
