### ISSUE TITLE
When compile, "com.android.ide.common.process.ProcessException"

### ISSUE THREAD

**Issue by kensupernova** [Yalantis/uCrop#71]
I am using android studio on osx. I followed the example code to include ucrop in my app. But when I compile, I always met this error:
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by shliama** [comment]
Unfortunately it says nothing to me. Can you run another projects with same gradle plugin version?

**Comment by jeevitharoyapathi** [comment]
Even I am facing same issue! I guess we are using jdk1.8.0 and Ucrop might be using jdk 1.7
