### ISSUE TITLE
Support changes

### ISSUE THREAD

**Issue by iRafal** [Yalantis/uCrop#713]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Library notifies about result via startActivtiyForResult/onActivityResult at Activity/Fragment.

**What is the expected behavior?**
Please, add support of new api for requesting activity result, which will be released at new version (currently is: 1.3.0-beta01) of "androidx.fragment:fragment-ktx" (https://developer.android.com/jetpack/androidx/releases/fragment). 

New ktx api example:
```
//Definition
private val uCropLauncher = registerForActivityResult(StartActivityForResult()) {
}
uCropLauncher.launch( /*uCropIntent*/ )
```

More details here: https://developer.android.com/training/basics/intents/result

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**
Currently version is 2.2.5.

**Comment by bmarty** [comment]
FTR this is not in the README, but 2.2.6 is available :)

**Comment by bmarty** [comment]
@iRafal there is nothing to do on the uCrop library to support the new way to start Activity for result. uCrop already exposes a `getIntent()` method, so you can use it instead of using any of the `start()` methods. I did the change in https://github.com/vector-im/element-android/pull/2285, if you want to have a look.

**Comment by iRafal** [comment]
Hi @bmarty. 
Thx for your update about new version release. 
Also thx for reply, I didn't mention this method. I've checked, it works fine as expected. 
Hope this discussion will help other developers with updating their projects to support new ktx release(s).

**Comment by Tanima-Sultana** [comment]
I solved this issue replacing the onActivityResult by using registerForActivityResult. There's no need to have multiple request code.
Code in CroppedActivity 

  val croppedIntent = fileUri?.let {
            UCrop.of(it,Uri.fromFile(File(cacheDir,destinationUri)))
                .withOptions(options)
                .withAspectRatio(0F, 0F)
                .useSourceImageAspectRatio()
                .withMaxResultSize(2000,2000)
                .getIntent(this)
        }

it returns the cropped intent.


val cropLauncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()){ result1 ->
            if( result1.resultCode == Activity.RESULT_OK ){
                val resultUri = result1.data?.let { UCrop.getOutput(it) }
                val resultIntent = Intent()
                resultIntent.putExtra("RESULT","$resultUri")
                setResult(-1,resultIntent)
                finish()
            }else if(result1.resultCode == UCrop.RESULT_ERROR){
                val cropError = result1.data?.let { UCrop.getError(it) }
            }
        }

it is for having the result from activity

        cropLauncher.launch(croppedIntent)
here I have passed the intent through launch.

In MainActivity I have handled the situation as same as CroppedActivity

cropImageLuncher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()){
            if(it.resultCode == Activity.RESULT_OK ){
                val result = it.data?.getStringExtra("RESULT")
                var resultUri:Uri? = null
                if (result != null){
                    resultUri = Uri.parse(result)
                }

                croppedImage?.setImageURI(resultUri)
            }
        }


Happy Coding :D
