### ISSUE TITLE
Jcenter shutdown

### ISSUE THREAD

**Issue by PatrinAV** [Yalantis/uCrop#748]
Jcenter is shutting down in near future(February 1st 2022). https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ Are ucop ready for this?

**Comment by iogui** [comment]
uCrop realeases are on jitpack.io. I think jcenter is not been used.

**Comment by DeMoss15** [comment]
@iogui is right, the library is released via jitpack, so you can remove jcenter form your project's repositories. Also, jcenter will be removed from the readme in one of upcoming PRs.
