### ISSUE TITLE
Missing 2.2.7-native variant

### ISSUE THREAD

**Issue by jrgonzalezg** [Yalantis/uCrop#763]
**What is the current behavior?**

2.2.7 version was released recently but there is no 2.2.7-native tag.

**What is the expected behavior?**

Is the native variant no longer provided / recommended or is it just pending to be tagged / available on JitPack? Also while the new release appears on https://github.com/Yalantis/uCrop/releases it is not mentioned / updated on README.

**Comment by fabio-blanco** [comment]
Android 10 and SAF support is not available for the native version. More research is needed to understand whether it is feasible to implement this functionality for the native version.
