### ISSUE TITLE
at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:102)    NullPointerException

### ISSUE THREAD

**Issue by 237177220** [Yalantis/uCrop#769]
**Do you want to request a *feature* or report a *bug*?**
a bug
**What is the current behavior?**
app cashed and dead

**What is the expected behavior?**
run nomal 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
when i selected a picture to crop ,when i choose completed crop the bug appeared

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

the version of uCrop is 2.2.6. android api is 29

**Comment by dmitriy1morozov** [comment]
There are too few details regarding the issue you faced. If it still exists please provide the image you are trying to crop and the stack trace output.
