### ISSUE TITLE
Portrait aspect 2x3 ratio

### ISSUE THREAD

**Issue by ninoid** [Yalantis/uCrop#778]
I am trying to set portrait crop dimensions to aspect ratio 2x3. Is this possible? I need to have options to choose from 3x2 and 2x3 aspect ratio.

**Comment by dmitriy1morozov** [comment]
@ninoid , you may toggle aspect ratios by simply clicking the aspect ratio on custom TextView. So clicking 3:2 will toggle to 2:3, the same goes for 16:9 -> 9:16 and so on.

**Comment by fqz100** [comment]
Did you solve it?
