### ISSUE TITLE
not working on 4.4

### ISSUE THREAD

**Issue by hoangvandan** [Yalantis/uCrop#78]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.vn.uvn/com.yalantis.ucrop.UCropActivity}: android.view.InflateException: Binary XML file line #43: Error inflating class com.yalantis.ucrop.view.UCropView
Please fix error

**Comment by shliama** [comment]
Cannot reproduce that. Do you face that error if running the sample?
