### ISSUE TITLE
hello 你为什么这么牛

### ISSUE THREAD

**Issue by codeceo-net** [Yalantis/uCrop#789]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**What is the expected behavior?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

**Please attach any *image files*, *URL* and `stack trace` that can be used to reproduce the *bug*.**

**Which versions of uCrop, and which Android API versions are affected by this issue? Did this work in previous versions of uCrop?**

**Comment by dmitriy1morozov** [comment]
Hello. We are sorry that you faced a problem with the library. Please supply us with the details about the issue using the aforementioned format.
