### ISSUE TITLE
api level 14?

### ISSUE THREAD

**Issue by nrazon** [Yalantis/uCrop#79]
You changed minSDK to support ICS 4.0 but ICS sdk levet starts with 14. 
"Updated minSdkVersion to Android ICS 4.0 (no reason to support couple percents of old phones)."

I think you set minSDK of library to 15. which ic 4.03+ 
Still too many 4.0 - 4.02 devices. (https://en.wikipedia.org/wiki/Android_version_history)

Please take minSDK to 14. 

error:
Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library [com.yalantis:ucrop:1.4.0]

**Comment by shliama** [comment]
Yeah, I guess I'll do that. Always using 15 for ICS because 14 has really couple devices out there. It's even marked as obsolete in SDK manager because there are almost no devices using this API. Most of the devices running Android 4.0 version are actually running 4.0.3 or 4.0.4.

**Comment by shliama** [comment]
Here you go, try version 1.4.1
