### ISSUE TITLE
Change theme color

### ISSUE THREAD

**Issue by lopspower** [Yalantis/uCrop#8]
It's possible to change the color **orange #FF6E40** (`ucrop_color_toolbar` and `ucrop_color_widget_active`) with the `colorPrimary` in your theme?
And allow to do that to adapt the style to the application :

```xml
<activity
    android:name="com.yalantis.ucrop.UCropActivity"
    android:screenOrientation="portrait"
    android:theme="@style/AppTheme"/>
```

**Comment by longtaoge** [comment]
how to change the crop  table  line ‘ color ?  eg: i lide a green  alpha 0.8  table line like Edmodo Cropper

**Comment by shliama** [comment]
@lopspower Currently you can override library colors just specifying colors with the same names in your colors.xml file.
For example:

```<color name="ucrop_color_toolbar">#000000</color>```

will make toolbar color black if specified inside you application colors.xml file. In fact you can override almost all colors in the library that way, but icons at the bottom (they are just png files for now).
We plan to make styling better in future updates.

@longtaoge 
This functionality will be added in the next update. ETA tomorrow.

**Comment by khaykov** [comment]
You can't override toolbar text color. It's defined using ```@android:color/white"```

**Comment by shliama** [comment]
@khaykov nice catch :+1: will fix those asap

**Comment by shliama** [comment]
Fixed in v1.1.2

**Comment by tvaamorim** [comment]
Is will be possible to change the toolbar and statusbar dynamically, with Options?

**Comment by shliama** [comment]
Yes it will be added in future update.

**Comment by timkoers** [comment]
I have created a pull request that adds this functionality

**Comment by channae** [comment]
is changing status bar color and icon colors is possible now?

**Comment by theshivamlko** [comment]
All above are not working, How to change color of toolbar and icon,

**Comment by majurageerthan** [comment]
<color name="ucrop_color_widget_background">#000000</color>

it is enough

**Comment by Balarutsav** [comment]
You can override colors and it will change 

    <color name="ucrop_color_statusbar">@color/colorPrimaryDark</color>
    <color name="ucrop_color_toolbar">@color/colorPrimaryDark</color>
    <color name="ucrop_color_toolbar_widget">@color/white</color>

 <color name="ucrop_color_blaze_orange">#FFFFFF</color>
