### ISSUE TITLE
Is it possible to crop the image without maintaining a fixed aspect ratio?

### ISSUE THREAD

**Issue by Mohaymin** [Yalantis/uCrop#801]
I am trying to allow users crop their image without maintaining any aspect ratio in my android application.

It should look something like this:

![demo](https://user-images.githubusercontent.com/29138411/147629105-8d339ef9-da30-42ea-b7ef-4a7f55b78d12.gif)

How can I achieve this goal using this library?

**Comment by Huangqiankun** [comment]
In the updateCropViewRect method of the OverlayView class, update


        boolean changeHeight = mTempRect.height() >= mCropRectMinSize;
        boolean changeWidth = mTempRect.width() >= mCropRectMinSize;

        // ------------------start------------------
        float mTempRectWidth = Math.abs(mTempRect.right - mTempRect.left);
        float mTempRectHeight = Math.abs(mTempRect.bottom - mTempRect.top);
        float diff = Math.min(mTempRectWidth, mTempRectHeight);
        mCropViewRect.set(mTempRect.left, mTempRect.top, mTempRect.left + diff, mTempRect.top + (diff * mTargetAspectRatio));

//        mCropViewRect.set(
//                changeWidth ? mTempRect.left : mCropViewRect.left,
//                changeHeight ? mTempRect.top : mCropViewRect.top,
//                changeWidth ? mTempRect.left : mCropViewRect.right,
//                changeHeight ? mTempRect.bottom : mCropViewRect.bottom);
        //-------------------end------------------------------
        if (changeHeight || changeWidth) {
            updateGridPoints();
            postInvalidate();
        }

**Comment by Huangqiankun** [comment]
In the updateCropViewRect method of the OverlayView class, update

        boolean changeHeight = mTempRect.height() >= mCropRectMinSize;
        boolean changeWidth = mTempRect.width() >= mCropRectMinSize;

        // -------------update-----start------------------
        float mTempRectWidth = Math.abs(mTempRect.right - mTempRect.left);
        float mTempRectHeight = Math.abs(mTempRect.bottom - mTempRect.top);
        float diff = Math.min(mTempRectWidth, mTempRectHeight);
        mCropViewRect.set(mTempRect.left, mTempRect.top, mTempRect.left + diff, mTempRect.top + (diff * mTargetAspectRatio));

        //mCropViewRect.set(
        //        changeWidth ? mTempRect.left : mCropViewRect.left,
        //        changeHeight ? mTempRect.top : mCropViewRect.top,
        //        changeWidth ? mTempRect.left : mCropViewRect.right,
        //        changeHeight ? mTempRect.bottom : mCropViewRect.bottom);
        //----------update---------end------------------------------
        if (changeHeight || changeWidth) {
            updateGridPoints();
            postInvalidate();
        }

**Comment by molpoo** [comment]
I am also interested in this feature !

**Comment by dmitriy1morozov** [comment]
Hello, @Mohaymin . You may use one of the public methods in OverlayView.java to enable freestyle crop and freely drag corners without a fixed aspect ratio. Please check the following method:
public void setFreestyleCropEnabled(boolean freestyleCropEnabled) {

Check the following screencast from the sample app. Is that what you were looking for?
![FreeStyleCrop](https://user-images.githubusercontent.com/17425376/150483411-8e097d29-ac4e-4111-aafb-7f54ffde3b0c.gif)

**Comment by Mohaymin** [comment]
@dmitriy1morozov yes! thanks for your response.
