### ISSUE TITLE
Access mCropViewRect

### ISSUE THREAD

**Issue by vxhviet** [Yalantis/uCrop#81]
Hi @shliama, thank you again for your awesome lib,

In my layout I would like to place the `HorizontalProgressWheelView` directly below the Overlay crop rectangle and it should dynamically update to a new position when the crop ratio change (the Overlay crop rectangle becomes bigger or smaller).

In order to do that I would need to get the position of the crop rectangle which mean I need to access the `mCropViewRect ` in `OverlayView`. Would you mind provide a quick `getter()` for this object?

Thank you so much for your time.

Edit: Currently I use reflection to access it. It's not elegant but it get the job done.

**Comment by shliama** [comment]
Answered in #82
