### ISSUE TITLE
How to get the RectF of the crop bounds when activity first start up?

### ISSUE THREAD

**Issue by vxhviet** [Yalantis/uCrop#82]
Dear @shliama,

I' currently trying to attach my own rotating wheel below the Crop Bounds. I've managed to do it in the `onClick` event of the `cropAspectRatioView` like this:

```java
private void setupAspectRatioWidget() {

        // Set the colors before the default item is selected
        ...

        for (ViewGroup cropAspectRatioView : mCropAspectRatioViews) {
            cropAspectRatioView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                    mGestureCropImageView.setTargetAspectRatio(
                            ((AspectRatioTextView) ((ViewGroup) v).getChildAt(0)).getAspectRatio(v.isSelected()));
                    
                    mGestureCropImageView.setImageToWrapCropBounds();
                    if (!v.isSelected()) {
                        for (ViewGroup cropAspectRatioView : mCropAspectRatioViews) {
                            cropAspectRatioView.setSelected(cropAspectRatioView == v);
                        }
                    }

                    //TODO: update protractor position here
                   mProtractorWheelView.setY((float)mUCropView.getHeight()/2 + mRectF.height()/2);
                }
            });
        }
    }
```

the `mRectF` is the private `mCropViewRect` retrieved from `OverlayView` using reflection. My wheel view update nicely when the ratio get changed.

However the problem is when I try to position my wheel view below the crop bound when the activity first start up, the wheel is place at wrong position. If I understand your code correctly, you only call `mViewOverlay.postInvalidate(); `:

```java
public UCropView(Context context, AttributeSet attrs, int defStyleAttr) {
        super(context, attrs, defStyleAttr);

        ...

        mGestureCropImageView.setCropBoundsChangeListener(new CropImageView.CropBoundsChangeListener() {
            @Override
            public void onCropBoundsChangedRotate(float cropRatio) {
                if (mViewOverlay != null) {
                    mViewOverlay.setTargetAspectRatio(cropRatio);
                    mViewOverlay.postInvalidate(); 
                }
            }
        });

        ...
    }
```

when there's a ratio change. And as such when the activity first start, when I try to get  `mCropViewRect`, it still retain the old value. Is there anyway to get the updated  `mCropViewRect` value when everything are fully initialized?

Thank you so much for your time.

**Comment by vxhviet** [comment]
I would like to add, I solve this by `addOnGlobalLayoutListener()` to the `mOverlayView` object in `initiateRootViews()`. Something like this:

```java
//init position
        mOverlayView.getViewTreeObserver().addOnGlobalLayoutListener(new ViewTreeObserver.OnGlobalLayoutListener() {
            @Override
            public void onGlobalLayout() {
                mRectF = getOverlayViewRectF();
                //do your thing
            }
        });
```

Hope this help someone,

**Comment by shliama** [comment]
Yes, I read #81 and this issues, and I'll try to provide more methods and callbacks in the next update so you won't need to use reflection etc.

**Comment by vxhviet** [comment]
Awesome, thanks you for your time.

**Comment by shliama** [comment]
Please try version 1.5.0.
I've added getter for `mCropViewRect ` in `OverlayView`, and also revised logic (because now uCrop supports freestyle crop) so `OverlayViewChangeListener#onCropRectUpdated(RectF cropRect)` will always update you with the current crop rectangle.

**Comment by wzgl5533** [comment]
How can I get current RectF of the cropView?or  current instace of OverlayView?
