### ISSUE TITLE
Using v1.4.1, could not build because of an error.

### ISSUE THREAD

**Issue by AhmadMuzakkir** [Yalantis/uCrop#84]
Hi,

When using v1.4.1, I received an error when building the project.

The error is "Error: Width (0) and height (0) cannot be < = 0." on file res/drawable/ucrop_vector_loader.xml.

I'm using support library version v23.3.0.

![image](https://cloud.githubusercontent.com/assets/10398517/14522164/d9bbc646-025f-11e6-9adb-b5355627572b.png)

**Comment by AhmadMuzakkir** [comment]
I found out the problem. I forgot to add the necessary attributes on the build.gradle.

**Comment by Rich2k** [comment]
What attributes are those as I've got the same issue

**Comment by shliama** [comment]
I guess you should define vector support:
http://android-developers.blogspot.com/2016/02/android-support-library-232.html

**Comment by AhmadMuzakkir** [comment]
@Rich2k The vector attributes.

If you are using gradle plugin version 1.5:

` // Gradle Plugin 1.5  
 android {  
   defaultConfig {  
     generatedDensities = []  
  }  

  // This is handled for you by the 2.0+ Gradle Plugin  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
 }  `

If you are using gradle plugin 2.0

`// Gradle Plugin 2.0+  
 android {  
   defaultConfig {  
     vectorDrawables.useSupportLibrary = true  
    }  
 }  `

**Comment by tejalpandya** [comment]
Hello, i have also this problem. how could i resolve this ?

**Comment by AhmadMuzakkir** [comment]
@tejalpandya 

You need to add certain attributes on your app's build.gradle.

```
// Gradle Plugin 2.0+  
 android {  
   defaultConfig {  
     vectorDrawables.useSupportLibrary = true  
    }  
 }  
```
or

```
// Gradle Plugin 1.5  
 android {  
   defaultConfig {  
     generatedDensities = []  
  }  

  // This is handled for you by the 2.0+ Gradle Plugin  
  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  }  
 } 
```

Ref: http://android-developers.blogspot.my/2016/02/android-support-library-232.html
