### ISSUE TITLE
Mutate() is not supported for older platform

### ISSUE THREAD

**Issue by AhmadVatani** [Yalantis/uCrop#85]
E/UCropActivity: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices

i spend one day complete for fix this bug...
i also add theme to UCropActivity in manifest like below but not working:
   ```
<activity
            android:name="com.yalantis.ucrop.UCropActivity"
            android:screenOrientation="portrait"
            android:theme="@style/Theme.AppCompat.Light.NoActionBar" />
```

**Comment by shliama** [comment]
Just add "ucrop_color_toolbar_widget" to your colors.xml with prefered color.

**Comment by voidstarfire** [comment]
Done the following in colors.xml

```
<!-- UCrop colors -->
<color tools:override="true" name="ucrop_color_toolbar_widget">@color/primary</color>
```

Doesn't work, get the following error

`E/UCropActivity: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices`

Why isn't this defaulted to something? Or detected as an older version??
