### ISSUE TITLE
Image doesn't wrap crop bounds on resetRotation()

### ISSUE THREAD

**Issue by vxhviet** [Yalantis/uCrop#86]
Dear @shliama,

Just a quick notice, it seem like in your demo app, the reset button on Rotate widget doesn't re-scale the image to fit the crop bounds. Thus this method `mGestureCropImageView.setImageToWrapCropBounds();` in:

```java
UCropActivty 

private void resetRotation() {
        mGestureCropImageView.postRotate(-mGestureCropImageView.getCurrentAngle());
        mGestureCropImageView.setImageToWrapCropBounds();
    }
```

doesn't do anything.

**Comment by shliama** [comment]
It's working as intended. If an image doesn't fit crop bounds after rotation - it'll scale an image, or do nothing otherwise.
