### ISSUE TITLE
When I was in use, found this bug

### ISSUE THREAD

**Issue by timmy008** [Yalantis/uCrop#87]
When I was in use, found this bug.Renderings are as follows:

![before_cutting](https://cloud.githubusercontent.com/assets/17633324/14664739/288cd87e-0700-11e6-9d36-1d4d231a4607.jpeg)

![after_the_cut](https://cloud.githubusercontent.com/assets/17633324/14664735/22ce477e-0700-11e6-9b98-371c13431a76.jpeg)

I present a solution:
```
public void setImageToWrapCropBounds(boolean animate, boolean save) {
	if (!isImageWrapCropBounds()) {
		...
		...
		if (willImageWrapCropBoundsAfterTranslate) {
			final float[] imageIndents = calculateImageIndents();
			deltaX = -(imageIndents[0] + imageIndents[2]);
			deltaY = -(imageIndents[1] + imageIndents[3]);
		} else {
			// A temporary solution
			if (save) {
				Logger.d(TAG, "被裁剪的图片偏出裁剪框，这是保存过程");
				final float[] imageIndents = calculateImageIndents();
				deltaX = -(imageIndents[0] + imageIndents[2]);
				deltaY = -(imageIndents[1] + imageIndents[3]);
			}
			RectF tempCropRect = new RectF(mCropRect);
			mTempMatrix.reset();
			mTempMatrix.setRotate(getCurrentAngle());
			mTempMatrix.mapRect(tempCropRect);

			final float[] currentImageSides = RectUtils.getRectSidesFromCorners(mCurrentImageCorners);

			deltaScale = Math.max(tempCropRect.width() / currentImageSides[0], tempCropRect.height() / currentImageSides[1]);
			// Ugly but there are always couple pixels that want to hide because of all these calculations
			deltaScale *= 1.01;
			deltaScale = deltaScale * currentScale - currentScale;

		}
		...
		...
	}
}
```

**Comment by shliama** [comment]
Thanks for the report.
I'll work on it asap.

**Comment by vxhviet** [comment]
I can't replicate this issue. So what is the exact steps that cause this @timmy008 ?

**Comment by shliama** [comment]
Try to reproduce it with new version 1.5.0.

**Comment by vxhviet** [comment]
Ah thats why, I still use version 1.4.1.
So has this bug been fixed yet?

**Comment by shliama** [comment]
I was not able to reproduce it, but in version 1.5.0 large part of logic was revised, therefore I think this bug might be fixed too.

**Comment by vxhviet** [comment]
I mean in version 1.4.1, I can't reproduce this issue. Thats why I ask @timmy008 the exact steps that cause this issue.

**Comment by timmy008** [comment]
@vxhviet  I downloaded the making of the above project, and then compile the installation to appear the problem
