### ISSUE TITLE
How to use UCrop directly in my ImageView?

### ISSUE THREAD

**Issue by Sam-kh** [Yalantis/uCrop#88]
I need to use uCrop in an ImageView and use it's gestures to crop the image. Just like Instagram and Telegram.

**Comment by shliama** [comment]
Just use GestureCropImageView class as your ImageView

**Comment by Sam-kh** [comment]
What about overlay view?

**Comment by shliama** [comment]
Then use UCropView class

**Comment by Sam-kh** [comment]
The ImageView gets so small when I use UCopView

**Comment by shliama** [comment]
Excuse me, but I'm here not to give you programming lessons.
If you have found a bug - please create issue for it, otherwise - at least describe your problem with more details, because "The ImageView gets so small when I use UCopView" is hardly enough.

**Comment by Sam-kh** [comment]
Sorry man, you're right. Thanks for your help.

**Comment by Sam-kh** [comment]
Since UCropView extends FrameLayout, not ImageView it doesn't have adjustViewBounds. I used `uCropView.getCropImageView().setAdjustViewBounds(true)` to fix the problem.

**Comment by shliama** [comment]
Glad you've found a way to fix it 👍
