### ISSUE TITLE
outofmemrory

### ISSUE THREAD

**Issue by jayronlou** [Yalantis/uCrop#89]
BitmapCropTask 
crop方法内的这一行
mViewBitmap = Bitmap.createBitmap(mViewBitmap, left, top, width, height);
很容易引起内存崩溃

**Comment by shliama** [comment]
What image do you try to crop?
Anyway, this should be fixed in version 2.0

**Comment by jayronlou** [comment]
big image, about 3~5M

**Comment by shliama** [comment]
@jayronlou Please try version 2.0 and comment if there are any issues :octocat:
