### ISSUE TITLE
Can I specify a list of ratio to allow users to select?

### ISSUE THREAD

**Issue by ben-zhong** [Yalantis/uCrop#90]
One of the key features of uCrop is to let users choose crop ratio dynamically.
Can I specify a list of ratio to allow users to select in the cropping activity (the same as default ratios)?

**Comment by shliama** [comment]
@ben-zhong hey and thanks for feature request 👍 
Yes, I think I'll be able to add that in future update, but I'm not sure if I have time this week.

**Comment by shliama** [comment]
@ben-zhong please use library version 2.1.0 and `Ucrop.Options.setAspectRatioOptions` method :octocat:
