### ISSUE TITLE
Override color value

### ISSUE THREAD

**Issue by mugurtomitajr** [Yalantis/uCrop#92]
I am receiving this error: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices. I'm running on Android 5.0 (21). I did override the color value but still not working.

**Comment by tjouin** [comment]
Same issue here. 5.1 (22)

**Comment by shliama** [comment]
I've answered in the issue #95
