### ISSUE TITLE
UCrop.of(sourceUri, destinationUri)

### ISSUE THREAD

**Issue by PereAlmendro** [Yalantis/uCrop#94]
the result of the crop is destination uri?, what is destination uri ? it's needed to start ucrop but 
i dont know whats his job... thanks!
where is the result of the crop ? i try to show in a imageview the result and the destinationUri or the uri from UCrop.getouput shows nothing

**Comment by shliama** [comment]
Hi, what about looking at the sample? I'm sure it's clear enough.
P.S. sourceUri (it's for your original image "source"), and destinationUri (it's where you want to save the result " destination ").

**Comment by PereAlmendro** [comment]
ohh i looked at it but it goes from one place to another and i get lost, well i think i got it thank you for your response

**Comment by kaustav07** [comment]
what if i dont want to save the image anywhere but instead i want the cropped image data in Stram,byte etc. so that i can use that data later to create a file or save it in server and retrieve whenever i need?

**Comment by KucherenkoIhor** [comment]
@kaustav07 uCrop uses native function that doesn't provide this opportunity. You can get InputStream from destination file and delete it after this.
