### ISSUE TITLE
Library won't work in devices pre lollipop.

### ISSUE THREAD

**Issue by voidstarfire** [Yalantis/uCrop#95]
Related https://github.com/Yalantis/uCrop/issues/85

Done the following in colors.xml

<color tools:override="true" name="ucrop_color_toolbar_widget">@color/primary</color>
Doesn't work, get the following error

E/UCropActivity: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices

Why isn't this defaulted to something? Or detected as an older version??

**Comment by shliama** [comment]
Library works for me for all supported platforms.

If you override color in your colors.xml - it will be used by the library (this is how resource works in Android). But remember - if you override colors - you do not need to call `options.setToolbarWidgetColor();` because you have already overridden default uCrop color.

I think I'll revise this "error" message logic in next update, to make it more clear.

P.S. "Library won't work in devices pre lollipop." - what's the stacktrace for crash?

**Comment by voidstarfire** [comment]
```
04-25 12:32:02.739 13284-13284/com.company.companyapp E/TransformImageView: onFailure: setImageUri
                                                                                       java.lang.IllegalArgumentException: Bounds for bitmap could not be retrieved from Uri
                                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:105)
                                                                                           at com.yalantis.ucrop.task.BitmapLoadTask.doInBackground(BitmapLoadTask.java:35)
                                                                                           at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                           at java.lang.Thread.run(Thread.java:818)
04-25 12:32:02.755 13284-13284/com.company.companyapp E/UCropActivity: Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices
```

**Comment by voidstarfire** [comment]
The Uri works in other crop libraries.

**Comment by voidstarfire** [comment]
My bad. Uri was resolving at the wrong destination some werid Uri issues in Android. Thanks for the awesome library.

**Comment by voidstarfire** [comment]
I'm still getting the issue

`Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices`

I have the following in xml

`
    <color tools:override="true" name="ucrop_color_toolbar_widget">@color/primary</color>`

I also tried
`options.setToolbarColor(ContextCompat.getColor(activity, R.color.primary));`

Still have the same issue.

**Comment by shliama** [comment]
Yes, the message is printed, but color should be the one you put in your colors.xml
or `options.setToolbarWidgetColor();`

**Comment by voidstarfire** [comment]
To repeat maybe I wasn't clear
I have this in my colors.xml under values directory

```
<!-- UCrop colors -->
<color tools:override="true" name="ucrop_color_toolbar_widget">@color/primary</color>
```

I also have
`options.setToolbarColor(ContextCompat.getColor(activity, R.color.primary))`

So I have both. I still encounter the error
`Mutate() is not supported for older platform - Therefore, override color resource (ucrop_color_toolbar_widget) in your app to make it work on pre-L devices
`

**Comment by shliama** [comment]
You will **always** get this message in the logcat for devices < Lollipop.
But it's just a message (in next update I'll make it not Log.e but Log.i).
Color should be fine if you override it in your colors.xml under values directory. Just forget about that message.
`options.setToolbarColor` changes background of the toolbar - not it's icons.

**Comment by voidstarfire** [comment]
I overrided it and there seems to be some bugs.

1. How do I make the title green as well?
2. The text has vanished.

![device-2016-04-25-125156](https://cloud.githubusercontent.com/assets/6940726/14781777/d6e1f3e0-0ae4-11e6-982d-3a68dc2d4c33.png)

**Comment by voidstarfire** [comment]
I only want green and white, how would I go about this, since there is no set primary and set secondary :-)

**Comment by shliama** [comment]
![device-2016-04-25-140336](https://cloud.githubusercontent.com/assets/2311626/14781977/c1b6aaec-0aee-11e6-8c31-7592818c0529.png)
So, for this setup I did following:

```java
options.setStatusBarColor(Color.BLUE);
options.setToolbarColor(Color.RED);
options.setActiveWidgetColor(Color.GREEN);
```

and also overridden toolbar widget color (yellow icons, loader and title):
```xml
<color name="ucrop_color_toolbar_widget">@color/yellow</color>
```

**Comment by voidstarfire** [comment]
Omg I'm laughing my ass off. Thanks for the response seems to be resolved.
Awesome library btw.

**Comment by shliama** [comment]
Glad to help (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
