### ISSUE TITLE
uCrop crashing on KitKat device

### ISSUE THREAD

**Issue by l3uddz** [Yalantis/uCrop#96]
http://pastebin.com/pW9NcL5x

The same code works perfectly fine on Lollipop/Marshmallow. Is this an issue with the library or something I am potentially doing, it seems unclear from the logcat above.

**Comment by shliama** [comment]
I think you should enable vector support, check this out:
https://github.com/Yalantis/uCrop/issues/84

**Comment by l3uddz** [comment]
Thankyou this helped, also had to set project to use gradle 2.0 and then immediately it worked.
