### ISSUE TITLE
IllegalArgumentException: x + width must be <= bitmap.width()

### ISSUE THREAD

**Issue by TheWhiteLlama** [Yalantis/uCrop#98]
Hi there!

I love this great lib and I don't wanna miss it! But since 1.5.0 or so, our users managed to produce this error:

`IllegalArgumentException: x + width must be <= bitmap.width()`

How does it come and how can I fix it?
Thank you for your reply!

**Comment by shliama** [comment]
Hi @TheWhiteLlama and thanks for using our library 👍 
Weird, this bug was fixed couple versions ago, but I think not for all cases (hard to reproduce).
Anyway, version 2.0 is coming out really soon and this bug won't be a problem anymore.

**Comment by ben-zhong** [comment]
@shliama so glad to hear version 2.0 is close!

**Comment by TheWhiteLlama** [comment]
Thank you for your answer! I think then there's no other choice than waiting ;)

**Comment by shliama** [comment]
@ben-zhong @TheWhiteLlama please update to version 2.0 and comment if there are any issues :octocat:

**Comment by premacck** [comment]
So I got an issue related to this one in version `2.2.3`.
Firstly, this is a very good library, but I was getting reports from the users that they're encountering toast messages like `x + width must be <= bitmap.width()`.
I couldn't reproduce it at first, but I was able to reproduce it by using `setMaxScaleMultiplier(2f)`

I took in an image of approx 16:9 aspect ratio like this one [here](https://drive.google.com/open?id=1umw3CwLPtoCXK6ljb6UpzjxAvVZwbayb)

But when I clicked on "3:4" aspect ratio, it turned to something like [this](https://drive.google.com/open?id=1ivgO3zWyWtPIgz0N32beMdsvs1MstaR_)
As you can see, the crop bounds are still out of the image bounds.

When I was not using the `setMaxScaleMultiplier(2f)` (the same as in the build that is in production, with the users), in my device the image was scaling properly up to the crop scale.
but after using `setMaxScaleMultiplier(2f)`, above scenario was happening in my device.

Is this issue intermittent, occuring only on some devices? Or is this a scaling issue?
